### ISSUE TITLE
Kubectl location preferences are lost on every launch of Lens ide

### ISSUE THREAD

**Issue by aaraodeo** [lensapp/lens#1010]
**Describe the bug**
Kubectl location preferences are lost on every launch of Lens ide

**To Reproduce**
1. Start Lens ide
2. Last configured cluster is opened.
3. Able to see pods in workloads
4. Open Terminal. An Error Alert message is displayed:
   A JavaScript error occurred  in the main process.
   Uncaught Exception:
   Error:  EPERM: operation not permitted , open
   'C:\Users\user\AppData\Roaming\Lens\binaries\kubectl\1.18.8\kubectl.exe'
5. Close the Alert message.
6. Goto File >> Preferences, unCheck Kubectl Binary
   In path to Kubectl binaries, specify
   C:\Program Files\Docker\Docker\resources\bin\kubectl.exe
7. Close Preferences
8. Open Terminal, issue following command:
   kubectl version --short
  It works and gives following output:
  Client Version: v1.18.8
  Server Version: v1.18.8
9. Close the Lens Ide
10. Start the Lens Ide again
11. The issue re-occurrs, i have to set again the kubectl path

**Expected behavior**
Kubectl location preferences needs to be preserved for user.

**Screenshots**
N/A

**Environment (please complete the following information):**
- Lens Version: 3.6.5
- OS: Windows 10 pro 64 bit 1909 (OS Build 18363.1082)
- Installation method (e.g. snap or AppImage in Linux): 
 Lens-Setup-3.6.5.exe on Windows 10 OS
https://github.com/lensapp/lens/releases/download/v3.6.5/Lens-Setup-3.6.5.exe
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

**Additional context**
Testing on Docker Desktop Version: 2.4.0
