### ISSUE TITLE
Add information about the newer startupProbe

### ISSUE THREAD

**Issue by Mr-Wouter** [lensapp/lens#1034]
**What would you like to be added**:
On the details panel of a pod, please add information about the newer "startupProbe" element, now it shows only the "readinessProbe" and the "livenessProbe". 

Probes are configured like this:

```
        startupProbe:
          failureThreshold: 30  
          httpGet:
            path: /api/health/startup
            port: 80
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /api/health/readiness
            port: 80
        livenessProbe:
          httpGet:
            path: /api/health/liveness
            port: 80
```

**Why is this needed**:
For consistency, I can see other probes in the UI, why not this one?

- Kubernetes distribution: AKS
- Desktop OS: Windows

This screenshots show the view contains only 2 of the 3 probes:
![image](https://user-images.githubusercontent.com/8132813/95228562-c9492100-07ff-11eb-8339-f33687d518d7.png)
