### ISSUE TITLE
Boolean not rendering on additional printer columns.

### ISSUE THREAD

**Issue by Vilsol** [lensapp/lens#1071]
**Describe the bug**
When a CRD has a boolean additional printer column, it doesn't show the value in the table.

**To Reproduce**
Apply this CRD, and then the example resource.
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: boolexamples.bool.example.com
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.randomBool
    name: Bool
    type: boolean
  group: bool.example.com
  names:
    kind: BoolExample
    listKind: BoolExampleList
    plural: boolexamples
    singular: boolexample
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            randomBool:
              type: boolean
          required:
          - randomBool
          type: object
        status:
          type: object
      type: object
```
```yaml
apiVersion: bool.example.com/v1
kind: BoolExample
metadata:
  name: randombool-sample
spec:
  randomBool: true
```

**Expected behavior**
When viewing the `BoolExample` CRD tab, the resource should have a boolean `true` in its row.

**Environment (please complete the following information):**
- Lens Version: 3.6.6
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Installer
 
**Logs:**
No relevant logs in the console or debug tools.

**Additional context**
Executing `kubectl` shows the value correctly:
```bash
$ kubectl get boolexamples
NAME                BOOL
randombool-sample   true
```
