### ISSUE TITLE
Helm3 app does not work with lens ide v3.6.7 behind http proxy

### ISSUE THREAD

**Issue by aaraodeo** [lensapp/lens#1098]
**Describe the bug**
Helm3 app is not working in lens ide 3.6.7 behind http proxy

**To Reproduce**
Steps to reproduce the behavior:Steps to reproduce the behavior:
1. Start Lens ide
2. It connects to last known k8s cluster configuration
3. Goto Workloads >> Pods 
4. It shows details of the running pods in k8s cluster
5. Now goto Apps >> Charts
6. It takes a very long time to show list of charts.
7. Click Releases. It shows list of Helm releases.
8. Click on one of the release. It shows release details in a new windows. Now click Upgrade button.
9. It opens a terminal in a new tab with title "Helm Upgrade:" and its remains stuck in this with a busy rolling circle symbol and it does not comes out of it.
10. Now goto Charts and click any of the available chart.
11. It tries to open the chart details in a new windows and its remain stuck in this with a busy rolling circle symbol and it does not comes out of it.

**Expected behavior**
Helm Release Upgrade to be completed successfully and Chart details to be shown without any issue.

**Screenshots**
![Screenshot 2020-10-18 182255](https://user-images.githubusercontent.com/9564014/96368193-38b00080-1170-11eb-982e-741cd6c957a3.jpg)
![Screenshot 2020-10-18 182333](https://user-images.githubusercontent.com/9564014/96368194-39e12d80-1170-11eb-9f0c-73b3660e9682.jpg)

**Environment (please complete the following information):**
- Lens Version: V3.6.7
- OS: Windows 10 pro 64 bit (Version 1909 OS Build 18363.1082)
- Installation method (e.g. snap or AppImage in Linux):  Windows installer (Lens-Setup-3.6.7.exe)
- Kubernetes: Docker Desktop 2.4.0.0

**Logs:**
N/A

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

**Additional context**
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}

Note: I am using a http proxy to connect to internet.

The steps mentioned above to reproduce the issue works fine on a another machine connected to internet without using a proxy.

So its seems helm3 does not work with lens ide 3.6.7 behind http proxy.
