### ISSUE TITLE
Missing metrics from windows nodes

### ISSUE THREAD

**Issue by mkoziel2000** [lensapp/lens#1218]
**Describe the bug**
When Prometheus is installed, I can see metrics for the Linux nodes (CPU, Memory, Disk)...but the same metrics are not reflected for windows nodes.

Reading revealed that cAdvisor does not know how to gather metrics from windows nodes.  A windows_exporter.exe service needs to run in order to collect metrics.  Once the service is installed and metrics are being collected on the windows nodes, there is still the act of tying it back up into Prometheus and Lens.

I have not been able to figure out the magic configuration that makes this scraping happen such that the metrics show up in Lens.

**To Reproduce**
1. Create a cluster with both windows nodes (earmarked for running windows containers) and linux nodes
2. Connect Lens to Cluster and turn on prometheus
3. Install windows_exporter.exe as a service on the windows worker nodes
3. Go to "Nodes" dashboard in Lens.  Metrics will only show for linux nodes

**Expected behavior**
Metrics should show for linux and windows nodes.

**Screenshots**
![image](https://user-images.githubusercontent.com/11468797/98050200-693d9e80-1dee-11eb-823e-21155cfc5b0a.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.7
- OS: [e.g. OSX] Windows 10 Pro (Lens), Ubuntu 20 (K8s nodes), Windows 2019 (Win worker nodes)
- Installation method:  MSI

**Comment by CoreyCaldwell** [comment]
Couple tips to help you get closer so the prometheus metrics at least get scraped from the windows node exporter after its installed on the bare node: (note: tested with a helm deployed prometheus operator configuration)

Install windows metrics on bare node
```
$WebClient = New-Object System.Net.WebClient
$WebClient.DownloadFile("https://github.com/prometheus-community/windows_exporter/releases/download/v0.15.0/windows_exporter-0.15.0-amd64.msi","C:\windows_exporter-0.15.0-amd64.msi")
msiexec /i C:\windows_exporter-0.15.0-amd64.msi ENABLED_COLLECTORS=cpu,cs,container,logical_disk,memory,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,net,os,service,system,tcp LISTEN_PORT=9100
```

create service in k8s (I think the annotations and labels here are what prometheus are looking for to automagically grab available metrics)
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: prometheus
    component: node-exporter
    release: prometheus
  name: prometheus-node-exporter-windows
  namespace: default
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
```

add endpoint to service with ip of node
```
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-node-exporter-windows
subsets:
  - addresses:
      - ip: <<ip address of node where you installed windows metrics exporter>>
    ports:
      - port: 9100
```

verify metrics are getting picked up
`kubectl port-forward <<prometeus pod name>> 9090:9090`
Browse to localhost:9090 and check the graph for something windows/.net-y like "windows_netframework_clrjit_jit_il_bytes_total"

At this point theres still a couple gotchas

- looks like all the windows metrics are prefixed with windows_ so lens would need to be updated to look at these
- its still a manual process to install the windows node exporter (but there should be a way to script this at least in azure)
- its still a manual process to maintain the endpoints that prometeus scrapes to pull in the metrics, nodes will likely get added and removed so we'd need something to keep that in sync

Just wanted to share what I have so far if it helps someone else out
