### ISSUE TITLE
Error trying to exec into a GKE pod.  

### ISSUE THREAD

**Issue by yash-shah-efx** [lensapp/lens#1314]
**Description**
While trying to exec into the pod, by clicking on the shell icon in the options on the far right, I am getting an error ```unable ti=o upgrade backend: error dialing backend: dial tcp 10.142.45.34:443: connectex: A connection attempt failed because the connected party did not properly respond after a peri
od of time, or established connection failed because connected host has failed to respond.```

**To Reproduce**
Not sure about reproducing it. 

1- After cluster is authenticated, try clicking on the shell command.
2 - It will open up a terminal window and execute a command of the following `kubectl exec -it -n default xxx -c yyy "--" sh -c "clear; (bash || ash || sh)"`

**Expected behavior**
The connection works fine from local workstation or from a jumpbox.

**Screenshots**
Added

**Environment (please complete the following information):**
- Lens Version: 3.6.7
- OS: [e.g. OSX] Windows 10 Enterprise
- Installation method (e.g. snap or AppImage in Linux): UI
  
**Logs:**

```
error: unable to upgrade connection: error dialing backend: dial tcp 10.142.45.34:443: connectex: A connection attempt failed because the connected party did not properly respond after a peri
od of time, or established connection failed because connected host has failed to respond.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://10.142.45.34
  name: gke_ews-sre-tools-npe-5b26_us-east1_ews-es-us-east1-npe
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://10.148.202.2
  name: gke_ews-sre-tools-npe-5b26_us-east1_gke-ews-sre-es-useast1
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://10.151.137.18
  name: gke_ews-sre-tools-npe-5b26_us-west1_ews-es-us-west1-npe
contexts:
- context:
    cluster: gke_ews-sre-tools-npe-5b26_us-east1_ews-es-us-east1-npe
    user: gke_ews-sre-tools-npe-5b26_us-east1_ews-es-us-east1-npe
  name: gke_ews-sre-tools-npe-5b26_us-east1_ews-es-us-east1-npe
- context:
    cluster: gke_ews-sre-tools-npe-5b26_us-east1_gke-ews-sre-es-useast1
    user: gke_ews-sre-tools-npe-5b26_us-east1_gke-ews-sre-es-useast1
  name: gke_ews-sre-tools-npe-5b26_us-east1_gke-ews-sre-es-useast1
- context:
    cluster: gke_ews-sre-tools-npe-5b26_us-west1_ews-es-us-west1-npe
    user: gke_ews-sre-tools-npe-5b26_us-west1_ews-es-us-west1-npe
  name: gke_ews-sre-tools-npe-5b26_us-west1_ews-es-us-west1-npe
current-context: gke_ews-sre-tools-npe-5b26_us-east1_ews-es-us-east1-npe
kind: Config
preferences: {}
users:
- name: gke_ews-sre-tools-npe-5b26_us-east1_ews-es-us-east1-npe
  user:
    auth-provider:
      config:
        access-token: ya29.c.Ko0B5AdqHV4FeR1GNAcuA13xKZ4coIlsSXUZ4Q4RL-CVMhkCUt8pIUAdxnUQ35Qp7HOANgNJ_zbAViCAm7-MsuFjrWeggO3aaBGfN_Xnv3ENM11rQNNJNUnnG1kMoI40TjLbTLsUfNWf0G3KWSNsZQNMaZjREPpog2KuaPDqY2aZH9PY9qagkd8vDHsHeI7X
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\yxs71\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-11-05T23:14:25Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_ews-sre-tools-npe-5b26_us-east1_gke-ews-sre-es-useast1
  user:
    auth-provider:
      config:
        access-token: ya29.c.Ko0B4geu3TjxnWukPS4nXfq4Au2xXD_V4M41-onKSHsXV6ZMtupnc-WFGeufBPTlnq4pnQ-_yYTDmqKQGQSDCi8R9tMpWfmfc2EeWefolDiZPhtUucRA2Bc4nlSKGKFuUzTCTbvMrFwc7Lbx51pZ59qkdBGUe2qr3Ij-bQn310rR_L3DIy4EIT8b7KZMU4V2
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\yxs71\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-10-27T22:41:01Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_ews-sre-tools-npe-5b26_us-west1_ews-es-us-west1-npe
  user:
    auth-provider:
      config:
        access-token: ya29.c.Ko0B4wcbTebcm7_MIsDnXht2HHOsRit2EeIm5S4x_m_8rDk63i7o5_fahEa5z9uJi_TYabki0mbrB3afKPm1hRTzMx1yhFPbFatUgRJWPpx5ZR_knsw2IJFzBHD65xStzlLB1NhRkGkw_Xi2tr4Wu2XbjtCSowUHHSZdThvb30CK_CDiWfSVURkKBCZcPKdk
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\yxs71\AppData\Local\cloud-code\installer\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-10-30T18:26:05Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp

```
