### ISSUE TITLE
lens rejects connections to self-signed installs, such as microk8s

### ISSUE THREAD

**Issue by nergdron** [lensapp/lens#135]
**Describe the bug**
when using a local environment, like microk8s, lens fails to connect with the error "http: proxy error: x509: certificate signed by unknown authority"

**To Reproduce**
1. install microk8s
2. dump config to local dir with `microk8s.kubectl config view > ~/.kube/config`
3. try to connect to local microk8s kube config with lens

**Expected behavior**
lens connects and manages microk8s

**Environment (please complete the following information):**
- Lens Version: 3.0.1
- OS: Ubuntu 19.04
- Installation method:  snap
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
error: Failed to connect to cluster microk8s: {"name":"StatusCodeError","statusCode":502,"message":"502 - \"x509: certificate signed by unknown authority\"","error":"x509: certificate signed by unknown authority","options":{"json":true,"timeout":10000,"headers":{"host":"16ae7648-dd2d-4b9a-893f-744d92ca2939.localhost:49152"},"uri":"http://127.0.0.1:49152/api-kube/version","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":502,"body":"x509: certificate signed by unknown authority","headers":{"content-type":"text/plain","date":"Tue, 17 Mar 2020 20:01:16 GMT","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"127.0.0.1:49152","port":"49152","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":"/api-kube/version","path":"/api-kube/version","href":"http://127.0.0.1:49152/api-kube/version"},"method":"GET","headers":{"host":"16ae7648-dd2d-4b9a-893f-744d92ca2939.localhost:49152","accept":"application/json"}}}}
```

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://127.0.0.1:16443
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    password: OMITTED
    username: admin
```
