### ISSUE TITLE
Add support for Cluster.ProxyURL

### ISSUE THREAD

**Issue by aservedio** [lensapp/lens#1529]
**What would you like to be added**:
Support the kubeconfig cluster.proxy-url option [introduced in 1.19](https://github.com/kubernetes/kubernetes/pull/81443/files#diff-f2db607d3757deae0b89ff32352f433d9c7dce7dbaa594dad5903f6b7826f698).

```yaml
apiVersion: v1
clusters:
- cluster:
    server: "..."
    proxy-url: "..."
```

**Why is this needed**:
Cannot connect to a cluster that uses proxy-url cluster config. kubectl v1.19+ can connect fine with that config but not lens.

**Environment you run Lens application on:**
Linux/Snap
