### ISSUE TITLE
Terminal, A javascript error occurred in the main process

### ISSUE THREAD

**Issue by san360** [lensapp/lens#156]
**Describe the bug**
Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL.

**To Reproduce**
1. Add cluster with kubeconfig file manually
2. Click on Terminal
3. See error

**Expected behavior**
Terminal should have started

**Screenshots**
![image](https://user-images.githubusercontent.com/6613457/77615512-d7a0b100-6f2f-11ea-825c-456a63e5d796.png)

**Environment (please complete the following information):**
- Lens Version: 3.01
- OS: Mac
- Installation method (e.g. snap or AppImage in Linux): Lens.app
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
current-context: kube1-dev
contexts:
- name: kube1-dev
  context:
    cluster: kube1-dev
    user: kube1-dev-sxxxxx
users:
- name: kube1-dev-sxxxxx
  user:
    token: xxxxxxxx
clusters:
- name: kube1-dev
  cluster:
    certificate-authority-data: xxxxxxx
    server: https://kube1-svc.dev.xxxx.xxxx..xxxxx
```

**Additional context**
