### ISSUE TITLE
add profile support

### ISSUE THREAD

**Issue by paquettej** [lensapp/lens#158]
**What would you like to be added**:
When adding a cluster, prompt for which aws profile to use

**Why is this needed**:
I have multiple environments and to prevent errors I explicitly do not have a default profile

**Environment you are Lens application on:**
EKS
- Kubernetes distribution: [EKS, AKS, GKE, Rancher, ...]
- Desktop OS: <the OS Lens app runs on in your case>
MacOS

**Comment by jakolehm** [comment]
AWS_PROFILE can be defined in EKS kubeconfig (as env), see https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html.

**Comment by o6uoq** [comment]
I have not found a way to use Lens to use multiple AWS profiles and/or multiple EKS clusters, no way to use the app/product as I cannot connect to an AWS based EKS cluster as yet which is not default.

**Comment by ozkologlu** [comment]
Even with AWS_PROFILE evn var set in kubeconfig still getting an error connecting to EKS (connection works fine in a terminal)

```
Connecting ...
Authentication proxy started
could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2020/04/03 08:35:49 http: proxy error: getting credentials: exec: exit status 1
```

**Comment by Nuru** [comment]
I have Lens working with multiple clusters each requiring a different IAM role. It is definitely able to be done. 

I believe the appropriate requirement for Lens is to work when `kubectl` works and present an error when it does not. It is asking too much for Lens to extend beyond the capabilities of `kubectl`.

The additional challenge with Lens is that it launches as a separate process, and therefore does not have access to your environment variables. If you need AWS authentication, you must configure your authentication in a way that `aws` CLI can obtain credentials without reference to your environment variables. 

@snowmoonsoftware you do not need to specify a default AWS profile. You do, however, need to set up your kubeconfig and the rest of your environment to allow `kubecfg` to work on the command line without environment variables. 

As @jakolehm pointed out, you can write your kubeconfig to specify an `aws` CLI command to run. This kubeconfig does not have to be the one you use for anything but Lens, you can write/paste it into Lens as a custom kubeconfig, and it can specify the `AWS PROFILE` to use and any other enviornment variable values you want to set, including `AWS_CONFIG_FILE`.  The `aws` CLI can get credentials from a variety of sources besides environment variables, including files like `~/.aws/config`, `~/.aws/credentials`, and `~/.aws/cli/cache/*` or via the AWS metadata server. 

There are a number of open source tools to help you do this securely, too many to list. The whole arena of security and authentication is large and complex, and I do not think it fair to ask Lens to weigh into it. I am in favor of avoiding feature and scope creep and drawing the line at Lens requiring you to supply a kubeconfig that works on your machine, the way you have your machine set up, in the environment you have Lens running. 

@ozkologlu after you configure your kubeconfig to use an AWS_PROFILE, you need to configure the profile in your `~/.aws/config` to get credentials from somewhere other than environment variables, as I explained above.

**Comment by Nuru** [comment]
To update, I recommend EKS users configure Lens to use a `KUBECONFIG` that specifies the profile to use. For example (partial configuration)
```yaml
users:
- name: arn:aws:eks:us-east-2:123456123456:cluster/eks-cluster-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - eg-cluster
      command: aws
      env:
      - name: AWS_PROFILE
        value: my-aws-profile
```

You can then use the free [Leapp](https://www.leapp.cloud/) app to manage your AWS authentication, including prompting for MFA tokens as needed.

**Comment by akullpp** [comment]
Anyone got it to work with Leapp recently? I keep getting "Invalid credentials"...

**Comment by rchojn** [comment]
@akullpp I have the same problem

**Comment by joebowbeer** [comment]
@akullpp works for me.

I run `aws eks update-kubeconfig` to update kubeconfig and then I add the env array with the AWS_PROFILE assignment.

Let update-kubeconfig do the heavy lifting. If I were to guess, I suspect your client.authentication.k8s.io api version is no longer recognized. Try v1.

**Comment by rchojn** [comment]
@joebowbeer  I tried exact flow that you've proposes. I am using `client.authentication.k8s.io/v1beta1`. `kubectl` works fine, but not `lens`. I think it could be connected to `AWS_SESSION_TOKEN`. How to deal with that?

**Comment by aleksei-zolotukhin** [comment]
> @joebowbeer I tried exact flow that you've proposes. I am using `client.authentication.k8s.io/v1beta1`. `kubectl` works fine, but not `lens`. I think it could be connected to `AWS_SESSION_TOKEN`. How to deal with that?

I have the same issue.
Here is the error message that I get if try to use KUBECONFIG generated by AWS CLI.

```
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::1234567890:assumed-role/OrganizationAccountAccessRole/botocore-session-1664394168 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1234567890:role/OrganizationAccountAccessRole

E0929 00:48:03.029715 106981 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws failed with exit code 254

getting credentials: exec: executable aws failed with exit code 254
```
Meanwhile, `kubectl` works perfectly.

Below is how configuration of EKS cluster looks like:
```
- name: arn:aws:eks:us-east-1:1234567890:cluster/example-dev-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - example-dev-eks
      - --role
      - arn:aws:iam::1234567890:role/OrganizationAccountAccessRole
      command: aws
      env:
      - name: AWS_PROFILE
        value: example-second
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

This is how AWS config `example-second` looks like:
```
[profile example]
region = us-east-1

[profile example-second]
role_arn = arn:aws:iam::1234567890:role/OrganizationAccountAccessRole
source_profile = example
region = us-east-1
```
