### ISSUE TITLE
[Windows 3.0.1] cannote parse kubeconfig

### ISSUE THREAD

**Issue by fabio-s-franco** [lensapp/lens#161]
**Describe the bug**
First time I tried to add a cluster it worked. Then I closed it, the cluster disappeared and I had to add it again. Followed the same steps:

1 - Click Add Cluster
2 - On Select kubeconfig, choos custom...
3 - Run on powershell: kubectl config view --minify --raw
4 - Copy the result
5 - Paste in the designated area inside lens
6 - Click Add Cluster(s)

This time I got "cannot parese kubeconfig"

Since I use ditto (for clipboard management), I even got back the kubeconfig that worked and tried again. Without success

**Environment (please complete the following information):**
- Lens Version: 3.0.1
- OS: Windows 10
- Installation method (e.g. snap or AppImage in Linux): Installer from github releases
 
**Logs:**
```
 info: Checking for update
info: Update for version 3.0.1 is not available (latest version: 3.0.1, downgrade is disallowed).
```

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: --removed--
    server: https://0.0.0.0
  name: changed
contexts:
- context:
    cluster: changed_cluster
    user: changed_cluster
  name: changed_cluster
current-context: changed_cluster
kind: Config
preferences: {}
users:
- name: changed_cluster
  user:
    auth-provider:
      config:
        access-token: --removed--
        cmd-args: config config-helper --format=json
        cmd-path: C:\..changed..\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-03-26T17:24:03Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
