### ISSUE TITLE
App crash when trying to display a ResourceQuota

### ISSUE THREAD

**Issue by dockerpac** [lensapp/lens#1618]
**Describe the bug**
App Crash when trying to display a ResourceQuota object

**To Reproduce**
1. Create a ResourceQuota in a namespace :  

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
spec:
  hard:
    limits.cpu: '20'
    limits.memory: 20Gi
    requests.cpu: '10'
    requests.memory: 20Gi
```

2. Go to Configuration --> Resource Quotas
3. Click on the ResourceQuota that was created

**Expected behavior**
Display quotas

**Screenshots**
![image](https://user-images.githubusercontent.com/41171215/100881450-3bf81500-34ae-11eb-9710-976c266321e2.png)

**Environment (please complete the following information):**
- Lens Version:4.0 rc2
- OS: OSX
- Installation method : .dmg

**Logs:**

**Kubeconfig:**

**Additional context**
It works on Lens 3.7
