### ISSUE TITLE
Lens 4.0 Breaking on MAC

### ISSUE THREAD

**Issue by ub-wroteIt** [lensapp/lens#1700]
**Describe the bug**
Unable to use & load any section after upgrading to 4.0.0 on MAC.

**To Reproduce**
1. Update to 4.0.0
2. Start Lens
3. Open Developer console to see the error

**Expected behavior**
All sections should load the Kubernetes related resources properly

**Screenshots**
<img width="1668" alt="Screen Shot 2020-12-08 at 6 41 30 PM" src="https://user-images.githubusercontent.com/11176924/101489294-c2b56200-3986-11eb-8bf2-3f2d2bde3a72.png">

**Environment (please complete the following information):**
- Lens Version: 4.0.0
- OS: [e.g. MacOS High Sierra Version 10.13.6]
- Installation method (e.g. snap or AppImage in Linux): Auto Upgrade

**Comment by areknow** [comment]
I have the same issue. And when I open a lower version, it auto updates to v4. Now I can only use lens by continually reinstalling v3.6.9

**Comment by spyro2000** [comment]
Why on earth isn't it possible to deactivate auto-update? Maybe you could try to restrict write-access to the binary to prevent it from overwriting the current version?

**Comment by sampopes** [comment]
Facing the same issue. I reinstalled 3.9.6 but it doesn't work anymore.

**Comment by Arnonrgo** [comment]
@ub-wroteIt do you have admin on the cluster - I have similar issue on clusters where I am not admin (and it works fine on ones I am), both on Macs and Windows https://github.com/lensapp/lens/issues/1682

**Comment by fjvela** [comment]
Same here, opened lens in debug mode on windows and no error are show in logs.
With lens 3.6.9 it works fine. I'm not cluster admin.

**Comment by ub-wroteIt** [comment]
@Arnonrgo No, I am not an admin on a cluster. The same cluster was working on an older version(with non-admin role).

**Comment by rvillars** [comment]
Same issue here too. Works with 3.9.6. Broken with 4.0. Forced to upgrade. Also not admin on the cluster.

**Comment by myspotontheweb** [comment]
I manually specified the namespaces I have access to on the cluster 

* File -> Cluster Settings (Ctrl-Shift-S)

Lens appears to be working again.

**PS**

* Restart Lens after adding namespaces

**Comment by ub-wroteIt** [comment]
@myspotontheweb , This workaround dint worked for me

**Comment by jdomag** [comment]
Is anybody from Lens working on this!? We lost an access to our clusters and had to switch to kubectl CLI

**Comment by jakolehm** [comment]
Could someone try with the latest version?

**Comment by abelal83** [comment]
I'm afraid this is still not working on Windows 10 OS either. It looks like something happened with the 4.0.0 release. All the versions I've tested from this version onward do not work (4.0.0, 4.2.0, 5.1.3). The most recent v3 - which is 3.9.10 - works perfectly with limited permissions.

This is the custom role that works fine in v3 but stopped working in v4 onwards

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
rules:
  - verbs:
      - get
      - list
      - watch
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - resourcequotas
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/portforward
      - services/proxy
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - get
      - list
      - watch
      - update
      - patch
      - delete
    apiGroups:
      - ''
      - apps
      - extensions
    resources:
      - pods
      - services
      - deployments
      - replicasets
      - ingresses
      - statefulsets
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - metrics.k8s.io
      - events.k8s.io
    resources:
      - pods
      - events

```

**Comment by Nokel81** [comment]
@abelal83 What is your `ClusterRoleBinding` for that cluster role? I have used the following and cannot reproduce not being able to view the resources:

```yml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer

```

**Comment by abelal83** [comment]
@Nokel81 

That role is bound to namespace only

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ofs-tst-team-devs
  namespace: ofs-tst
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 09fa736c-b5a4-48d4-9f2b-f035ae3a6540
    namespace: ofs-tst
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespace-developer
```

We have `ClusterRoleBinding` that allows view access to all namespaces

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespaces-view
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
```

this is the binding for namespace view only

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespaces-view-ofs-tst-team
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: 5a81adb8-d6e4-4fc9-99c1-f597bd814c92
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: namespaces-view

```

I should add no developers have access to the default namespace, could lens 4+ be looking at default namespace and see's no permissions so doesn't bother checking any other namespace like v3 did? 

In lens 4+ the only thing that does work is viewing namespaces only which I assume namespace `ClusterRoleBinding` is granting and working however, `RoleBinding` is no longer working.

using kubectl within lens (kubectl get pods -n ofs-tst) works as does visual studio code kubernetes extension(https://marketplace.visualstudio.com/items?itemName=ms-kubernetes-tools.vscode-kubernetes-tools).

As a cluster administrator I'm not affected but all our developers who love lens are :(
