### ISSUE TITLE
Object details panel is blank for CronJob resources

### ISSUE THREAD

**Issue by mlazzaro-better** [lensapp/lens#1739]
**Describe the bug**
When attempting to view details on a CronJob resource, the details panel is blank. The header with the controls (name, Edit button, Delete button, etc.) still renders normally, but the panel below that usually shows details like the labels, prior runs, etc., is blank.

The details panel works fine for all other resources, and the same behavior (missing details) is consistent across clusters, as well. Behavior can also be reproduced by other teammates running Lens 4.0.1 against the same clusters.

**To Reproduce**
1. Open Lens
2. Select a cluster that includes at least one CronJob
3. From the side panel, select "CronJobs" from under the "Workloads" heading
4. Click one of the CronJobs from the list shown in the main panel
5. The details panel opens on the right side, but no details are shown.

Note: Pulling up details for a Job resource associated with a CronJob works normally, but when clicking through to the associated CronJob via the link in the Job details panel, the same blank panel is shown for the CronJob.

**Expected behavior**
The details panel should show the normal details information, such as labels, prior execution history, associated Jobs, etc.

**Screenshots**
![Screen Shot 2020-12-10 at 11 01 40 AM](https://user-images.githubusercontent.com/68666782/101796705-349cc100-3ad7-11eb-9176-efc19228b0b8.png)
![Screen Shot 2020-12-10 at 11 02 04 AM](https://user-images.githubusercontent.com/68666782/101796710-36ff1b00-3ad7-11eb-9106-55c5b748cff7.png)
![Screen Shot 2020-12-10 at 11 02 25 AM](https://user-images.githubusercontent.com/68666782/101796718-39fa0b80-3ad7-11eb-82c5-7b8121a6f624.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.1 (Electron 3.9.5, Chrome 38.0.4103.122, Node 12.14.1)
-- Also occurred on 4.0.0
- OS: OSX Catalina 10.15.6 (19G2021)
- Installation method (e.g. snap or AppImage in Linux): brew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
[32minfo[39m: [EXTENSION]: enabled lens-license@0.1.0
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [CLUSTER]: activate {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: bind events {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: reconnect {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/config.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-workspace-store.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-extensions.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] start to listen (1)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [LENS-VIEW]: init dashboard, clusterId=65087feb-ecc1-4734-800b-471151903b3c
[31merror[39m: Can't find working API for the Kubernetes resource ingresses
[32minfo[39m: [KUBE-AUTH]: out-channel "kube-auth:65087feb-ecc1-4734-800b-471151903b3c" {"data":"Authentication proxy started\n","meta":{"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/config.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-workspace-store.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-extensions.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] start to listen (5)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [APP]: Init dashboard, clusterId=65087feb-ecc1-4734-800b-471151903b3c, frameId=5
[32minfo[39m: [LENS-VIEW]: loaded from http://65087feb-ecc1-4734-800b-471151903b3c.localhost:60428/
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus" not found
[32minfo[39m: using operator as prometheus provider
[33mwarn[39m: PrometheusLens: failed to list services: services "prometheus-server" not found
[32minfo[39m: using operator as prometheus provider
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/config.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-workspace-store.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-extensions.json
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [CLUSTER-STORE] start to listen (5)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [APP]: Init dashboard, clusterId=65087feb-ecc1-4734-800b-471151903b3c, frameId=5
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [STORE]: LOADED from /Users/mlazzaro/Library/Application Support/Lens/extension-store/lens-telemetry/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
[32minfo[39m: [CLUSTER]: refresh {"id":"65087feb-ecc1-4734-800b-471151903b3c","name":"data-02","initialized":true,"ready":true,"online":true,"accessible":true,"disconnected":false}
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://xxxxxxxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ci-04
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://xxxxxxxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-02
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://xxxxxxxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-staging-01
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://xxxxxxxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ops-02
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://xxxxxxxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/prod-03
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://xxxxxxxxxxxxxxxx.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/staging-03
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://xxxxxxxxxxxx
  name: data-01.xxxxxxxxxxxx
- cluster:
    certificate-authority-data: xxxxxxxxxxxx
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ci-04
    namespace: mortgage-pr-60778
    user: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ci-04
  name: ci-04
- context:
    cluster: data-01.xxxxxxxxxxxx
    namespace: data
    user: data-01.xxxxxxxxxxxx
  name: data-01.xxxxxxxxxxxx
- context:
    cluster: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-02
    namespace: default
    user: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-02
  name: data-02
- context:
    cluster: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-staging-01
    namespace: data-staging
    user: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-staging-01
  name: data-staging-01
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ops-02
    namespace: default
    user: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ops-02
  name: ops-02
- context:
    cluster: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/prod-03
    namespace: prod
    user: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/prod-03
  name: prod-03
- context:
    cluster: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/staging-03
    namespace: staging
    user: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/staging-03
  name: staging-03
current-context: data-01.xxxxxxxxxxxx
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ci-04
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - ci-04
      command: aws
      env: null
- name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-02
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - data-02
      command: aws
      env: null
- name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/data-staging-01
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - data-staging-01
      command: aws
      env: null
- name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/ops-02
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - ops-02
      command: aws
      env: null
- name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/prod-03
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - prod-03
      command: aws
      env: null
- name: arn:aws:eks:us-east-1:xxxxxxxxxxxx:cluster/staging-03
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - staging-03
      command: aws
      env: null
- name: data-01.xxxxxxxxxxxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - data-01
      command: aws-iam-authenticator
      env: null
- name: docker-desktop
  user:
    client-certificate-data: xxxxxxxxxxxx
    client-key-data: xxxxxxxxxxxx
```

**Additional context**
