### ISSUE TITLE
Lens Won't Open in Mac

### ISSUE THREAD

**Issue by dogac00** [lensapp/lens#1765]
When I click Lens, the application hangs and is not opening. The window shows "Connecting...".
I am adding the screenshot. Please fix this issue I cannot open Lens for days now.

**To Reproduce**
1. Download Lens for Mac
2. Open Lens

**Environment (please complete the following information):**
- Lens Version: 4.0.2
- OS: MacOS Catalina
- I downloaded dmg file from GitHub.

<img width="1434" alt="Screen Shot 2020-12-13 at 18 39 47" src="https://user-images.githubusercontent.com/26314896/102016551-9d539a00-3d72-11eb-988d-94d7f583c4e8.png">

**Comment by dogac00** [comment]
My Lens config file is like this:

```
apiVersion: v1
kind: Config
preferences: {}
current-context: dev
clusters:
  - name: dev
    cluster:
      server: 'DEV_SERVER'
      insecure-skip-tls-verify: true
  - name: stage
    cluster:
      server: 'STAGE_SERVER'
      insecure-skip-tls-verify: true
  - name: prod_p1_1
    cluster:
      server: 'PROD_SERVER_1'
      insecure-skip-tls-verify: true
  - name: prod_p1_2
    cluster:
      server: 'PROD_SERVER_2'
      insecure-skip-tls-verify: true
contexts:
  - name: dev
    context:
      cluster: dev
      user: dev
  - name: stage
    context:
      cluster: stage
      user: stage
  - name: prod_p1_1
    context:
      cluster: prod_p1_1
      user: prod_p1_1
  - name: prod_p1_2
    context:
      cluster: prod_p1_2
      user: prod_p1_2
users:
  - name: dev
    user:
      username: username
      password: password
  - name: stage
    user:
      username: username
      password: password
  - name: prod_p1_1
    user:
      token: token
  - name: prod_p1_2
    user:
      token: token
```
