### ISSUE TITLE
Application crashed often

### ISSUE THREAD

**Issue by thelastworm** [lensapp/lens#1786]
**Describe the bug**
When I use the application, I sometime face this issue 

**To Reproduce**
I'm not able to really explain, but it's often  happened when i left the node list screen 

**Expected behavior**
A crash of application

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 
- OS: OSX

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Error stack:

 
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:3775674)
    at http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:8681981
    at Array.map (<anonymous>)
    at http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:8681949
    at Array.map (<anonymous>)
    at r.value (http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:8681893)
    at r.value (http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:8687241)
    at ve (http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:18448)
    at http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:70625
    at ce (http://445dfb30-62ed-40ec-85e2-010d374cc5c7.localhost:51421/build/Lens.js:2:16554)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: https://217.182.238.xxx:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: xxxx
    client-key-data: xxx
```

**Additional context**
