### ISSUE TITLE
Lens startup causes MacOS to crash

### ISSUE THREAD

**Issue by zbypy** [lensapp/lens#1805]
**Describe the bug**
When lens 4 is starting up it causes mac OS (big sur) to crash.

**To Reproduce**
1. Click to Lens icon
2. Loading pop-up is displayed
3. After few seconds MacOS crashes - hearing ventilators on high speed, black screen, mac is off

**Environment (please complete the following information):**
- Lens Version: 4.0.3 (started with 4.0.0)
- OS: MacOS Big Sur 11.0.1
- Installation method (e.g. snap or AppImage in Linux): Installation from .dmg

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    server: https://serverdomain.com
  name: serverdomain.com
contexts:
- context:
    cluster: serverdomain.com
    namespace: a-namespace
    user: some-user
  name: thisiscontext
current-context: thisiscontext
kind: Config
preferences: {}
users:
- name: normaluser
  user:
    password: andhispassword
    username: normaluser
- name: user@domain.com
  user:
    auth-provider:
      config:
        client-id: ID.apps.googleusercontent.com
        client-secret: SECRET
        id-token: ID_TOKEN
        idp-issuer-url: https://some.tools.domain.com
        refresh-token: REFRESH_TOKEN
      name: oidc
```

**Additional context**
I upgraded from version 3.6.9 then it started to crash, it works fine when I install 3.6.9 back.
