### ISSUE TITLE
metrics volume size can not be set when installing it from the UI

### ISSUE THREAD

**Issue by matti** [lensapp/lens#183]
https://github.com/lensapp/lens/blob/master/src/features/metrics/03-statefulset.yml.hb#L115

**Comment by 0blu** [comment]
There is a file at `./kontena-lens/resources/features/metrics.ts` that contains the config. But chaining parameters there (and restarting lens) seems to have no effect, the size was still 20GiB.
I had to manually adjust `./kontena-lens/resources/features/metrics/03-statefulset.yml.hb`.

For example
``` yaml
  [... rest of the file ...]
  {{#if persistence.enabled}}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        {{#if persistence.storageClass}}
        storageClassName: "{{persistence.storageClass}}"
        {{/if}}
        resources:
          requests:
            storage: "2Gi"
  {{/if}}
```
