### ISSUE TITLE
Not all Roles and Role-Binding are presented  when choosing All Namespaces

### ISSUE THREAD

**Issue by doronshai** [lensapp/lens#1833]
Not all Roles and Role-Binding are presented and choosing the **All Namespaces** option.
Only after refreshing the IDE, sometimes it resolved.
I think I noticed that it happens just after using the + Bubble button for new user / new role.....

**To Reproduce**
1. Launch Lens **4.0.0**
2. Open the cluster you want
3. Go to **Access** **Control**
4. Go to **Roles**
5. Choose  **All Namespaces**
6. Now You will see partial list of the roles
7. Click Refresh for the IDE
8. Go to roles again, sometimes you will see all roles, sometimes more roles will be missing

**Expected behavior**
When choosing **All Namespaces**, All roles will be presented

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.0.0
- OS: MacOS Catalina 10.15.7 (19H2)
- Installation method (brew cask):

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    server: https://10.11.11.11:6443
  name: k12.io
contexts:
- context:
    cluster: k12.io
    namespace: default
    user: k12.io
  name: k12.io
current-context: k12.io
kind: Config
preferences: {}
users:
- name: default-k12.io
  user:
    token: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
```
