### ISSUE TITLE
Strict environments stop Lens from showing the namespaces it does have access to

### ISSUE THREAD

**Issue by MTijn** [lensapp/lens#1946]
**Describe the bug**
With a strict environment the app is not loading any information about any namespace any more.

**To Reproduce**
1. Have a strict environment where you can see the namespaces but are forbidden to access them
2. Open the app
3. Use that cluster to connect to
4. The app is trying to view pods on the namespaces you do not have access to
5. Then it results in no information shown at all

**Expected behavior**
Even if you do not have access to some namespaces I would expect I do get to see the information of the namespaces I am allowed to connect to.

**Screenshots**
![lens-issue](https://user-images.githubusercontent.com/3725681/104316302-9092a500-54dc-11eb-9727-bd8e165affa8.png)

**Environment (please complete the following information):**
- Lens Version: 4.0.0 and upwards, 3.6.9 works fine
- OS: Ubuntu 20.10
- Installation method (e.g. snap or AppImage in Linux): Snap and AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "pods is forbidden: User \"k8s-martijnk\" cannot list resource \"pods\" in API group \"\" in the namespace \"default\": RBAC: clusterrole.rbac.authorization.k8s.io \"restricted-psp\" not found",
  "reason": "Forbidden",
  "details": {
    "kind": "pods"
  },
  "code": 403
}
```

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: data
    server: some-name
  name: prod
contexts:
- context:
    cluster: prod
    namespace: some-namespace
    user: martijnk
  name: prod
current-context: prod
kind: Config
preferences: {}
users:
- name: martijnk
  user:
    auth-provider:
      config:
        client-id: kubernetes
        id-token: token
        idp-issuer-url: issuer
        refresh-token: refresh-token
      name: oidc
```
