### ISSUE TITLE
Can't connect to GKE cluster after update to v3.1

### ISSUE THREAD

**Issue by MicroBenz** [lensapp/lens#195]
**Describe the bug**
I've installed Lens v3.0.1 and connect to GKE cluster, things work as expected.

But today, after update to version 3.1 after I click connect to cluster. It shows nothing.

![image](https://user-images.githubusercontent.com/9103800/78122361-d9d6a400-7436-11ea-9b97-a2f5ecb33d42.png)

**Environment (please complete the following information):**
- Lens Version: 3.1
- OS: macOS 10.14.4
- Installation method (e.g. snap or AppImage in Linux): .app binary file from Github release

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: //cert
    server: https://34.87.57.144
  name: gke_takemetour-176217_asia-southeast1-a_tagthai-cluster
contexts:
- context:
    cluster: gke_takemetour-176217_asia-southeast1-a_tagthai-cluster
    user: gke_takemetour-176217_asia-southeast1-a_tagthai-cluster
  name: gke_takemetour-176217_asia-southeast1-a_tagthai-cluster
current-context: gke_takemetour-176217_asia-southeast1-a_tagthai-cluster
kind: Config
preferences: {}
users:
- name: gke_takemetour-176217_asia-southeast1-a_tagthai-cluster
  user:
    auth-provider:
      config:
        access-token: // token
        cmd-args: config config-helper --format=json
        cmd-path: /Users/benz/Downloads/google-cloud-sdk/bin/gcloud
        expiry: "2020-04-01T10:33:33Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
