### ISSUE TITLE
Lens 4* versions + RBAC + pods don't appear in the dashboard

### ISSUE THREAD

**Issue by eins** [lensapp/lens#1961]
**Describe the bug**
Hello Lensapp devs

I have a user with only ClusterRoles and Role for specific Namespaces
and the user is part of the group system:basic-user.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - userarn: arn:aws:iam::88888888888:user/Jolla
      username: Jolla
      groups:
        - system:basic-user
```

I can exec all the pods, see the logs in all pods in the specific namespaces with kubectl or Lens-3.6.9.AppImage and Lens-3.6.10.AppImage 

I tested all Lens 4.0 version and the issue persists 

How can I debug this and see why the RBAC config isn't working with Lens 4.*

**Environment (please complete the following information):**
- Lens Version:
  Lens-3.6.9.AppImage
  Lens-3.6.10.AppImage
  Lens-4.0.1.AppImage
  Lens-4.0.2.AppImage
  Lens-4.0.3.AppImage 
  Lens-4.0.4.AppImage
  Lens-4.0.5.AppImage
  Lens-4.0.6.AppImage
  Lens-4.0.7.AppImage
  Lens-4.0.8.AppImage
- OS: 
  linux distros: ubuntu, SB 33, Fedora 33, archlinux
- Installation method (e.g. snap or AppImage in Linux):
  AppImanges  in all linux distros and in ubuntu snap too

**Comment by jim-docker** [comment]
Does the user have have list-namespaces access (through RBAC)? You can also add the accessible namespaces on the cluster settings page, have you tried that?

**Comment by eins** [comment]
The user has  list-namespaces access through RBAC for all the namespaces because it is part of a clusterRole and ClusterRoleBinding.

The clusterRole, Role  and ClusterRoleBinding, RoleBinding configs are working with kubectl and Lens 3.6.9

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ns-list
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
 ---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devs-mere-prod
  namespace: mere-prod
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "endpoints", "events"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["secrets","persistentvolumeclaims", "daemonsets", "replicasets"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["apps", "extensions"]
  resources: ["deployments", "services", "statefulsets", "events"]
  verbs: ["get", "list", "watch", "update"]
```

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ns-list
subjects:
- kind: User
  name: jolla
  apiGroup: rbac.authorization.k8s.io
  ---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devs-rb-mere-prod
  namespace: mere-prod
subjects:
- kind: User
  name: jolla
  apiGroup: rbac.authorization.k8s.io
  ```

**Comment by eins** [comment]
@jim-docker I added the namespace manually:

File --> Cluster Settings --> Accessible Namespaces --> add manually the namespaces
and now in the specific namesapce I can see the pods in Lens 4.0.6 . 
it looks like now finally Lens is reading the RBAC for that particular cluster

How can I add this without doing it manually. because the user can list all namespaces but in Lens 4.0* in the specific namespace, no pods are showed.

**Comment by Nokel81** [comment]
@eins Thanks for the information. I have a few more questions about your set up.

1. How many `namespace`'s are in your cluster?
2. Are those the whole of the rbac permissions for the user?
3. When listing pods using `kubectl` are you doing `kubectl get pods -A`?

The reason why I am asking is that we currently (in version 4) check if the cluster context has `list` permissions on the first 10 namespaces that are returned by the equivalent to `kubectl get namespaces`. If the user doesn't have access to in any of those 10 namespaces Lens currently assumes that they don't have access at all.

I know that this is a sub par solution, but it was done as a compromise against flooding a kube server with a whole load of requests. Given how many users are running into this problem we may need to resolve this sooner though.

**Comment by eins** [comment]
@Nokel81 thanks for the reply

1. Outside these four namespaces:
   - kube-system
   - kube-public
   - kube-node-lease
   - default

   I have between two or six more namespaces, in the clusters  and all the developers are part  of system:basic-user group.

   Then I have a Role and RoleBindings for each namespace where the developers need to work on it.

   In order to list all namespaces we have a ClusterRole and a ClusterRolesbinding for only 'list namepsaces'

2. that is all the RBAC we use for the developers

3. the developers only use 'kubectl get pods' when they need to see pods of a particular namespace.
  
   I tested 'kubectl get pods -A'  command with a developer testing user an this is the output:

   ```
   kubectl get pods -A
   Error from server (Forbidden): pods is forbidden: User "jolla" cannot list resource "pods" in API group "" at the cluster scope
   ```

Let me know if you need more information.

**Comment by Nokel81** [comment]
When I set up a cluster with a user that has only get and list permissions for pods in the default name space (along with what you have above with the list namespace permissions), this is what I see. 
<img width="1145" alt="Screen Shot 2021-01-20 at 6 28 52 PM" src="https://user-images.githubusercontent.com/8225332/105253375-5add6400-5b4d-11eb-9c98-ec274c61d195.png">

I also see in my the dev console an error roughly like this:
<img width="458" alt="Screen Shot 2021-01-20 at 6 29 21 PM" src="https://user-images.githubusercontent.com/8225332/105253412-6b8dda00-5b4d-11eb-96d5-e03113a82804.png">

Is that what you are seeing. If so then great, I have reproduced your error and will start on the fix. If not I will still start on the fix since I have just found a bug too.

**Comment by eins** [comment]
In my case the namespace is called mere-prod and the dev user jolla has the same empty Overview pods(0) as you shared.
with Deployments(0) too.

the error that I saw was this:
```
kube-object.ts:59 Uncaught (in promise) TypeError: Cannot read property 'items' of undefined
    at Function.value (kube-object.ts:59)
    at r.value (kube-api.ts:274)
    at kube-api.ts:315
```

I searched for item.getName and I didn't find a match.

I added the namespace mere-prod  to Accessible Namespaces and reload it Lens, then I saw all the Pods and Deployments in the overview.

 After that I looked into the Console and I saw the same error, but t can see the pods, exec pods and see pod's logs :

```
kube-object.ts:59 Uncaught (in promise) TypeError: Cannot read property 'items' of undefined
    at Function.value (kube-object.ts:59)
    at e.value (kube-api.ts:274)
    at kube-api.ts:315
```

Maybe that error isn't related to the issue with exec/see pods.

**Comment by eins** [comment]
I just tested with Lens-4.0.6.AppImage and Lens-4.0.7.AppImage, I had the same issues.
I also tested with Lens-3.6.10.AppImage and it worked.
I noticed that the version 3 hasn't  the Accessible Namespaces option.

**Comment by Nokel81** [comment]
Okay thanks, I fixed the `kube-object.ts:59 Uncaught (in promise) TypeError: Cannot read property 'items' of undefined` error while I was investigating this issue. So I think I have indeed found your problem.

Thanks for the report.

**Comment by eins** [comment]
I just checked Lens-4.0.8.AppImage. I had the same issues, no pods or deployments apper in the dashboard for the selected namespace.

```
Uncaught (in promise) TypeError: Cannot read property 'items' of undefined
    at Function.value (kube-object.ts:59)
    at r.value (kube-api.ts:274)
    at kube-api.ts:315
```

**Comment by Nokel81** [comment]
Thanks for the update. I wasn't able to get my fix in for that patch release. Hopefully for the next one.

**Comment by schmel** [comment]
I merge branch "issue-1961" in last master, but trouble is not going away. Pods not list in Workloads. I have ~ 20 namespaces. 
If, i create NS alpha - it works, pods - listed, in NS - omega - pod not listed.

**Comment by Nokel81** [comment]
Do you have any logs from the dev-tools console?

**Comment by schmel** [comment]
> Do you have any logs from the dev-tools console?

In "omega" (pod not listed) namespaces - only info logs. But in "beta" (pod listed) - 403 for resources in default NS. 
rbac settings in both NS:

```
---
apiVersion: v1
kind: Namespace
metadata:
  name: beta
  labels:
    network/policy-group: firewall
    projects/owner: assa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beta
  namespace: beta
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: beta-admin
  namespace: beta
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin_beta
  namespace: beta
subjects:
- kind: ServiceAccount
  name: beta
  namespace: beta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: beta-admin
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: beta-admin
rules:
- apiGroups: ["*"]
  resources: ["namespaces", "customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["alertmanagers", "alertmanagerconfigs", "prometheuses", "prometheusrules", "servicemonitors", "podmonitors", "probes"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  
- apiGroups: ["kubeless.io"]
  resources: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: admin_beta
subjects:
- kind: ServiceAccount
  name: beta
  namespace: beta
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: beta-admin

```

**Comment by Nokel81** [comment]
I am having trouble understanding exactly what you are seeing with your shorthand. Would you mind explaining in more detail?

Screenshots and direct logs can help to.

I also noticed that you don't have `watch` permissions for `namespace`'s, that might help too.

**Comment by Nokel81** [comment]
However, I have tracked down a bug from the fact that if any watch fails then no pods are listed.

Thanks for the report, I will continue to investigate.

**Comment by Nokel81** [comment]
@schmel What you are seeing might already be fixed with #2193 in conjunction with #2003. However, if it is not then I believe that it would be fixed when #2209 gets fixed because that should account for non-watch permissions too. So I think I am going to leave this issue as being closed by #2003. And track the work around fixing your issue under #2209 .

**Comment by eins** [comment]
@Nokel81 I tested Lens-4.1.2 and  Lens-4.1.3, both version loaded Lens in the default namespace, but developers were able to see and choose the correct namespace and pods for a particular project.

Thanks

**Comment by schmel** [comment]
> I am having trouble understanding exactly what you are seeing with your shorthand. Would you mind explaining in more detail?
> 
> Screenshots and direct logs can help to.
> 
> I also noticed that you don't have `watch` permissions for `namespace`'s, that might help too.

Sorry for the long answer. Add "watch" to ClusterRole in verbs -  not solve the problem.

```
rules:
- apiGroups: [""]
  resources: ["namespaces", "customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
```
I record video. https://youtu.be/fmlgEvJKEys
