### ISSUE TITLE
Does lens support access to secure clusters that use SSO ?

### ISSUE THREAD

**Issue by amarouni** [lensapp/lens#200]
My K8s cluster is on AWS and I use OKTA to login to AWS, so doing any `kubectl ....` require an additional manual step where I get a one time AWS token via OKTA, I have to export this token `export ...` before my `kubectl...`

Is there any workaround for using Lens with this authentication mechanism ?

**Comment by Nuru** [comment]
@amarouni I am not part of the Lens project, but maybe I can help anyway. Please tell me more about your setup.

In my experience using Kubernetes on AWS with `kops` clusters, I did not need AWS permissions to use `kubectl`, I only needed them for `kops export kubecfg` to create my kubeconfig file. Pasting that file into Lens as a custom config works for me in that case.

In my experience using AWS EKS with SAML SSO like Okta (haven't actually used Okta, so it could be different, but seems unlikely) on a Mac, it was sufficient for me to log in to AWS in the Terminal so that temporary credentials were generated and saved in the standard `~/.aws/credentials` file. This is the same workflow I would use if I wanted to use `kubectl` on the command line in Terminal. 

See also the setup described in [this comment](https://github.com/lensapp/lens/issues/208#issuecomment-619278464) by someone who appears to be using Okta.

If that does not work, please provide more details, such as exactly how your cluster authentication is set up, how you run `kubectl` on the command line, your OS, etc.

**Comment by Nokel81** [comment]
You might be able to add those env vars to your kubeconfig. It might be able to work if you run lens from the command line too.

**Comment by jkroepke** [comment]
We are using Vanilla Kubernetes with Keycloak. In combination with https://github.com/int128/kubelogin Lens works out of the box.

**Comment by Timoses** [comment]
> We are using Vanilla Kubernetes with Keycloak. In combination with https://github.com/int128/kubelogin Lens works out of the box.

@jkroepke Does it?

I just installed Lens and tried using the `~/.kube/config` file which contains:
```
users:
- name: user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://kubernetes-sso.int/auth/realms/kubernetes
      - --oidc-client-id=kubernetes
      - --skip-open-browser
      - --grant-type=password
      command: kubectl
      env: null
      provideClusterInfo: false
```

In Lens I get:
```
Authentication proxy started

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:39:49 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:39:50 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:39:50 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:39:51 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"

Run 'kubectl --help' for usage.

2021/07/01 11:39:51 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:40:17 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:40:47 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:41:17 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.

2021/07/01 11:41:47 http: proxy error: getting credentials: exec: exit status 1

Error: unknown command "oidc-login" for "kubectl"

Run 'kubectl --help' for usage.

2021/07/01 11:42:17 http: proxy error: getting credentials: exec: exit status 1

502 - undefined

```

**Comment by jkroepke** [comment]
@Timoses 

> Error: unknown command "oidc-login" for "kubectl"

You have to install kubelogin on your local machine, too. It a kubectl plugin that is not builtin. If it's installed, verify that

```
% kubectl oidc-login version
kubelogin version v1.23.0 (go1.16.2 darwin_amd64)
```

Works.

**Comment by Timoses** [comment]
> @Timoses
> 
> > Error: unknown command "oidc-login" for "kubectl"
> 
> You have to install kubelogin on your local machine, too. It a kubectl plugin that is not builtin. If it's installed, verify that
> 
> ```
> % kubectl oidc-login version
> kubelogin version v1.23.0 (go1.16.2 darwin_amd64)
> ```
> 
> Works.

Sorry, should have mentioned that it is of course installed. `kubectl oidc-login` works.
It is installed via `krew` (under path `~/.krew/bin/...`) . Is that a problem?


As a side note: On Octant the same `~/.kube/config` file works without a problem.

**Comment by jkroepke** [comment]
Strange.

I'm using `Lens: 4.2.5` on MacOS. Did you initially paste the content of a kubeconfig or did you reference an existing one?

**Comment by Timoses** [comment]
5.0.0 here: 
![grafik](https://user-images.githubusercontent.com/6923843/124237221-9413fa00-db17-11eb-96b6-c81bc06395e6.png)

I created a symbolic link from `/usr/local/bin/kubectl-oidc_login` to `~/.krew/bin/kubectl-oidc_login`. Now Lens recognizes the oidc-login command.

However, I get 
```
error: get-token: authentication error: ropc error: could not read a username: read error: EOF
2021/07/02 09:47:56 http: proxy error: getting credentials: exec: exit status 1
```

I suppose this is because username and password are expected from stdin. Can't Lens offer this?

It does work however, if I once login through console with e.g. `kubectl get pods` (it asks for username/password). Afterwards the token is active and Lens can utilize this to connect to the clusters.

**Comment by jkroepke** [comment]
> Can't Lens offer this?
From what I know, Lens cant offer this. I guess a different issue for that case would be great.

I do a login through the browser (since I have to enter a OTP token too), that works for me.

```
users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: kubectl
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://login.dev/auth/realms/kubernetes
      - --oidc-client-id=kubernetes
      - --oidc-client-secret=UUID
```

**Comment by Nuru** [comment]
See alternative solution [here](https://github.com/lensapp/lens/issues/208#issuecomment-908858344)

**Comment by pbagriy** [comment]
> I created a symbolic link from `/usr/local/bin/kubectl-oidc_login` to `~/.krew/bin/kubectl-oidc_login`. Now Lens recognizes the oidc-login command.

Not an obvious solution, but it worked for me. 

Seems like plugin installation via Krew is the initial source of problem here. Plugins are installed in ~/.krew/bin/ directory and this directory is added to PATH. But Lens for some reason doesn't properly read user PATH variable in this case. It works as expected when using connection with other form of authorization (or no auth, e.g. when using minikube).

**Comment by Nuru** [comment]
Applications, when launched via the Finder, do not pick up any changes (such as changes to `PATH`) made in shell startup scripts like `.bashrc` or `.zshrc`. See [here](https://github.com/hschmidt/EnvPane#why-cant-i-set-path-with-envpane) for one explanation of why.

**Comment by jkroepke** [comment]
Maybe add the path to /etc/path.d/ can resolve the issue on MacOS.

See: https://golangbyexample.com/understand-etc-paths-pathsd-mac/

**Comment by LinTechSo** [comment]
Hi, any updates? I am using kubectl and lens and facing the same issue

**Comment by Enderric** [comment]
I have the same error as @Timoses.  I tried installing kubelogin as a super user and as a regular user. I tried to run lens from the command line as advised above. There is a corresponding symbolic link to kubectl-oidc_login. This command is working

```
[leyn@onekysonotob /]$ kubectl oidc-login version
kubelogin version v1.25.2 (go1.18.4 linux_amd64)
```

For comparison, k9s works, lens does not work. 
kubectl get pods and k9s works for both users

**Comment by veyselsahin** [comment]
a solution for someone who is still struggling

```
    - name: oidc
      user:
        exec:
            apiVersion: client.authentication.k8s.io/v1beta1
            args:
                - oidc-login
                - get-token
                - --oidc-issuer-url=https://your-oidc-url
                - --oidc-client-id=kubernetes
                - --grant-type=password
                - --username=YOUR_USERNAME
                - --password=YOUR_PASS
            command: /usr/local/bin/kubectl
            env: null
            interactiveMode: IfAvailable
            provideClusterInfo: false
```
