### ISSUE TITLE
User Exec command "/usr/local/bin/aws" not found on host.

### ISSUE THREAD

**Issue by zaf187** [lensapp/lens#2079]
**Describe the bug**
I am using Lens on Windows, all my interactions with a kubenetes cluster i perform via kubectl installed on Windows Subsystem for Linux (WSL). I have also installed aws cli on WSL. My kubeconfig file is in WSL, i am able to reference the file in Lens using the path `\\wsl$\Ubuntu-18.04\home\user\.kube`
When i try to use one of my aws eks clusters, i get the above error message. I am assuming it's because it's trying to use aws cli from windows.

Is there any way to get it working without having to install aws cli in two places (WSL and Windows)?

**To Reproduce**
Use a kubeconfig file that contains a reference an aws eks cluster, see below.

The problem arises where the `command: /usr/local/bin/aws` has been defined, i added the fully qualified path but that hasn't helped.

**Expected behavior**
It should be able to load the cluster

**Environment (please complete the following information):**
- Lens Version: 4.0.8
- OS: Windows 10 Pro
- Installation method (e.g. snap or AppImage in Linux): From websiteusing installer
- WsL: Ubuntu 18.04

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
User Exec command "/usr/local/bin/aws" not found on host.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://asdfasdfasdfasdfasd.gr7.us-east-2.eks.amazonaws.com
  name: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
contexts:
- context:
    cluster: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
    namespace: xxxxxxx-rc5
    user: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
  name: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
current-context: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-2:999999999999:cluster/xxxxxxx-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-2
      - eks
      - get-token
      - --cluster-name
      - xxxxxxx-1
      - --role
      - arn:aws:iam::999999999999:role/xxxxxxx-1-cluster-admin
      command: /usr/local/bin/aws
      env:
      - name: AWS_PROFILE
        value: xxxxxxx-eks
```

**Comment by zaf187** [comment]
I got it working after installing aws on Windows, i had to configure it all up again.

**Comment by jim-docker** [comment]
related to #2087

**Comment by levissssss** [comment]
Got a workaround that aliases the aws command from WSL:

1. Create a file in windows `aws.bat`:
```
@echo off
echo.
wsl aws %*
```
2. Add this to your `PATH` in windows. 
3. Restart (might not be needed but didn't work for me until I did)

**Comment by nevalla** [comment]
Another workaround is to copy paste the kubeconfg to Lens and set `wsl` as command and move `aws` to args:

```
- user:
    ...
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: wsl
      args:
      - aws      
      - eks
      - get-token
      ...
```
Also noticed that in order to get env variables present in Kubeconfig passed properly to `wsl` command you need to add those into `WSLENV` environment variable, for example:
```
AWS_PROFILE/u
```

or move those to args in Kubeconfig
