### ISSUE TITLE
panic trying to connect with 3.1.0

### ISSUE THREAD

**Issue by e271828-** [lensapp/lens#210]
**Describe the bug**

Panic on connect.

I suspect this may be due to not having the CA for that cluster set up, but there's nothing in the panic to give it away.

**To Reproduce**

Select cluster from list. Get panic.

**Environment (please complete the following information):**
OSX, dmg
 
**Logs:**
```
Connecting ...
Authentication proxy started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20bf29d]

goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/proxy.(*Server).ServeOnListener(...)
	/workspace/anago-v1.17.3-beta.0.40+c94b9acd4b784f/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/proxy/proxy_server.go:240
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/proxy.RunProxy(0x29a12e0, 0xc0003ee780, 0x2937aa0, 0xc0000b8008, 0xc000541b80, 0x0, 0x0)
	/workspace/anago-v1.17.3-beta.0.40+c94b9acd4b784f/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/proxy/proxy.go:163 +0x75d
k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/proxy.NewCmdProxy.func1(0xc000541b80, 0xc0003b0c60, 0x0, 0x6)
	/workspace/anago-v1.17.3-beta.0.40+c94b9acd4b784f/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/kubectl/pkg/cmd/proxy/proxy.go:82 +0x4f
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc000541b80, 0xc0003b0c00, 0x6, 0x6, 0xc000541b80, 0xc0003b0c00)
	/workspace/anago-v1.17.3-beta.0.40+c94b9acd4b784f/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830 +0x2aa
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00021db80, 0xc0000ba120, 0xc0000c0000, 0x8)
	/workspace/anago-v1.17.3-beta.0.40+c94b9acd4b784f/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914 +0x2fb
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/workspace/anago-v1.17.3-beta.0.40+c94b9acd4b784f/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
main.main()
	_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubectl/kubectl.go:49 +0x1f9
proxy exited with code 2
```

**Comment by andyast** [comment]
Having the same issue.  My organization has a MITM proxy (don't ask), but when I include ` insecure-skip-tls-verify: true` in the kubeconfig I get the same error.

**Comment by andyast** [comment]
my kubeconfig
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: https://<aws-account-id>.gr7.us-east-1.eks.amazonaws.com
    insecure-skip-tls-verify: true
  name: arn:aws:eks:us-east-1:<aws-account-id>:cluster/<cluster-name>
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:<aws-account-id>:cluster/<cluster-name>
    user: arn:aws:eks:us-east-1:<aws-account-id>:cluster/<cluster-name>
  name: arn:aws:eks:us-east-1:<aws-account-id>:cluster/<cluster-name>
current-context: arn:aws:eks:us-east-1:<aws-account-id>:cluster<cluster-name>
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:<aws-account-id>:cluster<cluster-name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - <cluster-name>
      - --role
      - arn:aws:iam::<aws-account-id>:role/<cluster-name>-adminRole
      command: aws
```

**Comment by andyast** [comment]
Update I tried using a different `certificate-authority-data` using the cert of the proxy and got the same errors.

**Comment by instinct-vfx** [comment]
Any updates on this? It seems to affect me with 3.5.3 too.

**Comment by andyast** [comment]
Just tested and it's still happening for me with 3.5.3 as well.

**Comment by nevalla** [comment]
Okay thanks for the info...we'll try to reproduce this.

**Comment by nevalla** [comment]
I think the issue here is that both `certificate-authority-data` and `insecure-skip-tls-verify` are present in Kubeconfig. So please try to remove `certificate-authority-data` and test again.

**Comment by andyast** [comment]
When I do that I get the following error

`SSL validation failed for https://sts.us-east-1.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)
2020/09/02 09:07:23 http: proxy error: getting credentials: exec: exit status 255`

**Comment by nevalla** [comment]
> When I do that I get the following error
> 
> `SSL validation failed for https://sts.us-east-1.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076) 2020/09/02 09:07:23 http: proxy error: getting credentials: exec: exit status 255`

And that with `insecure-skip-tls-verify: true` option?

**Comment by andyast** [comment]
Here is the kube config I'm using

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://<eks instance id>.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:<aws account id>:cluster/<aws eks cluster name>
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:<aws account id>:cluster/<aws eks cluster name>
    user: arn:aws:eks:us-east-1:<aws account id>:cluster/<aws eks cluster name>
  name: arn:aws:eks:us-east-1:<aws account id>:cluster/<aws eks cluster name>
current-context: arn:aws:eks:us-east-1:<aws account id>:cluster/<aws eks cluster name>
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:<aws account id>:cluster/<aws eks cluster name>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - <aws eks cluster name>
      - --role
      - arn:aws:iam::<aws account id>:role/<aws eks cluster name>-adminRole
      command: aws
```
