### ISSUE TITLE
[4.1.0-rc.1] "Connecting..." takes forever

### ISSUE THREAD

**Issue by juergenzimmermann** [lensapp/lens#2152]
**Describe the bug**
After a fresh install of _4.1.0-rc.1_ Lens cannot connect to my local Kubernetes via Docker Desktop on Windows 10 Enterprise. I see a message `Connecting... Authentication proxy started` and then Lens is hanging. After reinstalling 4.1.0-beta.2 Lens is working as before.

**To Reproduce**
1. Use Docker Desktop with Kubernetes
2. Click "+" in Lens to add the according cluster

**Expected behavior**
Connection to Kubernetes via Docker Desktop works as before.

**Screenshots**
![lens authentication-proxy](https://user-images.githubusercontent.com/734334/107881844-66227600-6ee6-11eb-9db6-e01488964eb9.png)

**Environment (please complete the following information):**
- Lens Version: 4.1.0-rc.1
- OS: Windows 10 2004 Enterprise
- Installation method (e.g. snap or AppImage in Linux): .exe

**Logs:**
No console message.

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0...
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: LS0...
    client-key-data: LS0...
```
