### ISSUE TITLE
"Cannot read property 'getId' of undefined" when clicking on a pod

### ISSUE THREAD

**Issue by ffissore** [lensapp/lens#2227]
**Describe the bug**
When clicking on a pod of our production cluster, the left pane starts to show up and it's immediately replaced by the error screen showing the error above. It does not happen with pods of our dev cluster

**To Reproduce**
1. Go to Pods
2. Click on a pod

**Expected behavior**
I expected to see the pod details

**Environment (please complete the following information):**
- Lens Version: 4.1.3
- OS: ubuntu
- Installation method (e.g. snap or AppImage in Linux): DEB

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
This what I get from the terminal
```
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
```

This is from the error page
```
Component stack:


    at QI (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:8013519)
    at span
    at div
    at jd (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:7756151)
    at div
    at kI (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:8016142)
    at Details
    at div
    at div
    at div
    at Bp (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:7728188)
    at Qd (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:7753647)
    at sy (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:7874585)
    at pa (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:7560311)
    at t (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:191498)
    at eT (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:8261853)
```
```
Error stack:

 
TypeError: Cannot read property 'getId' of undefined
    at http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:8013840
    at http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:42956
    at Array.map (<anonymous>)
    at Proxy.forEach.Array.<computed>.pr.<computed> (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:42931)
    at QI.render (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:8013805)
    at Ce (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:13973)
    at http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:7444538
    at ce (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:12079)
    at e.track (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:23443)
    at QI.s [as render] (http://249ff66b-b091-40f1-804b-a670a6c70fd8.localhost:40019/build/Lens.js:2:7444486)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA
    server: https://IP
  name: dev
- cluster:
    certificate-authority-data: DATA
    server: https://IP
  name: prod
contexts:
- context:
    cluster: dev
    user: dev
  name: dev
- context:
    cluster: prod
    user: prod
  name: prod
current-context: prod
kind: Config
preferences: {}
users:
- name: dev
  user:
    auth-provider:
      config:
        access-token: TOKEN
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "2021-02-25T09:12:24Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: prod
  user:
    auth-provider:
      config:
        access-token: TOKEN
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "2021-02-25T09:12:24Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

**Additional context**
