### ISSUE TITLE
4.1.3: Can't access cluster anymore (Azure)

### ISSUE THREAD

**Issue by spyro2000** [lensapp/lens#2270]
**Describe the bug**

- After updating to 4.1.3, I can't list any resources of cluster like pods etc. 
- Works per CLI (kubectl).
- Please note that I have to specify a namespace first because I don't have access to namespace "default".

**To Reproduce**
1. Refresh authentication via az login
2. Connect to cluster in K8S
3. Click on icon

**Expected behavior**
Pods, Services etc. are shown

**Screenshots**

![image](https://user-images.githubusercontent.com/8479925/109632524-66a64800-7b47-11eb-8b66-75e10c8871e1.png)

(the other entries of the list like pods etc. are not loading)

![image](https://user-images.githubusercontent.com/8479925/109633781-cea95e00-7b48-11eb-8e60-485518acd264.png)

![image](https://user-images.githubusercontent.com/8479925/109633561-84c07800-7b48-11eb-8da5-9c5ceeb10963.png)

(kubectl works just fine)

**Environment (please complete the following information):**
- Lens Version: 4.1.3
- OS: Win7X64 Prof
- Installation method (e.g. snap or AppImage in Linux): Lens Installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Did start per command line (powershell + cmd), but no logs are shown.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <removed>
    server: https://<removed>.hcp.westeurope.azmk8s.io:443
  name: maks-aks-westeurope
contexts:
- context:
    cluster: maks-aks-westeurope
    user: clusterUser_maks-aks-westeurope-rg_maks-aks-westeurope
  name: maks-aks-westeurope
current-context: maks-aks-westeurope
kind: Config
preferences: {}
users:
- name: clusterUser_maks-aks-westeurope-rg_maks-aks-westeurope
  user:
    auth-provider:
      config:
        access-token: <removed>
        apiserver-id: <removed>
        client-id: <removed>
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "3599"
        expires-on: "1614680736"
        refresh-token: <removed>
        tenant-id: <removed>
      name: azure
```

**Additional context**

When I open the DevTools, display the console and reload the App there are some errors shown, regarding an authorization problem (but seems to be about prometheus which we don't use):

![image](https://user-images.githubusercontent.com/8479925/109634025-0e704580-7b49-11eb-9ee3-0cc4e59f1192.png)
