### ISSUE TITLE
Lens doesn't use MacOs DNS resolver

### ISSUE THREAD

**Issue by eugene-dm** [lensapp/lens#230]
**Describe the bug**
Lens can't resolve DNS records when MacOs can.
We are connecting to development/production environments in AWS through VPN.
We are using private Route53 zones for internal DNS, so they are not visible worldwide.
Looks like Lens tries to resolve DNS using nameserver from /etc/resolv.conf which is usually router which not connected to VPN. 
At the same time, MacOs DNS resolver can resolve records through VPN.

**To Reproduce**
1. Connect to VPN with private DNS on Route53
2. Add a cluster by private DNS name

**Expected behavior**
The cluster should be connected successfully

**Screenshots**
<img width="1071" alt="Screen Shot 2020-04-08 at 12 16 50" src="https://user-images.githubusercontent.com/1763816/78767203-f3c23a80-7992-11ea-8fce-695d32c7fada.png">
<img width="756" alt="78767216-f7ee5800-7992-11ea-8781-1bb4076e81ca" src="https://user-images.githubusercontent.com/1763816/79764170-aef0b900-832d-11ea-9780-517883f518f2.png">

**Environment (please complete the following information):**
- Lens Version: 3.1.0
- OS: MacOs Catalina 10.15.3 (19D76)
- Installation method: dmg
 
**Logs:**
```
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
clusters:
- name: "dc1"
  cluster:
    server: "https://rancher.preprod.voicebase.com/k8s/clusters/c-56vd7"
    certificate-authority-data: ""
users:
- name: "dc1"
  user:
    token: ""

contexts:
- name: "dc1"
  context:
    user: "dc1"
    cluster: "dc1"
current-context: "dc1"
```

**Additional context**
