### ISSUE TITLE
Lens not responding after close terminal

### ISSUE THREAD

**Issue by rdeavila** [lensapp/lens#234]
**Describe the bug**
After use the terminal to connect to a pod, I click on `x` icon to close it. When I do it, 

**To Reproduce**
1. Go to 'Workloads > Deployments'
1. Click on an deployment
1. When the right panel open, click on a pod
1. Click on 'pod shell' button
1. Wait the connection
1. Do something (useful or not)
1. Type 'exit' to exit the pod shell
1. Click the Close button, to close the terminal tab
1. Lens freezes

**Expected behavior**
Just close the terminal tab

**Environment (please complete the following information):**
- Lens Version: 3.2.0
- OS: Win10
- Installation method (e.g. snap or AppImage in Linux): Installer
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://REDACTED
  name: gke_mailtop-com-br_us-east1-c_mailtop-k8s
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://REDACTED
  name: gke_mailtop-com-br_us-east1_mailtop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
- context:
    cluster: gke_mailtop-com-br_us-east1-c_mailtop-k8s
    user: gke_mailtop-com-br_us-east1-c_mailtop-k8s
  name: gke_mailtop-com-br_us-east1-c_mailtop-k8s
- context:
    cluster: gke_mailtop-com-br_us-east1_mailtop
    user: gke_mailtop-com-br_us-east1_mailtop
  name: gke_mailtop-com-br_us-east1_mailtop
current-context: gke_mailtop-com-br_us-east1-c_mailtop-k8s
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: gke_mailtop-com-br_us-east1-c_mailtop-k8s
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\rodrigo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-04-04T22:56:13Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_mailtop-com-br_us-east1_mailtop
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\rodrigo\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2020-01-29T17:49:38Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
