### ISSUE TITLE
Stack trace

### ISSUE THREAD

**Issue by kakaa** [lensapp/lens#2440]
Getting stack trace after a short while when opening the connection to cluster.

Open Lens and choose some Pod.
Wait 2-5 seconds in Cluster view and stack trace is shown.

**Expected behavior**
It used to open Pod view but this is not opened. It is a new K8s cluster. I have a cluster manually installed from scratch. Might be missing something.

**Screenshots**
```
App crash at http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/services?namespaces=
Error stack:

 
TypeError: Cannot read property 'kind' of undefined
    at r.value (http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:3775674)
    at http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:8681240
    at Array.map (<anonymous>)
    at http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:8681208
    at Array.map (<anonymous>)
    at r.value (http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:8681152)
    at r.value (http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:8686500)
    at ve (http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:18448)
    at http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:70625
    at ce (http://f38db4e1-43a3-406a-a8a4-975dbf31b0b1.localhost:51724/build/Lens.js:2:16554)

Component stack:


    in r
    in aside
    in div
    in r
    in r
    in t
    in Unknown
    in r
```
**Environment (please complete the following information):**
- Lens Version:
- OS: Windows 10
- 
![image](https://user-images.githubusercontent.com/6927041/113416448-0a467a80-93ca-11eb-958e-96de2b936ef0.png)

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://100.100.100.100:443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```
