### ISSUE TITLE
Nothing is showing on dashboards, no errors

### ISSUE THREAD

**Issue by ghost** [lensapp/lens#247]
**Describe the bug**
I have a properly configured `gcloud` and `kubectl` CLI tools.
They all work just fine.

But when I have imported all the contexts from kubeconfig into Lens, there is no information at all.

**To Reproduce**
1. Add a cluster from kubeconfig
2. Connect to it
3. No information, empty dashboards

**Expected behavior**
Some error that explains why this happened or better - data from kubernetes cluster.

**Screenshots**
<img width="2032" alt="Screenshot 2020-04-13 at 16 18 26" src="https://user-images.githubusercontent.com/59873217/79123342-a256e880-7da2-11ea-9fde-99be16318526.png">

**Environment (please complete the following information):**
- Lens Version: 3.2.0
- OS: OSX
- Installation method: AppImage

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Not sure how to get logs from command line if I'm running an .app
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: DATA+OMITTED
  name: "DATA+OMITTED"
contexts:
- context:
    cluster: "DATA+OMITTED"
    user: DATA+OMITTED
  name: "DATA+OMITTED"
current-context: "DATA+OMITTED"
kind: Config
preferences: {}
users:
- name: DATA+OMITTED
  user:
    auth-provider:
      config:
        client-id: DATA+OMITTED
        client-secret: DATA+OMITTED
        id-token: DATA+OMITTED
        idp-issuer-url: DATA+OMITTED
        refresh-token: DATA+OMITTED
      name: oidc
```
