### ISSUE TITLE
Cannot parse kubeconfig while Adding a Cluster (after deleted default workspace)

### ISSUE THREAD

**Issue by aleksmark** [lensapp/lens#249]
**Describe the bug**

I installed the lens app on my Mac and added four clusters from my config and everything was working ok. Then I created two workspaces and moved those clusters into the newly created workspaces. Dashboards for all clusters were working still fine. 

Then I deleted the default workspace. After I deleted the default workspace, I got an empty black screen (I am using the black theme), and I did not have the option to choose my custom workspaces. I assume I should not have deleted the default workspace (although there was an option to delete it). 

After that, I uninstalled the lense app and install it again. All my previously added clusters are gone and when I try to add again, same clusters, I get an error **cannot parse kubeconfig**. I don't see any workspaces.

**To Reproduce**
1. Add cluster from kubeconfig
2. Create custom workspace
3. Move added cluster to a custom workspace
4. Delete default workspace
5. See black screen without any options to add clusters or to switch to a custom workspace
6. Reinstall Lens
7. Add cluster from kubeconfig
8. See error **cannot parse kubeconfig**

**Expected behavior**
I am able to add new clusters and to see my custom workspaces

**Screenshots**
![image](https://user-images.githubusercontent.com/14918537/79251584-3c3c9500-7e78-11ea-9d36-b3ebd89b7d08.png)

**Environment (please complete the following information):**
- Lens Version: 3.2.0
- OS: [e.g. OSX] : OSX 10.15.4
- Installation method (e.g. snap or AppImage in Linux):  Lens-3.2.0.dmg
 

**Logs:**
How can I run Lens from command line? 

**Kubeconfig:**
I simplified the config and leave only one cluster. The same error occurs with this config

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: xxxx
  name: Cluster-Name
contexts:
- context:
    cluster: Cluster-Name
    user: clusterUser_xxx
  name: Context-Name
current-context: Context-Name
kind: Config
preferences: {}
users:
- name: clusterUser_xxx
  user:
    auth-provider:
      config:
        access-token: xxxx
        apiserver-id: xxxx
        client-id: xxxx
        environment: AzurePublicCloud
        expires-in: "3599"
        expires-on: "1586886162"
        refresh-token: xxx
        tenant-id: xxxx
      name: azure
```

**Additional context**

I suspect the issue is related to the deletion of the default workspace. And after reinstalling the application, some of the configuration is not cleaned up properly from the previous installation and now is in an invalid state. How can I make sure all config is cleaned when I uninstall the application?

Possible duplicate of https://github.com/lensapp/lens/issues/161
