### ISSUE TITLE
Can't connect to cluster in Arch Linux x86_64

### ISSUE THREAD

**Issue by martin-dos-santos** [lensapp/lens#2539]
**Describe the bug**
I've a cluster config in kubectl and I'm able to list pods and all kind of things but when I try to add the cluster to lens I got the next error:

> Authentication proxy started
> 
> 2021/04/15 18:48:40 http: proxy error: dial tcp: lookup {***censored***}.{***censored***}.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:57902->[::1]:53: read: connection refused
> 2021/04/15 18:48:40 http: proxy error: dial tcp: lookup {***censored***}.{***censored***}.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:57902->[::1]:53: read: connection refused
> 2021/04/15 18:48:40 http: proxy error: dial tcp: lookup {***censored***}.{***censored***}.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:57902->[::1]:53: read: connection refused
> 
> 2021/04/15 18:48:40 http: proxy error: dial tcp: lookup {***censored***}.{***censored***}.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:57072->[::1]:53: read: connection refused
> 
> 2021/04/15 18:48:40 http: proxy error: dial tcp: lookup {***censored***}.{***censored***}.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:44184->[::1]:53: read: connection refused
> 
> 502 - undefined

**To Reproduce**
1. Go to "File" > "Add Cluster"
2. Click on "Add Cluster" button as kubeconfig file is auto detected.
3. See error

**Expected behavior**
I should be able to connect to the cluster

**Environment (please complete the following information):**
- Lens Version: 4.2.1
- OS: Arch Linux x86_64
- Installation method (e.g. snap or AppImage in Linux): AppImge

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
[32minfo[39m: 📟 Setting Lens as protocol client for lens://
[32minfo[39m: 📟 failed ❗
[32minfo[39m: 🚀 Starting Lens from "/home/martin/.config/Lens"
[32minfo[39m: 🐚 Syncing shell environment
[32minfo[39m: 💾 Loading stores
[32minfo[39m: [STORE]: LOADED from /home/martin/.config/Lens/lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from /home/martin/.config/Lens/lens-workspace-store.json
[32minfo[39m: [STORE]: LOADED from /home/martin/.config/Lens/lens-extensions.json
[32minfo[39m: [STORE]: LOADED from /home/martin/.config/Lens/lens-filesystem-provisioner-store.json
[32minfo[39m: [STORE]: LOADED from /home/martin/.config/Lens/lens-user-store.json
[32minfo[39m: 🔑 Getting free port for LensProxy server
[32minfo[39m: 🔌 Starting LensProxy
[32minfo[39m: [LENS-PROXY]: Proxy server has started at http://localhost:33007
[32minfo[39m: 🔎 Testing LensProxy connection ...
[32minfo[39m: ⚡ LensProxy connection OK
[32minfo[39m: 🖥️  Starting WindowManager
[32minfo[39m: 🧩 Initializing extensions
[32minfo[39m: [EXTENSION-DISCOVERY] loading extensions from /home/martin/.config/Lens
[32minfo[39m: [EXTENSION-INSTALLER] installing dependencies at /home/martin/.config/Lens
[32minfo[39m: [WINDOW-MANAGER]: Loading Main window from url: http://localhost:33007 ...
[32minfo[39m: [EXTENSION-INSTALLER] dependencies installed at /home/martin/.config/Lens
[32minfo[39m: [EXTENSION-DISCOVERY] watching extension add/remove in /home/martin/.k8slens/extensions
[32minfo[39m: [EXTENSION]: enabled lens-license@0.1.0
[32minfo[39m: [STORE]: LOADED from /home/martin/.config/Lens/extension-store/lens-survey/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
telemetry main extension activated
[32minfo[39m: [STORE]: LOADED from /home/martin/.config/Lens/extension-store/lens-telemetry/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-telemetry@0.1.0
[32minfo[39m: 📡 Checking for app updates
[32minfo[39m: Checking for update
[32minfo[39m: [WINDOW-MANAGER]: Main window loaded
[32minfo[39m: Update for version 4.2.1 is not available (latest version: 4.2.1, downgrade is disallowed).
[32minfo[39m: [MENU]: navigating to /add-cluster
[32minfo[39m: [STORE]: SAVING /home/martin/.config/Lens/lens-cluster-store.json
[32minfo[39m: [CLUSTER-MANAGER]: init cluster {"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":false,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: "arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev" init success {"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","context":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","apiUrl":"https://{***censored***}.gr7.us-east-1.eks.amazonaws.com"}
[32minfo[39m: [STORE]: SAVING /home/martin/.config/Lens/lens-workspace-store.json
[32minfo[39m: [CLUSTER]: activate {"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: bind events {"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [CLUSTER]: reconnect {"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}
[32minfo[39m: [KUBE-AUTH]: out-channel "kube-auth:121694bb-1d54-4c7d-8764-6295ddc41b92" {"data":"Authentication proxy started\n","meta":{"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":true}}
[32minfo[39m: [KUBE-AUTH]: out-channel "kube-auth:121694bb-1d54-4c7d-8764-6295ddc41b92" {"data":"2021/04/15 18:55:42 http: proxy error: dial tcp: lookup {***censored***}.gr7.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:52093->[::1]:53: read: connection refused\n2021/04/15 18:55:42 http: proxy error: dial tcp: lookup {***censored***}.gr7.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:52093->[::1]:53: read: connection refused\n2021/04/15 18:55:42 http: proxy error: dial tcp: lookup {***censored***}.gr7.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:52093->[::1]:53: read: connection refused\n","error":true,"meta":{"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}}
[31merror[39m: Failed to connect cluster "arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev": StatusCodeError: 502 - undefined
[32minfo[39m: [KUBE-AUTH]: out-channel "kube-auth:121694bb-1d54-4c7d-8764-6295ddc41b92" {"data":"2021/04/15 18:55:42 http: proxy error: dial tcp: lookup {***censored***}.gr7.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:36258->[::1]:53: read: connection refused\n","error":true,"meta":{"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}}
[32minfo[39m: [KUBE-AUTH]: out-channel "kube-auth:121694bb-1d54-4c7d-8764-6295ddc41b92" {"data":"2021/04/15 18:55:42 http: proxy error: dial tcp: lookup {***censored***}.gr7.us-east-1.eks.amazonaws.com on [::1]:53: read udp [::1]:60155->[::1]:53: read: connection refused\n","error":true,"meta":{"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}}
[32minfo[39m: [CLUSTER]: disconnect {"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}
[32minfo[39m: [CLUSTER]: unbind events {"id":"121694bb-1d54-4c7d-8764-6295ddc41b92","name":"arn:aws:eks:us-east-1:{***censored***}:cluster/k8s-randomcompany-dev","initialized":true,"ready":false,"online":false,"accessible":false,"disconnected":false}
[32minfo[39m: SERVICE:QUIT
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: {****censored*****}
    server: https://{****censored*****}.{****censored*****}.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:{****censored*****}:cluster/k8s-randomcompany-dev
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:{****censored*****}::cluster/k8s-randomcompany-dev
    user: arn:aws:eks:us-east-1:{****censored*****}::cluster/k8s-randomcompany-dev
  name: arn:aws:eks:us-east-1:{****censored*****}::cluster/k8s-randomcompany-dev
current-context: arn:aws:eks:us-east-1:{****censored*****}::cluster/k8s-randomcompany-dev
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:{****censored*****}:cluster/k8s-randomcompany-dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - k8s-randomcompany-dev
      command: aws
      env:
      - name: AWS_PROFILE
        value: randomcompany-dev
```
