### ISSUE TITLE
Lens allowing deployment scale

### ISSUE THREAD

**Issue by Gidiklf** [lensapp/lens#2553]
**Describe the bug**
Hi Guys,

one of my R&D team member using the same kubeconfig in lens and kubectl
and in lens he is allowed to scale deployment while in kubectl he doesn't allowed as there is no role for "PATCH" deployment scale,
RBAC role does not exists allowed in lens 

1. Go to lens GUI and add deployment scale with 1 more replicas
2. check kubectl get pods 
3. Seeing replica grow by one
4. try to run the command with kubectl instead of lens : "kubectl scale --replicas=1 deployment <name>" 
5. Getting: "Error from server (Forbidden): deployments.app "<deployment_name>" is forbidden for user:<user_name> cannot patch resource.." 

**Expected behavior**
Lens wont allowed to scale the deployment as there is no RBAC role that allowed it for the specified user 

**Screenshots**
![kubectl-error](https://user-images.githubusercontent.com/36405154/115203093-c0ff6600-a0ff-11eb-82ba-885984c44663.png)

**Environment (please complete the following information):**
- Lens Version: 4.2.1
- OS: [e.g. OSX]
- Installation method (e.g. snap or AppImage in Linux):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Your logs go here...
```

**Kubeconfig:**

```
apiVersion: v1
kind: Config
clusters:
- name: "qa"
  cluster:
    server: "https://<server_url>"
    certificate-authority-data: "<CA_CERT>"

users:
- name: "qa"
  user:
    token: "<token>"

contexts:
- name: "qa"
  context:
    user: "qa"
    cluster: "qa"

current-context: "qa"

```

**Additional context**
