### ISSUE TITLE
Session expires after first 30 minutes or so after opening the app

### ISSUE THREAD

**Issue by raswinraaj** [lensapp/lens#2574]
**Describe the bug**
Session expires after first 30 minutes or so after opening the app

**To Reproduce**
1. Open Lens App
2. Connect to a cluster
3. Check logs
4. Keep the app open for 30 minutes or so, the session seems to expire.

**Expected behavior**
Opening any pod log should happen successfully. But on clicking of the pod log button, nothing opens

**Screenshots**

**Environment (please complete the following information):**
- Lens Version:4.2.0
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): exe

**Logs:**
No logs available

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data:  **censored**
    server: https://**censored**-d8f47b9d.hcp.eastus.azmk8s.io:443
  name: aks-**censored**
contexts:
- context:
    cluster: aks-**censored**
    user: clusterUser_**censored**_aks-**censored**
  name: aks-**censored**
current-context: aks-**censored**
kind: Config
preferences: {}
users:
- name: clusterUser_**censored**_aks-**censored**
  user:
    client-certificate-data: **censored**
    client-key-data: **censored**
    token: **censored**

```

**Additional context**
