### ISSUE TITLE
Invalid credentials when Authentication proxy started on Add Clusters from Kubeconfig

### ISSUE THREAD

**Issue by raksit31667** [lensapp/lens#2592]
**Describe the bug**
As a user, when I add a new cluster from Kubeconfig, it will be displayed as:

![Invalid credentials](https://imgshare.io/images/2021/04/22/Screen-Shot-2564-04-22-at-15.18.36.png)

**To Reproduce**
1. Add a new cluster using "Select kubeconfig file"
2. Select any contexts
3. Add HTTP proxy server URL
4. Click "Add cluster" and see error

**Expected behavior**
It should be able to connect to given Kube context.

**Environment (please complete the following information):**
- Lens Version: v4.2.2
- OS: [e.g. OSX] Mojave
- Installation method (e.g. snap or AppImage in Linux): dmg file

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: my-server-name
  name: my-cluster/name
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:57182
  name: kind-kind
contexts:
- context:
    cluster: my-cluster/name
    namespace: my-namespace
    user: my-cluster/name
  name: my-cluster/name
- context:
    cluster: kind-kind
    namespace: local
    user: kind-kind
  name: kind-kind
current-context: my-kube/context
kind: Config
preferences: {}
users:
- name: my-cluster/name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - my-region
      - eks
      - get-token
      - --cluster-name
      - my-cluster-name
      command: aws
      env:
      - name: AWS_PROFILE
        value: ...
- name: kind-kind
  user:
    client-certificate-data: ...
    client-key-data: ...
```

**Additional context**
- Same proxy configuration works with Lens on Windows.
- Be able to access Kubernetes context via `kubectl`.

**Comment by Nokel81** [comment]
So we display the "Invalid Credentials" if we fail to connect to the cluster. Would you be able to provide some logs?

**Comment by raksit31667** [comment]
> So we display the "Invalid Credentials" if we fail to connect to the cluster. Would you be able to provide some logs?

Hi @Nokel81 , thank you for your support.

The logs I retrieved from `Library/Logs/Lens` displayed as HTML page (it's my company's Apache server) after I tried connecting to a local cluster `localhost:60360` like this:

![Error response](https://imgshare.io/images/2021/04/26/Screen-Shot-2564-04-26-at-21.36.25.png)

Here is my `/etc/hosts` file:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by Nokel81** [comment]
So, correct me if I am wrong, but are you proxying localhost to some other host? Or do you have a security software that might be blocking the connection?

**Comment by mspedda** [comment]
I got similar issue and new to Lens, is this issue resolved for you ?

**Comment by raksit31667** [comment]
> I got similar issue and new to Lens, is this issue resolved for you ?

Not yet, as I am working with IT support of my company to investigate configured proxies.

**Comment by mspedda** [comment]
Thank You, let me know when you find a fix.

**Comment by smarsh-tim** [comment]
If you're running this in something like AWS EKS, where using an external authenticator like AWS IAM - you can get  this error if that configuration is incorrect.

Specific to AWS you have to do something like this: https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/

Personally, I've received this same error when either:
- aws_auth configmap is incorrect
- aws_auth configmap is not in the kube-system namespace

To resolve (if in EKS), you'd need backdoor login using the AWS root user. Then correct the aws_auth configmap.

**Comment by code-is-art** [comment]
I had a similar issue and for my particular case it was that I am using different aws profiles for different aws accounts with different clusters. The solution that helped me was to [add AWS_PROFILE to the kubeconfig](https://github.com/kubernetes-sigs/aws-iam-authenticator#specifying-credentials--using-aws-profiles).
```yaml
env:
  - name: "AWS_PROFILE"
    value: "dev"
```
I see you have ... in yours so maybe it might not help you but in case this helps someone else I am posting anyways.

**Comment by raksit31667** [comment]
> If you're running this in something like AWS EKS, where using an external authenticator like AWS IAM - you can get this error if that configuration is incorrect.
> 
> Specific to AWS you have to do something like this: https://aws.amazon.com/premiumsupport/knowledge-center/amazon-eks-cluster-access/
> 
> Personally, I've received this same error when either:
> 
> * aws_auth configmap is incorrect
> * aws_auth configmap is not in the kube-system namespace
> 
> To resolve (if in EKS), you'd need backdoor login using the AWS root user. Then correct the aws_auth configmap.

Based on the fact that I faced this issue while connecting to EKS via `aws-vault`, I am able to resolve it by modifying `~/.kube/config` like below:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: my-server-name
  name: my-cluster/name
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:57182
  name: kind-kind
contexts:
- context:
    cluster: my-cluster/name
    namespace: my-namespace
    user: my-cluster/name
  name: my-cluster/name
- context:
    cluster: kind-kind
    namespace: local
    user: kind-kind
  name: kind-kind
current-context: my-kube/context
kind: Config
preferences: {}
users:
- name: my-cluster/name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      # Change args and command to execute aws-vault
      args:
      - "exec"
      - "example-spring-loyalty"
      - "--"
      - aws
      - eks
      - --region
      - my-region
      - get-token
      - --cluster-name
      - my-cluster-name
      command: aws-vault
      env:
      - name: AWS_PROFILE
        value: ...
- name: kind-kind
  user:
    client-certificate-data: ...
    client-key-data: ...
```
