### ISSUE TITLE
HPAs not displayed unless role grants via empty api group

### ISSUE THREAD

**Issue by rittneje** [lensapp/lens#2630]
**Describe the bug**
We have a role that grants access to HPAs like this:
```yaml
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
```

However, even though I can access/list HPAs via kubectl, the HPA section under Configuration is missing in Lens.

If I change the role to also grant on the empty api group:
```yaml
- apiGroups: ["", "autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
```

then it works, even though that API group is wrong.

**To Reproduce**
1. Log in as a user with a role that looks like the first one above.
2. See that HPA is missing.
3. Update the role to look like the second one above.
4. Now see that HPA is visible.

**Expected behavior**

HPAs should be visible when the role grants against the autoscaling API group.

**Environment (please complete the following information):**
- Lens Version: 4.2.2
- OS: macos 10.15.7
- Installation method (e.g. snap or AppImage in Linux): n/a

**Additional context**
EKS v1.16
