### ISSUE TITLE
Custom resources are also fetched at cluster scope when filtering by namespaces, causing "Failed to load items" to be displayed

### ISSUE THREAD

**Issue by shmyer** [lensapp/lens#2683]
**Describe the bug**
When opening the view for a Custom Resource and filtering by namespace, Lens tries to retrieve Custom Resources not only at namespace scope (e.g. `GET /api-kube/apis/bitnami.com/v1alpha1/namespaces/<namespace>/sealedsecrets`), but also at cluster scope (e.g. `GET /api-kube/apis/bitnami.com/v1alpha1/sealedsecrets`). Since retrieving them at cluster scope is not allowed in our Cluster, the request is answered with a 403 Forbidden and Lens displays "Failed to load items", although the request at namespace scope was processed successfully.

Furthermore, when the request at namespace scope is processed I can see the retrieved resources in the view flashing for a very short time and then being replaced by "Failed to load items", since then the request at cluster scope fails.

**To Reproduce**
1. Have Custom Resources not gettable/listable at cluster scope, but at namespace scope
2. Don't use "accessible namespaces" feature and have namespaces listable at cluster scope
3. Open Developer Tools and open the View for a custom resource, while filtering by a namespace
4. In the Network tab of the Dev Tools you can see, that one request (namespace scope) is successful and endless requests are tried at cluster scope without success

**Expected behavior**
Only retrieve custom resources at namespace scope when the namespace filter is applied.

**Screenshots**
n/a

**Environment (please complete the following information):**
- Lens Version: 4.2.3
- OS: Win 10 Pro Version 1909 (Build 18363.1377)
- Installation method: Setup .exe

**Logs:**
How would I find Logs on Windows? The Logs I found under `C:\Users\<user>\AppData\Roaming\Lens\Lens\logs` are almost empty and have no relevant information regarding this issue

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <certificate-authority-data>
    server: <server>
  name: aks-test
contexts:
- context:
    cluster: aks-test
    user: clusterUser_rg-aks-test_aks-test
  name: aks-test
current-context: aks-test
kind: Config
preferences: {}
users:
- name: clusterUser_rg-aks-test_aks-test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - <server-id>
      - --client-id
      - <client-id>
      - --tenant-id
      - <tenant-id>
      command: kubelogin
      env: null
      provideClusterInfo: false

```
fy: using kubelogin: https://github.com/Azure/kubelogin

**Additional context**
n/a
