### ISSUE TITLE
node shell container image is not configurable 

### ISSUE THREAD

**Issue by danielwegener** [lensapp/lens#2742]
In https://github.com/lensapp/lens/blob/743597e2f545b15415316118ac8cdd55c09b8dfc/src/main/shell-session/node-shell-session.ts#L59 the node shell container is created using the fixed image docker.io/alpine:3.12. Or EKS cluster is running in a private VPC without any connection to docker.io, so multiple node-shell containers are created and end up with ImagePullBackOff. 

Would it be possible to make this image configurable in the app preferences?

Thanks in advance!

**Comment by meganeinu7** [comment]
We are often seeing this:
```
Failed to pull image "docker.io/alpine:3.12": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: 
You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```
Would it be possible to make imagePullSecrets configurable as well?

```
spec:
    containers:
    - name: "shell"
      image: "docker.io/alpine:3.12"
    imagePullSecrets:
    - name: regcred
```
