### ISSUE TITLE
Unable to connect to cluster after AWS session token is refreshed via awsume/aws-iam-authenticator

### ISSUE THREAD

**Issue by jamesdowning-chip** [lensapp/lens#2831]
**Describe the bug**
Using awsume to assume a role and provide a session token to access an EKS cluster. Launching Lens for the first time from the cli works however as soon as the token has expired and a new one needs to be generated via providing a MFA token Lens loses connection to the cluster.

**To Reproduce**
1.  awsume my-role
2. `kubectl get nodes` - nodes are shown 
3.  `open /Applications/Lens.app/`
4.  Add cluster, authentication successful in Lens
5. `awsume -r`
6.  Enter MFA token
7. Invalid credentials error now appears in Lens.

**Expected behavior**
Lens should continue to have connection to the cluster despite a new token being issued.

**Screenshots**
![Screenshot 2021-05-20 at 14 14 44](https://user-images.githubusercontent.com/83716012/118985173-2308f080-b976-11eb-9c14-d1f05b062e5c.png)

**Environment (please complete the following information):**
- Lens Version: tried versions `4.2.4`,`3.6.7`,`4.0.6`
- OS: MacOS BigSure
- Installation method (e.g. snap or AppImage in Linux): brew

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ****************************
    server: https://**********************.yl4.eu-west-2.eks.amazonaws.com
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-role
  name: my-cluster
current-context: my-cluster
kind: Config
preferences: {}
users:
- name: my-role
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - my-cluster
      command: aws-iam-authenticator
      env:
      - name: AWSUME_PROFILE
        value:  my-role
```

**Additional context**
The only workaround I've found is to re-install Lens, which again authenticates the cluster initially but never past the point of receiving a new session token.
