### ISSUE TITLE
metrics stack numbers are completely wrong

### ISSUE THREAD

**Issue by matti** [lensapp/lens#2864]
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doom
  namespace: doom
spec:
  selector:
    matchLabels:
      app: doom
  template:
    metadata:
      labels:
        app: doom
    spec:
      containers:
      - name: doom
        image: mattipaksula/http-doom
        resources:
          requests:
            memory: "48Mi"
            cpu: "1"
          limits:
            memory: "48Mi"
            cpu: "1"
```

![2021-05-25 at 9 48](https://user-images.githubusercontent.com/3893/119451812-595fba80-bd3e-11eb-9b14-b051ec97ab03.jpg)
