### ISSUE TITLE
Prometheus Operator Lens Monitoring Not Working

### ISSUE THREAD

**Issue by JessedeJonge** [lensapp/lens#289]
**Describe the bug**
I am trying to add an already running Prometheus instance for the Lens monitoring. Unfortunately the following changes have not done the trick for me, and Lens still isn't showing metrics. Any thing I am missing here?

**To Reproduce**
Install the prometheus operator from the Helm stable repo with the following values.yaml:
``` 
nodeExporter:
  serviceMonitor:
    relabelings:
      - sourceLabels: [__meta_kubernetes_pod_node_name]
        action: replace
        regex: (.*)
        replacement: $1
        targetLabel: kubernetes_node

kubelet:
  serviceMonitor:
    metricRelabelings:
      -  sourceLabels: [__metrics_path__]
         targetLabel: metrics_path
      -  sourceLabels: [node]
         targetLabel: instance
         action: replace 
```

The servicemonitors show the[ change needed for lens](https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md) is applied (`kubectl edit -n monitoring servicemonitors monitoring-prometheus-oper-node-exporter`): 

```
spec:
  endpoints:
  - port: metrics
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: kubernetes_node
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: monitoring
```

and `kubectl edit -n monitoring servicemonitors monitoring-prometheus-oper-kubelet`

```
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    metricRelabelings:
    - sourceLabels:
      - __metrics_path__
      targetLabel: metrics_path
    - action: replace
      sourceLabels:
      - node
      targetLabel: instance
```
**Expected behavior**
Lens should show statistics about pods and nodes of the cluster when adding `monitoring/monitoring-prometheus-oper-prometheus:9090` as instance. But says metrics are unavailable.

**Additional context**
Might be a good idea to update the [docs](https://github.com/lensapp/lens/blob/master/troubleshooting/custom-prometheus.md) with a working example for prometheus operator since its so commonly used to spin up Prometheus.
