### ISSUE TITLE
LENS slows system down to a crawl when SSO login expires

### ISSUE THREAD

**Issue by karlschriek** [lensapp/lens#2994]
**Describe the bug**
We use SSO login with assume-role to establish a connection to our EKS clusters. 

Typically the kubeconfig user would look something like this:

```
- name: arn:aws:eks:eu-central-1:123456789012:cluster/my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      - --role
      - arn:aws:iam::123456789012:role/kubernetes-admin-role
      command: aws
      env:
      - name: AWS_PROFILE
        value: my-profile
```
And the AWS profile would look like this:

```
[profile my-profile]
region = eu-central-1
sso_start_url = https://my-company.awsapps.com/start
sso_account_id = 123456789012
sso_role_name = PowerUserAccess
sso_region = eu-central-1
```

In order to establish a connection to the AWS cluster, the profile "my-profile" needs to first authenticate via SSO login. E.g.:

`aws sso login --profile my-profile`

At this point it is possible for LENS to connect to the cluster normally. This SSO login however expires once or twice per day. LENS does not appear to handle this expiry particularly well. Most mornings when I start up my workstation LENS is drawing almost all of my CPU resources (presumably in an attempt to connect to my cluster, but failing to do so since SSO login has expired). The issue is only resolved by renewing the SSO login.

**To Reproduce**

Login via SSO. Wait of SSO to expire.

**Expected behavior**
I would expect lens to either give up attempting to connect or in some other way limit the amount of CPU usage when unable to do so.

**Environment (please complete the following information):**
- Lens Version: 4.2.3
- OS: Windows
