### ISSUE TITLE
Kubeconfig cannot be parsed when users section contains user with empty name

### ISSUE THREAD

**Issue by gdubya** [lensapp/lens#2996]
**Describe the bug**
If the "users" sections of a kubeconfig contains a user with an empty name then trying to add a cluster via the Lens GUI does not work and no error message is given. 

Example from kubeconfig
```
users:
- name: ""
  user:
    client-certificate-data: certdatahere..
    client-key-data: keydatahere....
```

If you paste the text from the config file then the correct error message is displayed ("users[0].name is missing")

My kubeconfig contains several configurations and i'm not sure where this particular user came from.
