### ISSUE TITLE
[5.0.0-beta.7] Cannot connect with Docker Desktop

### ISSUE THREAD

**Issue by juergenzimmermann** [lensapp/lens#3029]
**Describe the bug**
When I try to use a fresh installed Lens _5.0.0-beta.7_ I cannot connect with Docker Desktop _3.3.3_ on WIndows Enterprise 10 21H1. I get several error messages:

```
2021/06/11 06:29:40 http: proxy error: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

**To Reproduce**
1. Start Docker Desktop _3.3.3_ on WIndows Enterprise 10
2. Start Lens _5.0.0-beta.7_

**Expected behavior**
Lens should start and connect with the K8s installation at Docker Desktop on Windows 10

**Screenshots**
Attached below

**Environment (please complete the following information):**
- Lens Version: 5.0.0-beta.7
- OS: WIndows Enterprise 10 21H1
- Installation method (e.g. snap or AppImage in Linux): .exe file for Windows

**Logs:**
```
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register succeeded ✅
```

**Kubeconfig:** $env:USERPROFILE\.kube\config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
contexts:
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
current-context: docker-desktop
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: ...
    client-key-data: ...
```
