### ISSUE TITLE
Can't add cluster

### ISSUE THREAD

**Issue by BeLeap** [lensapp/lens#3062]
**Describe the bug**

It fails to add cluster

**To Reproduce**

1. Try to add cluster context

**Expected behavior**

Cluster context added

**Screenshots**

<img width="1459" alt="Screen Shot 2021-06-15 at 9 22 01 PM" src="https://user-images.githubusercontent.com/46488521/122051939-1ca85000-ce20-11eb-89a9-21d6c10d48aa.png">

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: macOS
- Installation method (e.g. snap or AppImage in Linux): dmg(FYI. [Download Link](https://github.com/lensapp/lens/releases/download/v4.2.4/Lens-4.2.4.dmg))

**Logs:**

I can't find Lens.app executable
Maybe... This one?
```
[32minfo[39m: üîå Starting LensProxy
[32minfo[39m: [LENS-PROXY]: Proxy server has started at http://localhost:61741
[32minfo[39m: üîé Testing LensProxy connection ...
[32minfo[39m: ‚ö° LensProxy connection OK
[32minfo[39m: üñ•Ô∏è  Starting WindowManager
[32minfo[39m: üß© Initializing extensions
[32minfo[39m: [EXTENSION-DISCOVERY] loading extensions from /Users/beleap/Library/Application Support/Lens
[32minfo[39m: [EXTENSION-INSTALLER] installing dependencies at /Users/beleap/Library/Application Support/Lens
[32minfo[39m: [WINDOW-MANAGER]:¬†Loading Main window from url: http://localhost:61741 ...
[32minfo[39m: [EXTENSION-INSTALLER] dependencies installed at /Users/beleap/Library/Application Support/Lens
[32minfo[39m: [EXTENSION-DISCOVERY] watching extension add/remove in /Users/beleap/.k8slens/extensions
[32minfo[39m: [EXTENSION]: enabled lens-license@0.1.0
[32minfo[39m: [STORE]: LOADED from /Users/beleap/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
[31merror[39m: [EXTENSIONS-LOADER]: can't load extension main at /Users/beleap/Library/Application Support/Lens/node_modules/lens-telemetry/dist/main.js: Error: Command failed: ioreg -rd1 -c IOPlatformExpertDevice
/bin/sh: ioreg: command not found
 {"extension":{"id":"/Users/beleap/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","absolutePath":"/Applications/Lens.app/Contents/Resources/extensions/telemetry","manifestPath":"/Users/beleap/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","manifest":{"name":"lens-telemetry","version":"0.1.0","description":"Lens telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","analytics-node":"^3.4.0-beta.3","jest":"^26.6.3","mobx":"^5.15.5","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true},"error":{"status":127,"signal":null,"output":[null,{"type":"Buffer","data":[]},{"type":"Buffer","data":[47,98,105,110,47,115,104,58,32,105,111,114,101,103,58,32,99,111,109,109,97,110,100,32,110,111,116,32,102,111,117,110,100,10]}],"pid":38009,"stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[47,98,105,110,47,115,104,58,32,105,111,114,101,103,58,32,99,111,109,109,97,110,100,32,110,111,116,32,102,111,117,110,100,10]}}}
[32minfo[39m: üì° Checking for app updates
[32minfo[39m: Checking for update
[32minfo[39m: [STORE]: LOADED from /Users/beleap/Library/Application Support/Lens/lens-cluster-store.json
[32minfo[39m: [STORE]: LOADED from /Users/beleap/Library/Application Support/Lens/lens-extensions.json
[32minfo[39m: [STORE]: LOADED from /Users/beleap/Library/Application Support/Lens/lens-filesystem-provisioner-store.json
[32minfo[39m: [CLUSTER-STORE] requesting initial state sync
[32minfo[39m: [STORE]: LOADED from /Users/beleap/Library/Application Support/Lens/lens-workspace-store.json
[32minfo[39m: [WORKSPACE-STORE] requesting initial state sync
[32minfo[39m: [STORE]: LOADED from /Users/beleap/Library/Application Support/Lens/lens-user-store.json
[32minfo[39m: [CLUSTER-STORE] start to listen (1)
[32minfo[39m: [WORKSPACE-STORE] starting to listen state events
[32minfo[39m: [EXTENSION]: enabled kube-object-event-status@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-metrics-cluster-feature@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-node-menu@0.1.0
[32minfo[39m: [EXTENSION]: enabled lens-pod-menu@0.1.0
[32minfo[39m: [STORE]: LOADED from /Users/beleap/Library/Application Support/Lens/extension-store/lens-survey/preferences-store.json
[32minfo[39m: [EXTENSION]: enabled lens-survey@0.1.0
[31merror[39m: [EXTENSIONS-LOADER]: can't load extension main at /Users/beleap/Library/Application Support/Lens/node_modules/lens-telemetry/dist/renderer.js: Error: Command failed: ioreg -rd1 -c IOPlatformExpertDevice
/bin/sh: ioreg: command not found
 {"extension":{"id":"/Users/beleap/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","absolutePath":"/Applications/Lens.app/Contents/Resources/extensions/telemetry","manifestPath":"/Users/beleap/Library/Application Support/Lens/node_modules/lens-telemetry/package.json","manifest":{"name":"lens-telemetry","version":"0.1.0","description":"Lens telemetry","main":"dist/main.js","renderer":"dist/renderer.js","lens":{"metadata":{},"styles":[]},"scripts":{"build":"webpack -p","dev":"webpack --watch","test":"jest --passWithNoTests --env=jsdom src $@"},"dependencies":{},"devDependencies":{"@k8slens/extensions":"file:../../src/extensions/npm/extensions","@types/analytics-node":"^3.1.3","analytics-node":"^3.4.0-beta.3","jest":"^26.6.3","mobx":"^5.15.5","node-machine-id":"^1.1.12","react":"^16.13.1","ts-loader":"^8.0.4","typescript":"^4.0.3","universal-analytics":"^0.4.23","webpack":"^4.44.2"}},"isBundled":true,"isEnabled":true},"error":{"status":127,"signal":null,"output":[null,{"type":"Buffer","data":[]},{"type":"Buffer","data":[47,98,105,110,47,115,104,58,32,105,111,114,101,103,58,32,99,111,109,109,97,110,100,32,110,111,116,32,102,111,117,110,100,10]}],"pid":38013,"stdout":{"type":"Buffer","data":[]},"stderr":{"type":"Buffer","data":[47,98,105,110,47,115,104,58,32,105,111,114,101,103,58,32,99,111,109,109,97,110,100,32,110,111,116,32,102,111,117,110,100,10]}}}
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /preferences
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /landing
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /landing/:workspaceId
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /cluster
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /cluster/:clusterId/settings
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /extensions
[32minfo[39m: [PROTOCOL ROUTER]: internal registering /extensions/install/:LENS_INTERNAL_EXTENSION_PUBLISHER_MATCH(@[A-Za-z0-9_]+)?/:LENS_INTERNAL_EXTENSION_NAME_MATCH
[32minfo[39m: [WINDOW-MANAGER]: Main window loaded
[31merror[39m: Can't find working API for the Kubernetes resource ingresses
[32minfo[39m: Update for version 4.2.4 is not available (latest version: 4.2.4, downgrade is disallowed).
```

**Kubeconfig:**

kubeconfig was created by awscli, so I don't think it's wrong.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <<***censored***>>
    server: https://<<***censored***>>.ap-northeast-1.eks.amazonaws.com
  name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
- cluster:
    certificate-authority-data: <<***censored***>>
    server: https://<<***censored***>>.ap-northeast-1.eks.amazonaws.com
  name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
- cluster:
    certificate-authority-data: <<***censored***>>
    server: https://<<***censored***>>.ap-northeast-1.eks.amazonaws.com
  name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
contexts:
- context:
    cluster: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
    user: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
  name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
- context:
    cluster: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
    user: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
  name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
- context:
    cluster: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
    user: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
  name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
current-context: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - ap-northeast-1
      - eks
      - get-token
      - --cluster-name
      - <<***censored***>>
      command: aws
- name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - ap-northeast-1
      - eks
      - get-token
      - --cluster-name
      - <<***censored***>>
      command: aws
- name: arn:aws:eks:ap-northeast-1:<<***censored***>>:cluster/<<***censored***>>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - ap-northeast-1
      - eks
      - get-token
      - --cluster-name
      - <<***censored***>>
      command: aws
```
