### ISSUE TITLE
The resource cannot be created using the K3 cluster

### ISSUE THREAD

**Issue by pughua** [lensapp/lens#3158]
**To Reproduce**
An error occurred while creating the resource

**Screenshots**
![image](https://user-images.githubusercontent.com/780726/123075545-e6378a00-d44a-11eb-80f2-782aa48183a0.png)

**Environment (please complete the following information):**
- Lens Version:4.2.4
- OS: windows 10

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
C:\Program Files\Lens>
info: 馃摕 Setting Lens as protocol client for lens://
info: 馃摕 succeeded 鉁?
(node:24552) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:3316) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ******
    server: https://192.168.0.135:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: ******
    client-key-data: ******
```

**Additional context**
1.No "kubectl.exe" is found under path "C:\Users\lemonnc\AppData\Roaming\Lens\binaries\kubectl\1.21.1+k3s1";
2.Duplicate a copy of "kubectl.exe" to  "C:\Users\lemonnc\AppData\Roaming\Lens\binaries\kubectl\1.21.1+k3s1", and when "create resource " is executed, "kubectl.exe" is deleted.
