### ISSUE TITLE
Openunison Orchestrator Opereartor errors out

### ISSUE THREAD

**Issue by matty1979** [lensapp/lens#3173]
**Describe the bug**
```
App crash at http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/crd/openunison.tremolo.io/openunisons?lens-kube-details=%2Fapis%2Fopenunison.tremolo.io%2Fv1%2Fnamespaces%2Fopenunison%2Fopenunisons%2Forchestra
Component stack:
    at VE (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7938176)
    at div
    at div
    at div
    at nh (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7795675)
    at pp (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7821387)
    at gB (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7946288)
    at cc (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7683374)
    at t (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:223994)
    at BU (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:8515564)
```

```
Error stack:
TypeError: e.status.conditions.filter is not a function
    at VE.renderStatus (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7938562)
    at VE.render (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7939175)
    at Ce (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:13973)
    at http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7558683
    at ce (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:12079)
    at e.track (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:23443)
    at VE.s [as render] (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7558631)
    at VE.Ee (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7558779)
    at VE.t.render (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:7557735)
    at _s (http://994b40c7-9c0e-4a71-b9b1-21f45bf5ab3e.localhost:62106/build/Lens.js:2:4658731)
```

**Expected behavior**
Able to correctly view the CRD

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 4.24
- OS: Mac OS
- Installation method (e.g. snap or AppImage in Linux): Download dmg

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
Matthews-MacBook-Pro:~ matthewking$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:49202/856a8c21-4dad-48d9-b82a-c9ba7dab23cc
  name: k3d-ou-test
contexts:
- context:
    cluster: k3d-ou-test
    user: proxy
  name: k3d-ou-test
current-context: k3d-ou-test
kind: Config
preferences: {}
users:
- name: proxy
  user: {}
```

**Additional context**
