### ISSUE TITLE
Lens GUI doesn't open

### ISSUE THREAD

**Issue by aharonh** [lensapp/lens#3197]
**Describe the bug**
I used to have the tool installed before, some year ago - do not recall which version. After uninstalling and installing the latest, the GUI doesn't show up. How do I troubleshoot?

**To Reproduce**
Just run kontena-lens in command line or by double-clicking it's shortcut.

**Expected behavior**
The kontena-lens GUI opens.

**Screenshots**
N/A

**Environment:**
- Lens Version: 4.2.5 (also tried with 4.2.4 with same symptoms)
- OS: Ubuntu 20.04.2 LTS 
- Installation method: deb (also tried AppImage with same results)

**Logs:**

```
aharon@dev ~/ {dev.nvsrc.com} $ kontena-lens 
info: 📟 Setting Lens as protocol client for lens://
info: 📟 failed ❗
info: 🚀 Starting Lens from "/home/aharon/.config/Lens"
info: 🐚 Syncing shell environment

```

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRlpWSGRBUGkrdnZYMnJMMk1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1Ua3dOREV5TURjME16STVXaGNOTWprd05ERXhNRGMwTXpJNQpXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQWsrdktwUXFjL2Rudy9TU1ZlWVZ5MmVjakllZkZwM09TRUVYMlUwZTFnWGRLeXR4SVdqRm4Kby9WMStsVjVBN0hkOWs1dHdKRVlabzdYbHA3c2xCTUR2OUlJM2NLNFpGWjFuUHkrR2ViZk5IQXZSR3loSGZOZQpFM2pOWUpnMnhETXlZc0VLcWJ3aXgzcWc3UDZrZ1JZN014c1hkbVBlai9WRldVY2hZL25JT2hBZGRiNVVEczhTCmdKNll0Y3lJcUlHV2VFNWtROTl2RTJDZDZIanNFak5TZDRzUXZpdWFJNU5MY25GZkVmMnoyMW9MdlFabFBKK3cKZTRsYWhaZlRCZHg4WDFzdHZWMUR4MWw2em1lWjdQSXIzUHZoTno2SmlpSnpjQ1IzZTlXcGtQYU1GMmYxZXdtVQpJUWJWcXRSaU5HcW9lODY5VHJqb016NEtwb3l0VmNxbkhRSURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFWcU1PMTNUVitJSlIKMHJWLzgrVXN0SlFjSWsreU03aWpFVlNTTklMVlNaMEJHMTFJU0dVTlMvYTdEaEZJTWhMb2p1LysySE92aGppNwpLZ1VSOWo2TUQzaFpTRUt6NDcxcTNpYlFpN3pwOXNOQlZ4NHVSZzJKQzRnRlR5em9CRDBpYTN2bHVNVTB4ekNUCkF5N05BMXVpczQzWGZsTUZ1dUxBZUdoVnVBVDJhUldVR05uUDg1SDYrK3JrdzVVQW5RMVJhMEpxa1hiTllkZUQKZGtmdzNYMHlHUVVzNHVra1pQQ0JsTTZmSy9mUzlRUThsdHNhRXdLQjZtZFhrbHJFcEd6WlhCVDNyQlF3YSsyMAp1NlNpeEFOaHlsYXBoc1pKK0Z6bG5CVlkwRUoyb2RyYU11ZWw1SFpnc1dXbTYrZWloM0loSStKY25TWFJtbFFyCjNTaW1HeXBlQmc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.dev.mycompany.com
  name: dev.mycompany.com
contexts:
- context:
    cluster: dev.mycompany.com
    namespace: vnext
    user: dev.mycompany.com
  name: dev.mycompany.com
current-context: dev.mycompany.com
kind: Config
preferences: {}
users:
- name: dev.mycompany.com
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrekNDQWVPZ0F3SUJBZ0lNRlpWSGRQVTdkNEZoL0xwS01BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1Ua3dOREV5TURjME16TXpXaGNOTWprd05ERXhNRGMwTXpNegpXakFyTVJjd0ZRWURWUVFLRXc1emVYTjBaVzA2YldGemRHVnljekVRTUE0R0ExVUVBeE1IYTNWaVpXTm1aekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSldlOGxJQTFSSTNkbkFZNXAwMlc1TTkKbzBVRVRmT25xQUNDcVl2V0NDV3YwcHVYMXZTMWpJSlM5YktwY3lmMTBLNTRiYzA4UVlkRjlEZmRJeVRQWXNVUwpsUDJaZnhzcTRRRmgrckUwaFNqTWY5b3QxRXlGWXVhQkNudmNzVXlRZk4zcGwvWFdiWWpMMHY0aWJXTDFudmJMCkVuMVdqSmwrQ3dJb3hHUzBPSVFuOHVyRXA1QmtuM09JTjkrMXN2Zm9aTWlLWDF5SjlUUDh0aVA2d0tWR3g4QXcKYmxqV0NFT244c0QxaEVyQUZaZVRmOVNwaGM3dHo2WkRORXJRR1Q0Rms2T0p5RHZreHRqaERRT0ZCMDB5NzdoVwpxK2swc2JQWWE2Z1RjVFM2NEVBam1LdjJBUHhBblRRZzVZR3U5S004Y0RtZ1pRbkt5RDZ6ajkyWVBNbzdQRUVDCkF3RUFBYU0xTURNd0RnWURWUjBQQVFIL0JBUURBZ2VBTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGQndNQ01Bd0cKQTFVZEV3RUIvd1FDTUFBd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHTXgyaTd5SlNJaHl5TGFIcE94YVVJVAo5L2k3TnVja3VkNlVsTkRvVVRxNTh0dDZ0L0dXZUQ4bzFpRWttSXVBZzJnMXdvU2NqR3l6WlprNGJYbmhOVHdUCkFLalJrZUNYNmYySkpvRXhiZThwTFFJMGdkQ2pxemNJSFNQM0pJSytLdUtRTEhuTUZ5d1c5NnRKM2tMa0hUVWEKMWZRZWEvUFVYK3BzQ2ZMdzF1K3g4MkZjRytXTThCRmR5SmVEci9mbUJwOWtMalNtNERqUTBBR2p4cnd2Z3hJSQppQXRUMVZMNis2b1grVFpDQ3lQTmJyU0F2NzdoZmpwMlNhNHBuMlR1UEJhOExJakZJSjBuVWoyMm1DU1dRbTZiCmwxRFFnRHJ6aEFpMm44RE5sbUFRL01zZ0pGODh2S0hlSFhGWkJ6UEZYckZLTDdxMW1JNnEwa1lBWGFzMW1LUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: REMOVED==

```

**Additional context**
Used to the tool a year ago and it worked back then.
