### ISSUE TITLE
Unable to connect to a cluster with public ip and http proxy is enabled

### ISSUE THREAD

**Issue by fluidjeel** [lensapp/lens#3260]
**Cluster Type**
Self provisioned on aws ec2 using kubeadm on public-subnet

**Describe the bug**
Unable to connect to a cluster with public ip and http proxy is enabled

**HTTP Proxy**
```https://<public-ip>:6443/```

Also tried with following:

```
kubectl proxy --port=8080
```
HTTP proxy:  ```https://<public-ip>:8080/```

**Error**
```proxyconnect tcp: x509: certificate is valid for <private-ip>,<cluster-ip>, not <public-ip>```

**Environment (please complete the following information):**
- Lens Version:
- OS: Windows10

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeE1EY3dOREEzTlRrMU9Gb1hEVE14TURjd01qQTNOVGsxT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSzRZCktzTDlBR3FSWFE4SE9RdDRHTW5ScGZqMVl6S2NJWFhTR1ZIRUwyQUxKS1M2ZVF2ZnhrSHJ1VTRRdElzSmlINm0KV1RIYm04b1FmR01QMTc2SGZicmNGK2p5MVVsRWNST0dHRlBSeVNTdnA0RVVFUlhDZzdqaGFHNCsrWkV5OEJ0VApQci91UjBZbE1sRU1HOElVMFpxTWNOS043aWhRb3E0eXBqZUNSYWFzYnBTaUh5TVc3aDlmUGx5TVFCWEs4SFhhCll2MEZLZ3ovZTFFT3IzVTU0bzA3VlpLS1EzbWRSQ056NzFYVE00VDhid1cxTkc3YkNWeG95MlZ4dFJIUy93QloKSlZuWnF3anFlR0lzTnRwMEY1YzZSQjAyZk4xN0lmOWgrYnFWazdvR2lRL1hqN0pDck1LSjYyd2t5VFp1VWx3UwpNa2h6QkYwNmw5aVoxZ3AzNnFrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCblhVWUxFSHJEdHhvbHBTcXowbmFyd3BLbURNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDQklHanRaa25WanpTTWNDRExZR1M3dlJEaXVyUVozcDlSR3RHR1NSV2Y2aFE2NVF5KwpUejFvSjRVcXJwYXEybEpIUjYrNkhiK0luV2plSDdtbUJiRjlhWmk5SEtIQlJuTld4UEtOblJVT1BaWE00eHpWCkJMNUhZQzkwVVoyYm1KQU45bXgxSExCVm1hbVJwak44VWJJVENReDhGbU1RTjFvb0dGYUNyMDVySGZ6ZWhzRnoKS2d5bFAyV2V1YStIMW9oRkJ2allDTk9FTHBpYnIxQW02d2d1cGFkd3lyNmZTTVBPU3hKbEUrYVJtay9HVHBYYQoxTTdOTVowdlRXTTZrbFAvU3dGRHhqTU9vN0QzMEU3amZQWVh6Qk5oMTVpQnZod2JOM211azFwOEhCWEFJeG00Cm02Nkc3TWdEdlZ3TllDSm4xTFAwYjJ1cGJwQUhJc0J3R0hYQgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://192.168.1.68:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lJZVp6YlptNVowQU13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TVRBM01EUXdOelU1TlRoYUZ3MHlNakEzTURRd09EQXdNREZhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXhFYk8vUUZxK2hoQ1VySmcKVlI1VStObVNXcS9GcDdtTGdCWUh2V2F4OFg4bTRvdS8rbVJsRlFXMVprbXRzdWo1QUdQMHRQWHVmYmN1R3JBagpUdGxxQitabEZnYnVPOEk5WUVubWloSHBSb1oyNFVNM2cyNVU0d0hzckhQa0RiUnYvblpBbmxIdnpGMGtFUTZsCjc0dG16VElEQXNtOU1KdTFHZW9zblhuSFhIQ0Y5Y3RXcmxody9NZWQ2QVJibzdheGgvaldRby9qVkx5SGhsU1IKVU1PVUVJUXRVNGtMNjRNSmRmYXQvbDA5ZE5aWlZnb0N4SU50eVY2OXZmT05FUG5tOFlxem1CRjdvcmJ5OHZxdApLM2d3NUFSUUN0NERKandkakhBN1hqWXZFK3JrSHhxbzdzZzRKOGs3aGVjbGtaMVhDZC9OL09mWHI4WnlsM0hzCjFaK3JId0lEQVFBQm8xWXdWREFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JRWjExR0N4QjZ3N2NhSmFVcXM5SjJxOEtTcApnekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBbE91K1diVEwrTUFkdVVmbkZmNldySExKOFllOUZJdjduKzMvClhCM3FhbGlUdDZRSUs0SmhlRlRwVW1UM0ZWWUMxRGpVSmVKUmgzYVVRM01QVWVSTVdIWUFoYVJENm9PcWFWTkwKeWQwV2RjcUUrQ1RkQUtKRDlmTFZnM2ZMbStlTHdXTXNqSTBkc3Q4UkNXcTU5Z3hrbmJNVUpLaTNzRGVIc2pDbApLbzVrQ2ptSitSM2ZIUmhvcTN0RVBGNUV6YnY5V2c3M3ZuSFhrMHA3Z2ttU200UkQ3alRDbGtWKzVGeDJzTUVSClBWcmtaRXRLaE12a2lxMm9NeEJYRFJEMG9XSkh6dWNKRTRKQm9sTndqT1p1WWlZMHpkaGR3VHJrQ1N2UzFEazkKaE9DQ1dRR0dkdHJpY3dVaS8vb0gwT2ZGbFBGbFVNYWg0T1ZCb2lZb3dQUyt2OWxCNnc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBeEViTy9RRnEraGhDVXJKZ1ZSNVUrTm1TV3EvRnA3bUxnQllIdldheDhYOG00b3UvCittUmxGUVcxWmttdHN1ajVBR1AwdFBYdWZiY3VHckFqVHRscUIrWmxGZ2J1TzhJOVlFbm1paEhwUm9aMjRVTTMKZzI1VTR3SHNySFBrRGJSdi9uWkFubEh2ekYwa0VRNmw3NHRtelRJREFzbTlNSnUxR2Vvc25YbkhYSENGOWN0VwpybGh3L01lZDZBUmJvN2F4aC9qV1FvL2pWTHlIaGxTUlVNT1VFSVF0VTRrTDY0TUpkZmF0L2wwOWROWlpWZ29DCnhJTnR5VjY5dmZPTkVQbm04WXF6bUJGN29yYnk4dnF0SzNndzVBUlFDdDRESmp3ZGpIQTdYall2RStya0h4cW8KN3NnNEo4azdoZWNsa1oxWENkL04vT2ZYcjhaeWwzSHMxWitySHdJREFRQUJBb0lCQVFDL0o4TWhiMGNUcVpxMgpWWmt5Yk9jT3NUOHphU3JVRGdYSnlpcmhrR25QTENuZnk0RStTSmFWb2Npb2hTdFJLa3FQMGNtYWtFWWtVOG5vCkhoRlZFck9NWEJ1cEZ6amdKRzJJSUpFUmVSNDdIR3dkT1V5UWlWek05YXZkek1TWGdGcnVkWmE3V2t0ME9tWU0KNHJwREVQNGU3QTA0b3VmSnRtdnJnRURSWWJBQzJyR0VLS2lHVG43WFZVTnA3ZldpUUpPUDlLV2FBcmxONmpvSQpRMm5iNzM0OFpKVngvdVE4NDQ1VmpkNEwzTm9IV2x5eEx4aUhZN3pEWFQvVHVRNTh0cTBwbWNaQlc1QmNONTJ4CnBTNUxUUndEOWV5VGE0OEZMbUlVYlVBNXNXQlhBbG9IaHBXNGE3U3ZuSGpYZGp4eUR0QlNzNEw1VHB0Qmx2dkMKclUrU3pnc0JBb0dCQU16S290ZTIwRGtlMUdyL0MvT1lqWkRTbFJNMVk2T0RiS05Oa2x1bnVXV3cxY2lBZklDdAo5RUtBcXRNT3hubDc5VzVXdkpJZUExUFBPbFYrcjFoU2xsZnc5Ym9scFNHTXFiYWticmJTK3JHOVJERnNDWkdECmo4dmFvanNXVXE1LzJFcklacFI2NEluS1U0bDk4bnZ0ZjFRZXBENS96OW1kNCtNbGFkRUo2ZDZmQW9HQkFQVmIKR21RZlhCUU5CVlF4KzNIQzBmMHNvNkxuNnpsbzVVeXdyVkFJd2RFZE50cjVOUEN1L1RvU3FybXF3MmNSZDYxagplRmxqdXhpcFFXbXc3eVNzVmQvRmdLTFE5cW16eFNjd1RqUWVaRDA0aXZVdjRxc243WDZIUytVUlJrOG94cDRRClh2RFdJZ0NaSE1QbVR2YVBVT01zelhUSCsxbEpvNFZCV0FIdThXT0JBb0dBY0cyU3B0QnpVZGlPRDB1RHVURDQKRHhpOHhMWGJ4S25qRzJmN3dKdTgyWW9TWTZlK01qck56VENzRjRDV0Q1Mnc2T2x2VHR4eFFUS1VPTmw2MUFkTApDRzU5eUxyZ0JDSWdEZWdKN0E2NW1KaHFkcU4wUVZHendOdC9rdWEzYjVzNkdCd2F6TXNFdUVDK1NjNCtNREQ3ClpTZ0pUVktIdmxYREJUSEYvUC92UjhzQ2dZRUEyMS9Db0FUZUNsdCtDVUxMWkhMaDJIRmlPaFVNMzM3bmpvTmwKNHVxQmlSeUs0SXp6aGNPZ1RKMUdJczRJK28zR3FMUUlkanhTbkFFeHFITjN6eDE3aHFHTG00Z2xFNlRWd1cxUwpidzFCYU8rMlp2V1N3Si9wbkRrU1pkVGxQWC9pM284YXBGR0JnM0ZqSTlFM2h3S3JPd1BqQytpRzF0V2RyRmE1CmZya0xBWUVDZ1lFQWlNZjQrQUFDeVQ2SjNaN1BheUtJRHdVT2ZlUWhKVFl2OGZ5SlA4NFFBM1NpRUhrN3Q2ZTIKRjUwQk1UQStJbTU1UGEvczdjY0tmaFRDbWdJOWR3R0YwL281VTVLbitOOVFrelFvb0ltQ054VGlSNUJGdXpmcQovT1F1ZnovNjd2a3BHZUMyOG9tUjRndUdyTEYxalBRcFh1eDNYY2gveDMwQ3Z3dk9ueVZtbzkwPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
```
