### ISSUE TITLE
Lens not able to detect Prometheus installed as Prometheus operator in namespace monitoring

### ISSUE THREAD

**Issue by strus38** [lensapp/lens#3263]
**Describe the bug**
Lens not able to detect Prometheus installed as Prometheus operator in namespace monitoring
(or whatever other setup, monitoring is never visible)

**To Reproduce**
1. Go to 'Settings'
2. Select Prometheus Operator

**Expected behavior**
Monitoring metrics are visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/5890515/124445375-c9228580-dd7f-11eb-86cd-8bc155f48adf.png)

![image](https://user-images.githubusercontent.com/5890515/124445435-d50e4780-dd7f-11eb-86d3-c91195aced3a.png)

![image](https://user-images.githubusercontent.com/5890515/124445491-e5262700-dd7f-11eb-97d9-d28789e861f5.png)

**Environment (please complete the following information):**
- Lens Version: 5
- OS: Windows
- Installation method (e.g. snap or AppImage in Linux): Windows setup

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://localhost:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
...
```
