### ISSUE TITLE
App crash while accessing 'Endpoints'

### ISSUE THREAD

**Issue by stephenpope** [lensapp/lens#328]
**Describe the bug**
Lens seems unable to process endpoint definition.

Deployed ElasticSeach operator (kubectl apply -f https://download.elastic.co/downloads/eck/1.1.0/all-in-one.yaml) and created an elasticsearch instance as per the quickstart instructions.

Updated one of the services to use a load-balancer ..

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: cluedin
spec:
  version: 7.6.2
  nodeSets:
  - name: default
    count: 1
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
```

**To Reproduce**
1. Go to 'Endpoints' page

**Expected behavior**
Shows endpoint list

(other namespaces show endpoint list correctly)

**Screenshots**
![image](https://user-images.githubusercontent.com/689099/80700583-dbe35f80-8ad5-11ea-9667-7597d5bca1ed.png)

**Environment (please complete the following information):**
- Lens Version: 3.4.0-beta1 (also happens in 3.3.0)
- OS: [e.g. OSX] OSX 10.15.4
- Installation method (e.g. snap or AppImage in Linux): DMG (drag/drop to Applications folder)
 
**Logs:**
```
k get endpoints
NAME                   ENDPOINTS           AGE
kubernetes             192.168.64.7:6443   124m
cluedin-es-transport   10.42.2.19:9300     65m
cluedin-es-http        10.42.2.19:9200     65m
cluedin-es-default     10.42.2.19          65m
```

```
k get svc -o wide
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE    SELECTOR
kubernetes             ClusterIP      10.43.0.1       <none>          443/TCP          131m   <none>
cluedin-es-transport   ClusterIP      None            <none>          9300/TCP         73m    common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=cluedin
cluedin-es-default     ClusterIP      None            <none>          <none>           73m    common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=cluedin,elasticsearch.k8s.elastic.co/statefulset-name=cluedin-es-default
cluedin-es-http        LoadBalancer   10.43.215.163   192.168.64.25   9200:31921/TCP   73m    common.k8s.elastic.co/type=elasticsearch,elasticsearch.k8s.elastic.co/cluster-name=cluedin
```
