### ISSUE TITLE
Mac Lens desktop does not run. 

### ISSUE THREAD

**Issue by jeremy-moore** [lensapp/lens#33]
From Lens-2.0.5.dmg
Got email invite to install. 
Also link to support is broken
https://account.kontena.io/support

**Comment by InAnimaTe** [comment]
Same, takes a `kill` to actually stop it too :(

**Comment by kke** [comment]
It's being developed solely on macs so it seems strange. Which version of MacOS?

**Comment by miskun** [comment]
@nevalla can you take a look at this support link issue

**Comment by jauco** [comment]
same here. stalls on loading dialog

Lens 2.0.7 (2.0.7.20191002.30)
Mac os 10.14.4 (18E226)

**Comment by jakolehm** [comment]
Try to start Lens via terminal using command: `/Applications/Lens.app/Contents/MacOS/Lens`

Does it show any errors?

**Comment by amigold** [comment]
These are the errors I'm seeing

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'certData' of null
    at e.caData (/Applications/Lens.app/Contents/Resources/app.asar/webpack:/src/main/context-handler.ts:49:50)
    at /Applications/Lens.app/Contents/Resources/app.asar/main.js:1:271925
    at Object.next (/Applications/Lens.app/Contents/Resources/app.asar/main.js:1:272030)
    at o (/Applications/Lens.app/Contents/Resources/app.asar/main.js:1:270776)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:7755) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'certData' of null
    at e.caData (/Applications/Lens.app/Contents/Resources/app.asar/webpack:/src/main/context-handler.ts:49:50)
    at /Applications/Lens.app/Contents/Resources/app.asar/main.js:1:271925
    at Object.next (/Applications/Lens.app/Contents/Resources/app.asar/main.js:1:272030)
    at o (/Applications/Lens.app/Contents/Resources/app.asar/main.js:1:270776)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:7755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7755) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:7755) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by jnummelin** [comment]
@amigold that implies that Lens app cannot properly parse & use the kubeconfig. Could you post what kind of kubeconfig you are using, especialy the user part. Rip out any sensitive data naturally. :)

And yes, we need to handle those kind of errors better.

EDIT: 2.0.7 version should handle kubeconfig loading errors bit better.

**Comment by amigold** [comment]
@jnummelin 
hopefully this helps?

```
users:
- name: NAME HERE
  user:
    client-certificate-data: CERTIFICATE DATA HERE
    client-key-data: CLIENT KEY DATA HERE
    password: PASSWORD HERE
    username: admin
- name: NAME HERE
  user:
    password: PASS HERE
    username: USER HERE
```

**Comment by jnummelin** [comment]
@amigold thanks. having both client certs and basic auth defined, sounds wrong, not 100% sure that might break things.

Mind pasting the whole kubeconfig with sensitive data ripped out just to inspect which config might cause this.

Oh, and I'm assuming the your `kubectl` works fine with this config?

**Comment by amigold** [comment]
@jnummelin kubectl works fine indeed

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CA DATA
    server: URL
  name: NAME
contexts:
- context:
    cluster: NAME
    user: USER NAME
  name: USER NAME AGAIN
current-context: CLUSTER NAME
kind: Config
preferences: {}
users:
- name: NAME HERE
  user:
    client-certificate-data: CERTIFICATE DATA HERE
    client-key-data: CLIENT KEY DATA HERE
    password: PASSWORD HERE
    username: admin
- name: NAME HERE
  user:
    password: PASS HERE
    username: USER HERE
```
