### ISSUE TITLE
Access to prometheus metrics forbidden after upgrading from v4 to v5

### ISSUE THREAD

**Issue by enummela** [lensapp/lens#3318]
The below RBAC used to give users access to prometheus metrics in v4 but after upgrading to v5 the users are forbidden from accessing the metrics. Have there been any changes between v4 and v5 that could be causing this? Any help with this would be much appreciated!

```
kind: ClusterRole
metadata:
  name: metrics-reader
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
  - list
  - watch
```

```
kind: Role
metadata:
  name: metrics-reader
  namespace: system
rules:
- apiGroups:
  - ""
  resourceNames:
  - prometheus-server:http
  - prometheus-server:80
  - 'http:prometheus-server:'
  - prometheus-server
  resources:
  - services
  - services/status
  - services/proxy
  verbs:
  - list
  - watch
  - get
```

These are the related errors I found from running Lens in debug mode:
```
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
warn: PrometheusLens: failed to list services: services "prometheus-server" not found
info: using helm as prometheus provider
error: [Metrics]: metrics not available
```

And here are the details about the error (modified for clarity):
```
{
    "error": {
        "name": "StatusCodeError",
        "statusCode": 403,
        "message": "403 - {\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"services \\\"prometheus-server:80\\\" is forbidden: User \\\"app-maintainer:EKSGetTokenAuth\\\" cannot create resource \\\"services/proxy\\\" in API group \\\"\\\" in the namespace \\\"system\\\"\",\"reason\":\"Forbidden\",\"details\":{\"name\":\"prometheus-server:80\",\"kind\":\"services\"},\"code\":403}",
        "error": {
            "kind": "Status",
            "apiVersion": "v1",
            "metadata": {},
            "status": "Failure",
            "message": "services \"prometheus-server:80\" is forbidden: User \"app-maintainer:EKSGetTokenAuth\" cannot create resource \"services/proxy\" in API group \"\" in the namespace \"system\"",
            "reason": "Forbidden",
            "details": {
                "name": "prometheus-server:80",
                "kind": "services"
            },
            "code": 403
        },
        "response": {
            "statusCode": 403,
            "body": {
                "kind": "Status",
                "apiVersion": "v1",
                "metadata": {},
                "status": "Failure",
                "message": "services \"prometheus-server:80\" is forbidden: User \"app-maintainer:EKSGetTokenAuth\" cannot create resource \"services/proxy\" in API group \"\" in the namespace \"system\"",
                "reason": "Forbidden",
                "details": {
                    "name": "prometheus-server:80",
                    "kind": "services"
                },
                "code": 403
            },
            "request": {
                "uri": {
                    "protocol": "http:",
                    "slashes": true,
                    "auth": null,
                    "host": "localhost:63243",
                    "port": "63243",
                    "hostname": "localhost",
                    "hash": null,
                    "search": null,
                    "query": null,
                    "pathname": "/api-kube/api/v1/namespaces/system/services/prometheus-server:80/proxy/api/v1/query_range",
                    "path": "/api-kube/api/v1/namespaces/system/services/prometheus-server:80/proxy/api/v1/query_range",
                    "href": "http://localhost:63243/api-kube/api/v1/namespaces/system/services/prometheus-server:80/proxy/api/v1/query_range"
                },
                "method": "POST",
                "headers": {
                    "Host": "079d7da4b66d9219fe0de198ac254367.localhost:63243",
                    "content-type": "application/x-www-form-urlencoded",
                    "accept": "application/json",
                    "content-length": 2449
                }
            }
        }
    }
}
```

The first set of errors seem to indicate that Lens cannot locate the `prometheus-server` service in the `system` namespace, but the detailed error message shows the request being sent to the correct endpoint `namespaces/system/services/prometheus-server:80` but receiving a 403 Forbidden error.

**Comment by mmisztal1980** [comment]
We have started to experience this also after folks started to upgrade to v5

**Comment by Yann-J** [comment]
Same issue here! Lens seems to be trying to `create` resources, and that's not a permission we're willing to give...

**Comment by dwstern** [comment]
Similar issue here. In v4, I could grant permission to see metrics with this - it's probably overpermissive, but my aim in this case was to grant _read-only_ access to cluster resources and see metrics, not necessarily to grant _least privileges_:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-metrics-reader
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["monitoring.coreos.com"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
```

However, in v5, a user with these permissions can't see metrics in Lens. Like @Yann-J I really don't want to grant permission to create or change any k8s resources.

UPDATE: I figured out a solution, with a bit of help from this post describing a very similar but not quite identical problem: https://stackoverflow.com/questions/57829488/enable-access-for-kubernetes-dashboard-via-external-vip-or-floating-ip

Here's what I did - note that I haven't figured out a way to not specify the port number in the proxy name, which seems like a bad thing to me - when I tried to wildcard or omit it from the resourceNames field, it no longer worked:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-prometheus-proxy-creator
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["prometheus-operated:9090"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- nonResourceURLs: ["/ui", "/ui/*", "/api/v1/namespaces/*/services/prometheus-operated:*/proxy/*"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

Cluster Role Binding - substitute the group (or user - in which case remember to change the kind: to User too) that you're binding the role to instead of 'my-k8s-group':
```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-prometheus-proxy-creator-k8sgroup
subjects:
- kind: Group
  name: my-k8s-group # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-prometheus-proxy-creator
  apiGroup: rbac.authorization.k8s.io
```

Might not be perfect, but it's working for me.

**Comment by emouawad** [comment]
Still not working with latest lens 6.2.6

**Comment by janre** [comment]
For me this works with lens v2023.3.171731-latest:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: some-really-cool-name
rules:
  - apiGroups:
      - ""
    resources:
      - "namespaces"
      - "nodes"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - "customresourcedefinitions"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "services/proxy"
    resourceNames:
      - "prometheus-operated:9090"
    verbs:
      - "get"
      - "list"
      - "watch"
      - "create"
      - "update"
      - "patch"
      - "delete"
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - "list"
``` 

probably not the best solution, since the service account can see all services, but sufficient for me.
note also: nodes and customresourcedefinitions are optional

**Comment by stefankuksenko** [comment]
with OpenLense 6.5.2 this works for me
the same as for the previous author all service resources are available for listing, maybe there is a better solution if someone finds it please let us know.
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-prometheus-proxy-creator
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["prometheus-operated:9090"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list"]
```
