### ISSUE TITLE
Lens 5.0.2 failed to connect to a kubernetes cluster

### ISSUE THREAD

**Issue by wu105** [lensapp/lens#3330]
**Describe the bug**
Newly installed Lens 5.0.2-latest.20210705.2
Added a cluster, pasted in the content of working kubeconfig file, and the cluster is added in disconnected sate.
When connecting to the cluster, lens would display the following:
```
Authentication proxy started
Oops, something went wrong.
```
After clicking on the reconnect button on the error display, the display would change to teh following:
```
Authentication proxy started
2021/07/09 12:44:25 http: proxy error: x509: certificate signed by unknown authority
2021/07/09 12:44:35 http: proxy error: x509: certificate signed by unknown authority
502 - undefined
```
The lens preference on proxy already selected "Allow untrusted Certificate Authorities".

**To Reproduce**
See description above.

**Expected behavior**
Should connect instead of error.

**Screenshots**
copied the key text in the description.

**Environment (please complete the following information):**
- Lens Version: Lens 5.0.2-latest.20210705.2
- OS: Windows 10 Enterprise, 1909 build 18363.1646
- Installation method (e.g. snap or AppImage in Linux): direct download and install

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
N/A

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
kind: Config
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <blah>
    server: https://<domainname>:30000
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
preferences: {}
users:
- name: kubernetes-admin
  user:
    token: <blahblah>
```

**Additional context**
`https://<domainname>:30000` in the kubeconfig file is the ingress url for the apiserver which works for kubectl. 
`certificate-authority-data` is used by kubectl to verify the certificate, thus lens should have followed suite and not having any problem with the certificate with the apiserver connection.
the user `token` works fine with kubernetes dashboard through the ingress.
Lens displays `lens login` at bottom on the right which does not feel relevant (when clicked it would open the Lens Spaces sign in page at https://app.k8slens.dev/signin/... and I did not bother to register).
Not sure what the `authentication proxy` in the error messages refers to.
Our out going traffic goes through a proxy which may replace the TLS certificates but the signing authority is trusted locally.
