### ISSUE TITLE
File system error:Metrics not available at the moment

### ISSUE THREAD

**Issue by xiaozhao123254** [lensapp/lens#3372]
![image](https://user-images.githubusercontent.com/83004907/125547990-504f2a2c-5d28-4e27-a58d-03389eb5509d.png)

**Comment by Nokel81** [comment]
Is the kubernetes cluster using containerD or some other runtime?

**Comment by austinnichols101** [comment]
I have the same message on a GKE `autopilot` cluster (containerD runtime)

**Comment by ryanthedev** [comment]
I have the same issue running on AKS/containerD.

**Comment by cbluth** [comment]
i have a similar symptom, i cannot view metrics in lens with an account on the cluster using a rolebinding in a specific namespace, using eks and deploying the lens-metric namespace via the buttons in lens (from a different account):

![image](https://user-images.githubusercontent.com/6709636/132023152-588070d2-ff89-4356-8ed4-22557ccb9ffd.png)

**Comment by Nokel81** [comment]
@cbluth If you open up your devtools, do you see any logs about permsissions?

**Comment by marcbachmann** [comment]
Regarding the missing `container_fs_usage_bytes` metric, that's coming soon in cadvisor.
A PR got merged: https://github.com/google/cadvisor/pull/2936

**Comment by cbluth** [comment]
@Nokel81 @xiaozhao123254 

i have a working template here:
```
# role
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: lens-metrics
  name: read-only-lens-metrics
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - pods
  - events
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - "services/proxy"
  verbs:
  - create

# role binding
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  namespace: lens-metrics
  name: vendor-read-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-only-lens-metrics
subjects:
- kind: Group
  name: ${SOMEGROUP1}
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: ${SOMEGROUP2}
  apiGroup: rbac.authorization.k8s.io
```
