### ISSUE TITLE
Tolerations for a pod are missing the "value" field.

### ISSUE THREAD

**Issue by itamar-otonomo** [lensapp/lens#3376]
in POD detail view, the tolerations displayed are shown in the format of <key>=<effect>. There is no info displayed about the value of the specific toleration.

**To Reproduce**
1. create a pod with a specific toleration like so:
```yaml
  tolerations:
    - key: app
      operator: Equal
      value: foo
      effect: NoSchedule
```
2. when pod is running, click on it and click show in the tolerations section
3. available columns are key, operator, effect and seconds. no "value" column.

**Expected behavior**
I'd like to see in the value for every taint

**Screenshots**
![Screen Shot 2021-07-14 at 12 20 25](https://user-images.githubusercontent.com/37770416/125597654-0944db45-7ab6-4b8d-82e4-0ddcdf55cd0e.png)

**Environment (please complete the following information):**
- Lens Version: 5.0.2
- OS:OSX
