### ISSUE TITLE
Lens doesn't find/list all expected charts

### ISSUE THREAD

**Issue by vitobotta** [lensapp/lens#3515]
**Describe the bug**
Hi. I have added some repositories like grafana

**To Reproduce**
1. Go to 'Preferences >  Kubernetes > Helm Charts > Select 'grafana' from the list'
2. Click on cluster on the sidebar
3. Scroll down to Apps > Charts
4. Search for Grafana
5. some charts are shown from the grafana repo but not all. The chart for grafana itself doesn't show up. I have tried `helm repo update` and closing/reopening the app but no difference.

**Expected behavior**
I would expect Lens to list all the charts in the enabled repos.

**Environment (please complete the following information):**
- Lens Version: 5.1.3-latest.20210722.1
- OS: [e.g. OSX] macOS Big Sur 11.5
- Installation method (e.g. snap or AppImage in Linux): Just downloaded the app from the website

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
````
https://pastebin.ubuntu.com/p/zwFQKy3hTk/
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://x.x.x.x:6443
  name: alpha
contexts:
- context:
    cluster: alpha
    user: alpha
  name: alpha
current-context: alpha
kind: Config
preferences: {}
users:
- name: alpha
  user:
    client-certificate-data: ...
    client-key-data: ...e
```

**Additional context**
Not sure of what other info to provide. Thanks in advance!
