### ISSUE TITLE
TypeError: Cannot read property 'namespace' of undefined

### ISSUE THREAD

**Issue by timalander** [lensapp/lens#3543]
**Describe the bug**
When trying to open a cluster tab, I am greeted with the following error (which was not present in previous versions)

**To Reproduce**
1. Open app
2. Click on a cluster tab on the left

**Expected behavior**
The cluster tab should open
**Screenshots**
![image](https://user-images.githubusercontent.com/1991727/127672947-a9012cb5-65f2-4c66-8c9a-9af9d8dfb53a.png)

**Environment (please complete the following information):**
- Lens Version: 5.1.3
- OS: Mac OSX 11.4
- Installation method (e.g. snap or AppImage in Linux): DMG

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
TypeError: Cannot read property 'namespace' of undefined
    at pods_api_Pod.getNs (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:512082:30)
    at pods_api_Pod.getOwnerRefs (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:512113:32)
    at http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:541401:30
    at http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:7000:49
    at http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:6964:25
    at trackDerivedFunction (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:1881:18)
    at Reaction.track (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:2409:18)
    at useObserver (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:6962:14)
    at http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:7000:16
    at Ch (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450238:137)
    at li (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450261:154)
    at ki (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450259:169)
    at ii (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450258:178)
    at ck (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450355:126)
    at bk (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450331:347)
    at ak (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450331:278)
    at Tj (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450331:138)
    at Lj (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450324:163)
    at http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450204:115
    at exports.unstable_runWithPriority (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450415:343)
    at gg (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450203:325)
    at jg (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450204:61)
    at ig (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450203:428)
    at Wj (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:450325:190)
    at reactionScheduler (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:2536:12)
    at http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:2537:14
    at Hh (/Applications/Lens.app/Contents/Resources/extensions/lenscloud-lens-extension/dist/renderer.js:306:141185)
    at reactionScheduler (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:2536:12)
    at runReactions (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:2505:3)
    at endBatch (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:2172:5)
    at transaction (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:3328:5)
    at ObservableMap.replace (http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:4341:5)
    at http://677e0f7affd746a284c4e8217ba0537c.localhost:52514/build/Lens.js:518641:27
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: redacted
  name: redacted
- cluster:
    certificate-authority-data: redacted
    server: redacted
  name: redacted
- cluster:
    certificate-authority-data: redacted
    server: redacted
  name: kubernetes_prod
contexts:
- context:
    cluster: redacted
    user: redacted
  name: kubernetes-eks-poc
- context:
    cluster: redacted
    user: redacted
  name: kubernetes-eks-prod
- context:
    cluster: kubernetes_prod
    user: engineers_prod
  name: kubernetes_prod
current-context: kubernetes-eks-prod
kind: Config
preferences: {}
users:
- name: redacted
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - kubernetes-eks-poc
      command: aws
      env: null
- name: redacted
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - kubernetes-eks-prod
      command: aws
      env: null
- name: engineers_prod
  user:
    token: redacted

```
