### ISSUE TITLE
Missing *Exec* and *Log* options in Pod Menu

### ISSUE THREAD

**Issue by assafshomerivy** [lensapp/lens#3548]
**To Reproduce**
1. Go to 'Pods'
3. See error

**Expected behavior**
Get logs and exec options

**Screenshots**
![Screen Shot 2021-08-01 at 16 15 13](https://user-images.githubusercontent.com/47712834/127772238-e0193ba2-943c-4966-9003-e92e8254a2d8.png)

**Environment (please complete the following information):**
- Lens Version: 
![Screen Shot 2021-08-01 at 16 17 07](https://user-images.githubusercontent.com/47712834/127772291-d0607312-f663-499d-8036-90c5b7c58670.png)
<img width="521" alt="Screen Shot 2021-08-01 at 16 17 44" src="https://user-images.githubusercontent.com/47712834/127772310-7f485e1b-7236-40ee-8b78-ae1d0d1b664b.png">

- Installation method (drag and drop dmg):

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
not sure what you mean by that
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
➜  ~ cat .kube/config
apiVersion: v1

clusters:

- cluster:

    certificate-authority-data: *****

    server: https://api.***.****

  name: *******

contexts:

- context:

    cluster: *******

    user: ***

  name: ***-*******

current-context: ***-*******

kind: Config

preferences: {}

users:

- name: ***

  user:

    client-certificate-data: **************

    client-key-data: *********
➜  ~
```

**Additional context**
* Other team members using the exact same kubeconfig do have the `exec` and `log` options
* I followed the following [workaround](https://github.com/lensapp/lens/issues/1690#issuecomment-741636330) but didn't help at all.
