### ISSUE TITLE
How to increase Prometheus metrics scrape frequency / Lens refresh frequency ?

### ISSUE THREAD

**Issue by ypicard** [lensapp/lens#3577]
Hi,

I would like to know how to increase the refresh frequency for Prometheus metrics available in the Lens app.

I have tried increasing the `scrape_interval` on my cluster with the following settings in the Prometheus chart:
```
    values:
      - server:
          global:
            scrape_interval: 15s 
```

But nothing changed. Is there a setting to play with so that the Lens app refreshes those metrics more often? 

Thanks for this awesome product.
