### ISSUE TITLE
Lens refuses to start

### ISSUE THREAD

**Issue by ldelossa** [lensapp/lens#3580]
**Describe the bug**

❯ lens
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register failed ❗

**To Reproduce**
I'm not actually sure when/why this began to occur.

This happens everytime I try to open lens.

**Expected behavior**
Lens opens correctly.

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 5.1.3
- OS: Fedora 34
- Installation method (e.g. snap or AppImage in Linux): RPM from GH.

**Logs:**

❯ lens
info: 📟 Setting Lens as protocol client for lens://
info: 📟 Protocol client register failed ❗

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: -- redacted -- 
    server: https://127.0.0.1:45091
  name: kind-ldelossa-dev
contexts:
- context:
    cluster: kind-ldelossa-dev
    user: kind-ldelossa-dev
  name: kind-ldelossa-dev
current-context: kind-ldelossa-dev
kind: Config
preferences: {}
users:
- name: kind-ldelossa-dev
  user:
    client-certificate-data: -- redacted --
    client-key-data: -- redacted --
```

**Additional context**
