### ISSUE TITLE
An error occured while loading a crd resource list

### ISSUE THREAD

**Issue by leoendless** [lensapp/lens#369]
**Describe the bug**

A parse error occurred while loading my own customize resource definition, 

**Screenshots**

![image](https://user-images.githubusercontent.com/8739949/81794044-c1c96880-953c-11ea-945f-b1e6f7996e0b.png)

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: [e.g. OSX] MacOS Catalina 10.15.4
- Installation method (e.g. snap or AppImage in Linux): 
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Error: Lexical error on line 1. Unrecognized text.
...ta.labels.kubesphere\.io/workspace
-----------------------^
    at Parser.parseError (webpack-internal:///105:3928:15)
    at Parser.parser.yy.parseError (webpack-internal:///105:5128:17)
    at Object.parseError (webpack-internal:///105:4103:28)
    at Object.next (webpack-internal:///105:4357:25)
    at Object.lex (webpack-internal:///105:4367:22)
    at lex (webpack-internal:///105:3956:28)
    at Parser.parse (webpack-internal:///105:3969:26)
    at JSONPath.nodes (webpack-internal:///105:4982:26)
    at JSONPath.query (webpack-internal:///105:4958:22)
    at eval (webpack-internal:///990:13303:39)
```

**Comment by leoendless** [comment]
crd.yaml
```yaml
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: workspaceroles.iam.kubesphere.io
  annotations:
    controller-gen.kubebuilder.io/version: (devel)
spec:
  group: iam.kubesphere.io
  names:
    plural: workspaceroles
    singular: workspacerole
    kind: WorkspaceRole
    listKind: WorkspaceRoleList
    categories:
      - iam
  scope: Cluster
  versions:
    - name: v1alpha2
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              description: >-
                APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the
                latest internal value, and may reject unrecognized values. More
                info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
              type: string
            kind:
              description: >-
                Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the
                client submits requests to. Cannot be updated. In CamelCase.
                More info:
                https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
              type: string
            metadata:
              description: Standard object's metadata.
              type: object
            rules:
              description: Rules holds all the PolicyRules for this ClusterRole
              type: array
              items:
                description: >-
                  PolicyRule holds information that describes a policy rule, but
                  does not contain information about who the rule applies to or
                  which namespace the rule applies to.
                type: object
                required:
                  - verbs
                properties:
                  apiGroups:
                    description: >-
                      APIGroups is the name of the APIGroup that contains the
                      resources.  If multiple API groups are specified, any
                      action requested against one of the enumerated resources
                      in any API group will be allowed.
                    type: array
                    items:
                      type: string
                  nonResourceURLs:
                    description: >-
                      NonResourceURLs is a set of partial urls that a user
                      should have access to.  *s are allowed, but only as the
                      full, final step in the path Since non-resource URLs are
                      not namespaced, this field is only applicable for
                      ClusterRoles referenced from a ClusterRoleBinding. Rules
                      can either apply to API resources (such as "pods" or
                      "secrets") or non-resource URL paths (such as "/api"), 
                      but not both.
                    type: array
                    items:
                      type: string
                  resourceNames:
                    description: >-
                      ResourceNames is an optional white list of names that the
                      rule applies to.  An empty set means that everything is
                      allowed.
                    type: array
                    items:
                      type: string
                  resources:
                    description: >-
                      Resources is a list of resources this rule applies to. 
                      ResourceAll represents all resources.
                    type: array
                    items:
                      type: string
                  verbs:
                    description: >-
                      Verbs is a list of Verbs that apply to ALL the
                      ResourceKinds and AttributeRestrictions contained in this
                      rule.  VerbAll represents all kinds.
                    type: array
                    items:
                      type: string
      subresources: {}
      additionalPrinterColumns:
        - name: Workspace
          type: string
          jsonPath: .metadata.labels.kubesphere\.io/workspace
        - name: Alias
          type: string
          jsonPath: .metadata.annotations.kubesphere\.io/alias-name
  conversion:
    strategy: None
  preserveUnknownFields: true
```
