### ISSUE TITLE
What permissions to give a cluster role in able to see metrics.

### ISSUE THREAD

**Issue by ryanpeach** [lensapp/lens#3698]
**Describe the bug**
I have a production cluster running a prometheus server already but when I create a cluster role to put view-only users on my team in (very restrictive), metrics are not visible.

What permissions are needed for this?

My current Cluster Role

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view-only
rules:
- apiGroups:
    - "*"
  resources:
    - bindings
    - componentstatuses
    - configmaps
    - endpoints
    - events
    - limitranges
    - namespaces
    - nodes
    - nodes/metrics
    - persistentvolumeclaims
    - persistentvolumes
    - pods
    - pods/logs
    - podtemplates
    - replicationcontrollers
    - resourcequotas
    - serviceaccounts
    - services
    - mutatingwebhookconfigurations
    - validatingwebhookconfigurations
    - customresourcedefinitions
    - apiservices
    - aplogconfs
    - appolicies
    - apusersigs
    - controllerrevisions
    - daemonsets
    - deployments
    - replicasets
    - statefulsets
    - tokenreviews
    - localsubjectaccessreviews
    - selfsubjectaccessreviews
    - selfsubjectrulesreviews
    - subjectaccessreviews
    - horizontalpodautoscalers
    - cronjobs
    - jobs
    - certificatesigningrequests
    - leases
    - eniconfigs
    - endpointslices
    - targetgroupbindings
    - events
    - ingresses
    - globalconfigurations
    - policies
    - transportservers
    - virtualserverroutes
    - virtualservers
    - alertmanagerconfigs
    - alertmanagers
    - podmonitors
    - probes
    - prometheuses
    - prometheusrules
    - servicemonitors
    - thanosrulers
    - ingressclasses
    - ingresses
    - networkpolicies
    - runtimeclasses
    - poddisruptionbudgets
    - podsecuritypolicies
    - clusterrolebindings
    - clusterroles
    - rolebindings
    - roles
    - priorityclasses
    - csidrivers
    - csinodes
    - storageclasses
    - volumeattachments
    - securitygrouppolicies
  verbs:
   - get
   - watch
   - list
```

**Comment by cbluth** [comment]
I am having a similar scenario:
- multiple teams on one cluster
- each team gets a single namespace
- each team gets a single Role and RoleBinding in their namespace
- no clusterroles are binded to the team members, yet

what else can i give them so that they can see the metrics in lens?

**Comment by jim-docker** [comment]
Can you try adding these resources as well?

```
      - services/proxy
      - services/portforward
```
(portforward only if you need this feature)

**Comment by ryanpeach** [comment]
We have actually decided to go to a many-cluster development environment instead so I no longer have the time to debug this, as it's not relevant anymore, but I believe it's worth keeping up for someone to answer for the internet.

**Comment by jim-docker** [comment]
@cbluth Did you get this working?

**Comment by cbluth** [comment]
@jim-docker 

yeah, here is the template im using, apply it to the lens-metrics namespaces:
```
# role
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: lens-metrics
  name: read-only-lens-metrics
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - pods
  - events
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - "services/proxy"
  verbs:
  - create

# role binding
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
  namespace: lens-metrics
  name: vendor-read-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-only-lens-metrics
subjects:
- kind: Group
  name: ${SOMEGROUP1}
  apiGroup: rbac.authorization.k8s.io
- kind: Group
  name: ${SOMEGROUP2}
  apiGroup: rbac.authorization.k8s.io
```
