### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by vovtz** [lensapp/lens#3739]
**Describe the bug**
Kept it running over the weekend. When returning to it an ‘App crash’ was displayed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Leave it running
2. Return to it after a few days

**Expected behaviour**
No errors displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/1536228/132192642-b421b87c-ecfb-4894-a48f-c72389dbed07.png).

**Environment (please complete the following information):**
- Lens Version: 4.2.4
- OS: macOS 10.15.7
- Installation method (e.g. snap or AppImage in Linux): downloaded

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
N/A
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <secret>
    server: https://kubernetes.docker.internal:6443
  name: docker-desktop
- cluster:
    certificate-authority-data: <secret>
    server: https://172.19.233.2:6443
  name: <fqdn-secret>
- cluster:
    certificate-authority-data: <secret>
    server: https://172.21.9.9:6443
  name: <fqdn-secret>
- cluster:
    certificate-authority: /Users/vovtz/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Mon, 06 Sep 2021 11:13:42 CEST
        provider: minikube.sigs.k8s.io
        version: v1.23.0
      name: cluster_info
    server: https://192.168.64.3:8443
  name: minikube
contexts:
- context:
    cluster: <fqdn-secret>
    namespace: kafka-perf-test
    user: rigid-view
  name: degiro-production
- context:
    cluster: <fqdn-secret>
    namespace: default
    user: rigid-admin
  name: degiro-test
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Mon, 06 Sep 2021 11:13:42 CEST
        provider: minikube.sigs.k8s.io
        version: v1.23.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: <secret>
    client-key-data: <secret>
- name: minikube
  user:
    client-certificate: /Users/vovtz/.minikube/profiles/minikube/client.crt
    client-key: /Users/vovtz/.minikube/profiles/minikube/client.key
- name: rigid-admin
  user:
    token: <secret>
- name: rigid-view
  user:
    token: <secret>
```

**Additional context**
App crash at http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/pods?lens-namespaces=rigid

```
Component stack:


    at KD (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:8296788)
    at div
    at tF (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:8302823)
    at div
    at div
    at cF (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:8308806)
    at footer
    at div
    at pU (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:8514060)
    at cc (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:7683374)
    at t (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:223994)
    at BU (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:8515564)
```

```
Error stack:

 
TypeError: Cannot read property 'showTimestamps' of undefined
    at KD.get logs (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:8299041)
    at ce (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:12079)
    at e.computeValue (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:18380)
    at e.trackAndCompute (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:18206)
    at e.get (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:17257)
    at e.read (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:51873)
    at KD.get (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:53326)
    at KD.render (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:8299148)
    at Ce (http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:13973)
    at http://535860d3-2ac3-4a3e-b10e-97b247bb3186.localhost:53604/build/Lens.js:2:7558683
```
