### ISSUE TITLE
Connecting to cluster through ssh tunnel on localhost

### ISSUE THREAD

**Issue by Skycelot** [lensapp/lens#388]
**Describe the bug**
My master node is behind a router and I can't connect to it directly from my computer.
I can though connect through ssh to the host that sees the master node and make a tunnel from the master node to my local port. But when I try to connect through that tunneled port I get a message, that certificate was given for dedicated IPs and 127.0.0.1 is not among them. The same message is shown when I try to use kubectl directly from command line. But there is a kubectl flag "insecure-skip-tls-verify" that allows me to connect to my master through the tunneled port on localhost. If I check a property "Allow untrusted Certificate Authorities" in Lens that doesn't help me. Can you add a possibility to use kubectl flag "insecure-skip-tls-verify" into Lens?

**To Reproduce**
1. Create ssh tunnel L6443:192.168.2.20:6443
2. Add a new cluster in Lens with address https://127.0.0.1:6443
3. See connection error

**Expected behavior**
Successfull connection with insecure-skip-tls-verify option

**Screenshots**
![Lens](https://user-images.githubusercontent.com/3769680/82840071-014b6980-9eda-11ea-8972-42f5cee4e001.png)
![kubectl](https://user-images.githubusercontent.com/3769680/82840070-001a3c80-9eda-11ea-87dd-705b6d99a799.png)

**Environment (please complete the following information):**
- Lens Version: 3.4.0
- OS: Windows
 
**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://127.0.0.1:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
```

**Comment by jnummelin** [comment]
@Skycelot did you try by adding `insecure-skip-tls-verify: true` option to your kubeconfig too under `- cluster`?

**Comment by xeago** [comment]
Alternatively, use [sshuttle](https://github.com/sshuttle/sshuttle) as a poor-man's vpn.

**Comment by mudged** [comment]
I'm seeing a similar issue. I can only access my cluster by ssh'ing and port forwarding with an intermediary server.
I can connect when using kubectl as I use the `tls-server-name` property. But when I connect via LENS (3.5.3 Ubuntu) I see the message:
`http: proxy error: x509: certificate is valid for <actual-ip-address>, not 127.0.0.1`

In my .kube/config I have:
```
- cluster:
    certificate-authority-data: <REDACTED>
    server: https://127.0.0.1:16444
    tls-server-name: <actual-ip-address>
  name: mycluster
```

If I remove the tls-server-name property then kubectl stops working with the same error. Which leads me to think LENS isn't using `tls-server-name`. Also adding `insecure-skip-tls-verify: true `has no effect.
