### ISSUE TITLE
Node taints have undefined in the name

### ISSUE THREAD

**Issue by alekc** [lensapp/lens#3987]
**Describe the bug**
Taint reports undefined in the ui (see screenshot)

**To Reproduce**
Given a node with a following spec
```
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
  - 10.244.0.0/24
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
```

open node information from the ui

**Expected behavior**
It should report `node-role.kubernetes.io/master=NoSchedule`

**Screenshots**
![image](https://user-images.githubusercontent.com/302807/136443122-6a23034a-53dc-4dad-98da-e770ffa2ba09.png)

**Environment (please complete the following information):**
- Lens Version: Lens: 5.2.5-latest.20211001.2
- OS: Osx
- Installation method manual
