### ISSUE TITLE
auto-refresh is not working

### ISSUE THREAD

**Issue by Nilegfx** [lensapp/lens#442]
**Describe the bug**
Lens doesn't auto-refresh, I have to refresh manually for (almost all resources/objects)

**To Reproduce**
1. apply any change

**Expected behavior**
the changes appear without manual refresh (CMD+r)

**Environment (please complete the following information):**
- Lens Version:Version: 3.5.0-beta.1
- OS: [e.g. OSX] Catalina 10.15.3 (19D76)
- Installation method (e.g. snap or AppImage in Linux): dmg
 
**Logs:**
not sure how to get the logs, let me know and I'll edit the issue.

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
current-context: xxx-cluster
preferences: {}
clusters:
  - cluster:
      certificate-authority-data: xxxx
      server: https://xxx.xxx.xxx.xx:xxxx
    name: xxx-cluster
contexts:
  - name: xxx-cluster
    context:
      cluster: xxx-cluster
      user: kubernetes-admin
users:
  - name: xxx-user
    user:
      username: xxx
      password: xxx
  - name: kubernetes-admin
    user:
      client-certificate-data: xxx
      client-key-data: xx
```

**Additional context**
Lens was working fine until I introduced a new cluster, only then it stopped refreshing.

I tried to uninstall and reinstall it again, still do not work
