### ISSUE TITLE
Failed to connect to "xxxx": StatusCodeError: 502

### ISSUE THREAD

**Issue by nieaowei** [lensapp/lens#4678]
**Describe the bug**
info: [CLUSTER]: refresh {"id":"925c7c694cf5814be73fce100af8f913","name":"nieaowei","ready":false,"online":false,"accessible":false,"disconnected":false}
error: [CLUSTER]: Failed to connect to "xxxx": StatusCodeError: 502 - undefined

**To Reproduce**
Connect to cluster

**Screenshots**
<img width="728" alt="image" src="https://user-images.githubusercontent.com/42961884/149103257-fb979f0e-d238-4151-b009-b91a5be9e16d.png">

**Environment (please complete the following information):**
- Lens Version: 5.3.3-latest.20211223.1
- OS: Macos

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: certs/xxx/k8s-ca.crt
    server: https://xxx.co:8383
  name: shanghai3s
contexts:
- context:
    cluster: shanghai3s
    namespace: default
    user: nieaowei
  name: nieaowei
current-context: nieaowei-agora-hci-shanghai3s
kind: Config
preferences: {}
users:
- name: nieaoweix
  user:
    auth-provider:
      config:
        client-id: shanghai3s
        client-secret: xxxxxx
        id-token: xxxxx
        idp-issuer-url: https://dex.xxx.co
        refresh-token: xxxxx
      name: oidc
```
