### ISSUE TITLE
Deploying Prometheus with Lens reports errors

### ISSUE THREAD

**Issue by bhechinger** [lensapp/lens#48]
**Describe the bug**
I've clicked on the Install button for metrics to have Lens deploy Prometheus. It does seem to be working as I do get metrics data in Lens now, however the StatefulSet for Prometheus is in a constant state of alarm with the following error:

```
create Pod prometheus-0 in StatefulSet prometheus failed error: pods "prometheus-0" is forbidden: error looking up service account lens-metrics/prometheus: serviceaccount "prometheus" not found
```

**To Reproduce**
1. Go to settings
2. Click on Install for Metrics
3. Go to StatefulSets

**Expected behavior**
Prometheus to deploy without errors.

**Environment (please complete the following information):**
- Lens Version: 2.1.2
- OS: Ubuntu Studio 19.10
- Installation method: snap
- Kubernetes Cluster: 1.15.3 Digital Ocean Hosted
 
**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://REDACTED.ondigitalocean.com
  name: do-nyc3-pubserv
contexts:
- context:
    cluster: do-nyc3-pubserv
    user: do-nyc3-pubserv-admin
  name: do-nyc3-pubserv
current-context: do-nyc3-pubserv
kind: Config
preferences: {}
users:
- name: do-nyc3-pubserv-admin
  user:
    token: REDACTED

```
