### ISSUE TITLE
rancher-desktop shown as not connected on windows wsl2

### ISSUE THREAD

**Issue by tobstone** [lensapp/lens#4847]
**Describe the bug**
A startet Rancher-Desktop Instance isnt shown and recognized as conneted on Windows WSL2 although the API is obviously connected. Nodes 

**To Reproduce**
1. Start Rancher Desktop 1.0.1
2. Start Lens 
3.  Rancher Desktiop is recognized as new Cluster in the local kubeconfig
4.  Add Cluster to Hotbar, Doubleklick to Connect
5 , The view shows Pods, the Node etc as expectet but Icon in Hotbar still has Black Dot And Lens Metrics arnt installable

**Expected behavior**
Lens Shows Correct Connection Status

**Screenshots**
![grafik](https://user-images.githubusercontent.com/349584/153449988-5a363201-66c3-4bbb-ba25-4819d7da3704.png)

**Environment (please complete the following information):**
- Lens Version:  5.3.4
- OS: Windows 11 Pro 21H2
- Installation method (e.g. snap or AppImage in Linux): Win Installer

**Kubeconfig:**

```
apiVersion: v1
kind: Config
clusters:
  - name: boringbernd.local
    cluster:
      server: https://boringbernd.dwbn.org:6443
      certificate-authority-data: xxx
      insecure-skip-tls-verify: false
  - name: docker-desktop
    cluster:
      server: https://kubernetes.docker.internal:6443
      certificate-authority-data: xxx
      insecure-skip-tls-verify: false
  - name: rancher-desktop
    cluster:
      server: https://172.22.124.114:6443
      certificate-authority-data: xxx
      insecure-skip-tls-verify: false
users:
  - name: docker-desktop
    user:
      client-certificate-data: xxx
      client-key-data: xxx
  - name: rancher-desktop
    user:
      client-certificate-data: xxx
      client-key-data: xxx
  - name: tobiassteinhoff
    user:
      token: xxx
contexts:
  - name: boringbernd
    context:
      cluster: boringbernd.local
      name: boringbernd
      user: tobiassteinhoff
      namespace: theme-develop
  - name: docker-desktop
    context:
      cluster: docker-desktop
      name: docker-desktop
      user: docker-desktop
      namespace: monitoring
  - name: rancher-desktop
    context:
      cluster: rancher-desktop
      name: rancher-desktop
      user: rancher-desktop
preferences: {}
current-context: rancher-desktop
```
