### ISSUE TITLE
Unable to connect to clusters using aws-iam-authenticator

### ISSUE THREAD

**Issue by dblencowe** [lensapp/lens#49]
**Describe the bug**
The AWS IAM authenticator program generates temporary tokens which are injected in a context in order to provide authentication that's been validated against an active IAM account. In order to support this the users section of the kubeconfig file calls a command (supported by Kubectl). Unfortunately I don't seem to be able to authenticate to these clusters using Lens.

**To Reproduce**
1. Setup EKS based cluster within AWS
2. Follow instructions for setting up local kubectl access
3. Add cluster to Lens
4. See error `Invalid kubeconfig context snip-production: cannot access cluster (snip-production)`

**Expected behavior**
Lens should connect to the cluster by executing the command stored in the config file, just like Kubectl

**Screenshots**
Example config file:
```yaml
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1alpha1
        args:
          - token
          - '-i'
          - production-<snip>
        command: aws-iam-authenticator
        env: null
```

**Environment (please complete the following information):**
- Lens Version: 2.1.3
- OS: OSX 10.14.5
- Installation method (e.g. snap or AppImage in Linux): DMG file
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
No logs produced when running application with `open -W -F -a Lens`

**Kubeconfig:**
See above

**Additional context**
