### ISSUE TITLE
Metric: Don't use hostPath-volumes with path "/"

### ISSUE THREAD

**Issue by sebschlue** [lensapp/lens#501]
In my test environment consisting of three nodes running k3s 1.18.3 on top of CentOS 7.8 having Pods use something like

````
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
````

causes severe problems at all Pods being stuck in state "Terminating" forever due to "device or resource busy" errors.

This has been discussed in other projects as well, for instance, there have been similar tickets at rook-ceph project, where this has been fixed since then.
