### ISSUE TITLE
Error: unknown command "oidc-login" for "kubectl"

### ISSUE THREAD

**Issue by Keithsc** [lensapp/lens#534]
**Describe the bug**
My kubeconfig file works when using kubectl and the krew installed oidc_login plugin but doesn't work for Lens and when i paste in my config into Lense and press the "Add Cluster" button I get the error Error: unknown command "oidc-login" for "kubectl". 

**To Reproduce**
Open Lens and load my kubeconfig and the error appears

**Expected behavior**
I think my browser should open and I should be able to authenticate through the browser. So I just enter my login details and if they are correct I get a OK message in the browser and I expect lens to then be able to connect to the cluster

**Environment (please complete the following information):**
- Lens Version: 3.5.0
- OS: Ubuntu 20.04 LTS
- Installation method (e.g. snap or AppImage in Linux): snap
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
Connecting ...
Error: unknown command "oidc-login" for "kubectl"
Run 'kubectl --help' for usage.
2020/06/26 12:39:40 http: proxy error: getting credentials: exec: exit status 1
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config

clusters:
- name: mycluster-cluster
  cluster:
    server: https://mycluster.com:6443
    certificate-authority-data: LS089eutj980w5j7t4........
contexts:
- context:
    cluster: mycluster-cluster
    user: oidc
  name: mycluster-context
current-context: mycluster-context

preferences: {}

users:
- name: oidc
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://auth.mydomain.com/auth/realms/MYREALM
      - --oidc-client-id=kubernetes
      - --oidc-client-secret=                                    
      command: kubectl
      env: null

```

**Additional context**
I am not sure if it mater but my Desktop OS is Ubuntu Mate and I am using Lens 3.5.0 what was installed as a snap.
