### ISSUE TITLE
OIDC does not work with custom CA

### ISSUE THREAD

**Issue by jakolehm** [lensapp/lens#59]
**Describe the bug**
OIDC authentication does not work if `idp-issuer-url` uses custom CA.

**Logs:**

```
Invalid kubeconfig context test-cluster
AggregateError: RequestError: unable to verify the first certificate at ClientRequest.<anonymous> (/Applications/Lens.app/Contents/Resources/app.asar/node_modules/got/index.js:182:22) RequestError: unable to verify the first certificate at ClientRequest.<anonymous>
```

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://ucp:6443
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: me
  name: test-cluster
current-context: test-cluster
kind: Config
preferences: {}
users:
- name: me
  user:
    auth-provider:
      config:
        client-id: oidc
        client-secret: REDACTED
        id-token: REDACTED
        idp-issuer-url: https://ucp:32000
        refresh-token: REDACTED
      name: oidc
```

**Additional context**
This is probably a bug with ts/js kubernetes client library.
