### ISSUE TITLE
TypeError: Cannot read property 'objectConstructor' of undefined with pdb

### ISSUE THREAD

**Issue by matti** [lensapp/lens#605]
```
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: pot
  namespace: default
spec:
  minAvailable: 100%
  selector:
    matchLabels:
      app: pot
```

^-- "create resource" with this.
