### ISSUE TITLE
Allow to update environment variables on a cluster configuration

### ISSUE THREAD

**Issue by marcofranssen** [lensapp/lens#631]
When using aws mfa, from my commandline I get a token which is valid for a limited amount of time.

Using an exec login method (`aws` cli) I am able to connect. However after the token expires I will have to update this environment variable.

As far I can see there is no way to configure this.

**Comment by nevalla** [comment]
Do you need to update environment variable manually or does aws cli update that? How about if you are using `kubectl` does that require anything extra steps when token expires? https://github.com/lensapp/lens/pull/466 potentially fixes this, but just want to understand the issue better.

**Comment by marcofranssen** [comment]
I'm using this set of bash functions to authenticate my terminal using mfa. https://github.com/marcofranssen/aws-auth

This will export the following variables in my current terminal.

```bash
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export AWS_SESSION_TOKEN
```

This way I never have to store these in plain text somewhere.

What I currently do is generate a kubeconfig from terraform. I open this config in Lens and then append these 3 environment variables manually to the generated config for Lens to be able to use them.

Now my AWS_TOKEN will expire in 12 hours. Currently I will then have to repeat those steps and add a new cluster and remove the old one.

I think it would be very useful if environment variables could be configured or set on the fly.

From `kubectl` I don't have this issue as the terminal where I'm running this command is authenticated using `aws-auth-mfa-login my-account 123456`, which exports those 3 vars on success.

**Comment by jakolehm** [comment]
@marcofranssen does it work if you first run `aws-auth-mfa-login my-account 123456` and then start lens from the same terminal window?

**Comment by marcofranssen** [comment]
It works if I append the values manually to my generated kubeconfig when importing/adding the cluster using a custom kubeconfig as following to the exec section.

```yaml
users:
- name: arn:aws:eks:eu-west-1:759729069112:cluster/my-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - my-cluster
      - --role
      - arn:aws:iam::759729069112:role/MyRole
      command: aws
      env:
      - name: AWS_ACCESS_KEY_ID
        value: my-key-id
      - name: AWS_SECRET_ACCESS_KEY
        value: my-key-secret
      - name: AWS_SESSION_TOKEN
        value: my-token
```

However after 12 hours I would have to remove the cluster and add it again.

So that means I copy my generated kubeconfig and then manually add the following.

```yaml
      env:
      - name: AWS_ACCESS_KEY_ID
        value: my-key-id
      - name: AWS_SECRET_ACCESS_KEY
        value: my-key-secret
      - name: AWS_SESSION_TOKEN
        value: my-token
```
