### ISSUE TITLE
An extra Powershell window pops when the `Shell` clicked.

### ISSUE THREAD

**Issue by Adj325** [lensapp/lens#638]
**Describe the bug**
I can't get in container. Powershell pops when the `Shell` clicked. The command like 'kubectl --kubeconfig config exec' doesn't execute. 

**To Reproduce**
1. Go to 'Pods'
2. Choose any pod
3. Click on 'Shell'
4. Powershell pops 

**Expected behavior**
Powershell doesn't pop and I get in container.

**Screenshots**
![image](https://user-images.githubusercontent.com/28868224/89279984-9b6a2380-d67a-11ea-89fb-40909efd4941.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.1
- OS: Windows 10.0.18363.959 pro
- Installation method (e.g. snap or AppImage in Linux):  install by exe files
 
**Logs:**
![image](https://user-images.githubusercontent.com/28868224/89280330-0f0c3080-d67b-11ea-95e3-bd3d17e1c4fc.png)

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: certificate-authority-data
    server: https://server
  name: kubernetes-admin-name
contexts:
- context:
    cluster: kubernetes-admin-name
    namespace: namespace
    user: user
  name: name
current-context: admin-context
kind: Config
preferences: {}
users:
- name: name
  user:
    token: token
```
