### ISSUE TITLE
OIDC login is not being re-imported after tokens expire

### ISSUE THREAD

**Issue by starkers** [lensapp/lens#649]
**Describe the bug**
We log into our clusters via OIDC + dex. After adding our cluster in lens everything seems OK. However eventually that token expires.. So the next day, after that token expired we get:

```
Connecting ...
2020/08/06 09:02:38 http: proxy error: failed to refresh token: oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_request","error_description":"Refresh token is invalid or has already been claimed by another client."}
```
This is **after** the user has refreshed their token and pulled a new one into their KUBECONFIG.

I'm using a version of this to update the KUBECONFIG: https://github.com/pusher/k8s-auth-example

**Expected behavior**
When we "add a server" in Lens it appears to import settings from the KUBECONFIG, ideally it should examine the token's refresh time, if it has expired then it would be great if it tried re-imported the settings from KUBECONFIG (or just prompted users to re-auth?)

**Screenshot**
![image](https://user-images.githubusercontent.com/462087/89507674-bea0ea00-d7c4-11ea-9b11-823bdc7cafc4.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.2
- OS: Linux
- Installation method: AppImage
 
**Logs:**
```
error: Failed to connect to cluster main.eu-staging: {"name":"StatusCodeError","statusCode":502,"message":"502 - \"Refresh token is invalid or has already been claimed by another client.\"","error":"Refresh token is invalid or has already been claimed by another client.","options":{"json":true,"timeout":10000,"headers":{"host":"9482819f-0a1f-4fed-9d0c-6bb4baf94ae4.localhost:46251"},"uri":"http://127.0.0.1:46251/api-kube/version","simple":true,"resolveWithFullResponse":false,"transform2xxOnly":false},"response":{"statusCode":502,"body":"Refresh token is invalid or has already been claimed by another client.","headers":{"content-type":"text/plain","date":"Thu, 06 Aug 2020 07:57:38 GMT","connection":"close","transfer-encoding":"chunked"},"request":{"uri":{"protocol":"http:","slashes":true,"auth":null,"host":"127.0.0.1:46251","port":"46251","hostname":"127.0.0.1","hash":null,"search":null,"query":null,"pathname":"/api-kube/version","path":"/api-kube/version","href":"http://127.0.0.1:46251/api-kube/version"},"method":"GET","headers":{"host":"9482819f-0a1f-4fed-9d0c-6bb4baf94ae4.localhost:46251","accept":"application/json"}}}}

```

**Kubeconfig:**

Kubeconfig's look like this (but with more servers typically).. 

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: https://api.main.eu-staging.acmecorp.org
  name: main.eu-staging
contexts:
- context:
    cluster: main.eu-staging
    namespace: default
    user: david@acmecorp.org
  name: main.eu-staging
current-context: main.eu-staging
kind: Config
preferences: {}
users:
- name: david@acmecorp.org
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: REDACTED
        id-token: REDACTED
        idp-issuer-url: https://dex.acmecorp.org
        refresh-token: REDACTED
      name: oidc

```
