### ISSUE TITLE
Renew token for kubeconfig does not work

### ISSUE THREAD

**Issue by rreinurm** [lensapp/lens#65]
**Describe the bug**
kubectl config uses JWT Bearer token for user authentication which works well initially. After token expiration the import of new token does not apply and only way to reuse tool is to remove the cluster and import new config with updated token.

**To Reproduce**
1. Create new cluster with following config
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <cert-place-holder-in-base64>
    server: https://some-server.addess:6443
  name: k8s-cluster
contexts:
- context:
    namespace: default
    cluster: k8s-cluster
    user: <example-user>
  name: k8s-context
users:
- name: <example-user>
  user:
    token: <jwt-token-here>
current-context: k8s-context
```
2. After token expires (for JWT token usually 1h) the Lens provide new token input form
3. Insert new input token and nothing happens, nothing appears in log either then Lens is started from command line

**Expected behavior**
Update Lens config with new Token and authenticate to K8s cluster.

**Environment (please complete the following information):**
- Lens Version: 2.4
- OS: OSX 10.15.1
