### ISSUE TITLE
Not Able To Connect To Cluster 

### ISSUE THREAD

**Issue by brianpham** [lensapp/lens#653]
**Describe the bug**
Lens was working for me for awhile until I deleted everything and started over. Not sure why it is stuck with the Connecting... message. I am able to run kubectl get pods and other kubectl commands

**To Reproduce**

**Expected behavior**
Should be able to connect or better error message

**Screenshots**

<img width="362" alt="Screen Shot 2020-08-06 at 3 30 28 PM" src="https://user-images.githubusercontent.com/5695495/89589278-30475b00-d7fa-11ea-8373-3ebdea552a71.png">

<img width="292" alt="Screen Shot 2020-08-06 at 3 31 24 PM" src="https://user-images.githubusercontent.com/5695495/89589277-2f162e00-d7fa-11ea-82ad-a8319c24dd2d.png">

**Environment (please complete the following information):**
- Lens Version: 3.5.2
- OS: 10.15.6 (19G73)
- Installation method (e.g. snap or AppImage in Linux): Mac OS 

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    server: https://xxxxxx.sk.us-east-1.eks.amazonaws.com
    certificate-authority-data: xxxxx
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "terraform-eks-demo"
```
