### ISSUE TITLE
OIDC does not work with custom CA

### ISSUE THREAD

**Issue by djgilcrease** [lensapp/lens#66]
**Describe the bug**
OIDC authentication does not work if idp-issuer-url uses custom CA. https://github.com/kontena/lens/issues/59

**Screenshots**
![image](https://user-images.githubusercontent.com/1778574/68147917-e985a700-feef-11e9-808e-90caa1ae20cf.png)

**Environment (please complete the following information):**
- Lens Version: v2.4.1
- OS: linux
- AppImage 
 
**Logs:**
```
error: Failed to connect to cluster test-cluster: {"name":"AggregateError"}
RequestError: unable to verify the first certificate at ClientRequest.<anonymous> (/tmp/.mount_Lens-2kYjkXc/resources/app.asar/node_modules/got/index.js:182:22)
```

**Kubeconfig:**
```
apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority-data: ...
    server: https://testcluster-api.company.local:443
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: gilcrease
  name: test-cluster
- name: gilcrease
  user:
    auth-provider:
      config:
        client-id: loginapp
        client-secret: ...
        id-token: ...
        idp-issuer-url: https://dex.company.local/dex
        refresh-token: ...
      name: oidc
```
