### ISSUE TITLE
Fails to connect to PKS cluster

### ISSUE THREAD

**Issue by webmutation** [lensapp/lens#689]
When trying to connect to a PKS cluster using the kubeconfig in the system it always fails. This issue existed before but was solved about 9 months ago... but I cannot find it anymore on kontena issue tracker.

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [cert-redacted]
    server: https://server:8443
  name: k8s-dev
contexts:
- context:
    cluster: k8s-dev
    namespace: dev
    user: webmutation
  name: dev
current-context: k8s-dev
kind: Config
preferences: {}
users:
- name: webmutation
  user:
    auth-provider:
      config:
        client-id: pks_cluster_client
        client-secret: ""
        id-token: [token-redacted]
        idp-certificate-authority-data: [certificate-redacted]
        idp-issuer-url: https://server:8443/oauth/token
        refresh-token: [eyJhbG...redacted]
      name: oidc
```
There is no error it just fails to connect... is there a way to get a more verbose message? Or any clue on how to fix the issue? 
I remember that 9 monts ago it was related to OpenID handling. My current configuration works fine for VS Code Kubernetes plugin for example, but in Lens it keeps failing to connect. 

Currently we use PKS cli to get the kubeconfig, the message about kubelogin is not very clear.
