### ISSUE TITLE
ResourceQuota displayed wrong for kilo-suffix notation

### ISSUE THREAD

**Issue by gudzenkov** [lensapp/lens#705]
**Describe the bug**
ResourceQuota values set in kilo-suffix are treated like simple numbers

**To Reproduce**
1. Set ResourceQuota with `k`-suffix
```
kind: ResourceQuota
apiVersion: v1
metadata:
  name: gke-resource-quotas
  namespace: default
spec:
  hard:
    count/ingresses.extensions: 100k
    count/jobs.batch: 50k
    pods: 15k
    services: 5000
```
2. Go to Namespaces -> `default` -> `gke-resource-quotas`
3. Watch progress-bar `1016 / 15k` and over-float status telling `Set: 15k. Used 6700%`

**Expected behavior**
1. Progress-bar and status should indicate `6.7%`

**Screenshots**
<img width="654" alt="Lens ResourceQuota bug" src="https://user-images.githubusercontent.com/11720732/90522922-f751a380-e174-11ea-9aa7-bbf73069cc87.png">

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: MacOS Catalina 10.15.5 (19F101)
- Installation method (e.g. snap or AppImage in Linux): 
```
❯ brew cask install lens
==> Downloading https://github.com/lensapp/lens/releases/download/v3.5.3/Lens-3.5.3.dmg
```
