### ISSUE TITLE
Spinner replaces cluster overview metrics when user is RBAC restricted

### ISSUE THREAD

**Issue by jim-docker** [lensapp/lens#7385]
**Describe the bug**
For a user restricted to reading pods and nodes the cluster metrics are briefly shown, then replaced with the spinner. Some logic is deciding there are no metrics to show. Metrics on the nodes list, nodes details and pods details work fine.

https://user-images.githubusercontent.com/40840436/226474130-0a42a9de-7b7f-4cda-92f7-7c9f6d9c331c.mov

This occurs here for Lens built-in metrics on LDK, which otherwise (i.e. no RBAC restrictions) work fine. Ubuntu 20.04, though that probably doesn't matter.

The following are the resources applied (to a service account):

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - nodes
    verbs:
      - get
      - list
      - watch
```

```
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-read-only
subjects:
- kind: ServiceAccount
  name: developer-reader
  namespace: default
roleRef:
  kind: ClusterRole
  name: read-pods
  apiGroup: rbac.authorization.k8s.io
```

This also requires RBAC permissions for such a limited user to see the `lens-metrics`:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: lens-metrics
  name: read-only-lens-metrics
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - pods
  - events
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - "services/proxy"
  verbs:
  - create
```

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
  namespace: lens-metrics
  name: read-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-only-lens-metrics
subjects:
- kind: ServiceAccount
  name: developer-reader
  namespace: default
```
