### ISSUE TITLE
lens can't connecting  k8s,

### ISSUE THREAD

**Issue by goodking-bq** [lensapp/lens#750]
**Describe the bug**
when click connect,screen show 
```
Connecting ...
Authentication proxy started
```
kubectl command seem all right. 
```
kubectl get pod -n default
NAME                                      READY   STATUS             RESTARTS   AGE
busybox-48wpt                             1/1     Running            140        48d
busybox-gffmv                             1/1     Running            140        48d
busybox-sdrn9                             1/1     Running            140        48d
nfs-client-provisioner-5f6b6c589c-t2tcf   1/1     Running            1          97d
traefik-69fr2                             1/1     Running            0          27d
zabbix-1598336566-0                       2/2     Running            0          44h
zabbix-1598336566-postgresql-0            1/1     Running            0          44h
zabbix-web-89dfd9d8d-2nncp                0/1     CrashLoopBackOff   753        44h
```
**To Reproduce**
1. Go to 'home'
2. Click on 'cluster  ' left

**Expected behavior**

**Screenshots**
![1598496754794](https://user-images.githubusercontent.com/7803202/91378665-95b7c600-e853-11ea-9eba-28d9bb84ede0.jpg)

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: macos 10.15.6
 
**Logs:**
where can i find lens log ?? 
```
i can't find logs 
```

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/golden/.minikube/ca.crt
    server: https://192.168.64.4:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/golden/.minikube/profiles/minikube/client.crt
    client-key: /Users/golden/.minikube/profiles/minikube/client.key
```

**Additional context**
