### ISSUE TITLE
The Application does not display any data or information

### ISSUE THREAD

**Issue by leomongeg** [lensapp/lens#78]
**Describe the bug**
The application does not display any data or information of the Cluster, and there is no error message.

<img width="1680" alt="Screen Shot 2019-11-13 at 2 25 32 PM" src="https://user-images.githubusercontent.com/10834425/68801910-96fc6700-0622-11ea-9595-9b37175974ee.png">
<img width="1669" alt="Screen Shot 2019-11-13 at 2 26 35 PM" src="https://user-images.githubusercontent.com/10834425/68801919-99f75780-0622-11ea-8c6a-71e2c3f55531.png">

**Expected behavior**
The application should display all the cluster information, nodes, pods, services, deployments, etc

**Environment (please complete the following information):**
- Lens Version: 2.5.1
- OS: OSX Mojave
 

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: long alphanumeric value
    server: https://long-alphanumeric-value.k8s.ondigitalocean.com
  name: do-sfo2-k8s-mycluster-dev-cluster
contexts:
- context:
    cluster: do-sfo2-k8s-mycluster-dev-cluster
    user: do-sfo2-k8s-mycluster-dev-cluster-admin
  name: do-sfo2-k8s-mycluster-dev-cluster
current-context: do-sfo2-k8s-mycluster-dev-cluster
kind: Config
preferences: {}
users:
- name: do-sfo2-k8s-mycluster-dev-cluster-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - long-alphanumeric-value
      command: doctl
      env: null
```
