### ISSUE TITLE
Question: What are the minimum Roles required to display metrics graphs with service accounts?

### ISSUE THREAD

**Issue by k-jiang** [lensapp/lens#787]
For security reason, I created some service accounts for others to access different part of the network. I use Lens as a GUI interface and installed "Metrics" through Settings. I can see all the metrics graphs (pod cpu / ram usage etc) when login with the master account (default account).

However I see no graphs but message says "Metrics not available at the moment" when I login with a newly create service account (with ["edit" Role](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles) binded on some namespace).

Currently I can only make the metrics graphs show up if I bind an "edit" Role with "lens-metrics" namespace to those service accounts. But it also means that those accounts could potentially alternate the underlying metric services like prometheus etc.

I don't want my other users messing around with the metrics services, thus could you tell me if it is possible to just create a specific Role that only grants sufficient permissions?

Sorry I don' t know too much about TypeScript. But I can write a Role/ClusterRole config file if I know how exactly the Lens obtains those metrics data. Is it through pods port-forwarding or endpoints? from which service? What API or kubectl commands are being used? I will post the yaml file here once I finished it.

**Environment you are Lens application on:**

- Kubernetes distribution: Rancher k3s, with 1 master and 1 worker nodes
- Desktop OS: Ubuntu 20.04 (Gnome)

Thank you!

**Comment by nevalla** [comment]
https://github.com/lensapp/lens/pull/644 adds `ClusterRole`, is that something you could use too?

**Comment by k-jiang** [comment]
> #644 adds `ClusterRole`, is that something you could use too?

Yes exactly! Thank you so much!

For any of you who have the same issue, you can use my ClusterRole.yml here which is based on the PR:
```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lens-read-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - services/proxy
    verbs:
      - get
      - list
      - watch
```

You can bind this ClusterRole with your newly created service accounts with:
```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lens-read-metrics
  namespace: lens-metrics # this is the namespace where Lens creates its metrics services by default
subjects:
  - kind: ServiceAccount
    name: <put your account name here>
    namespace: <your service account namespace>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lens-read-metrics
```

Now your graphs should show up again :)

**Comment by celvin** [comment]
didn't work, I still getting " Metrics not available at the moment"

**Comment by vasyakrg** [comment]
10x. worked!

**Comment by automationjunky** [comment]
> didn't work, I still getting " Metrics not available at the moment"

I had to target `services` in addition to `services/proxy` in my `ClusterRole`, like so:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lens-read-metrics
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - services/proxy
    verbs:
      - get
      - list
      - watch
```

**Comment by marcbachmann** [comment]
> I had to target services in addition to services/proxy in my ClusterRole, like so:

Somehow that still didn't work for me.
I've used this configuration to restrict it to the monitoring namespace:
```yaml
---
# Provides the required permissions for readonly users
# to get metrics working in lens
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: port-forward-lens
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["pods/portforward", "services/proxy"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: port-forward-lens-binding
  namespace: monitoring
subjects:
  - kind: User
    name: someusername
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: port-forward-lens
  apiGroup: rbac.authorization.k8s.io
```
