### ISSUE TITLE
Opening pod shell results in error: unable to upgrade connection: Misdirected Request

### ISSUE THREAD

**Issue by kenlasko** [lensapp/lens#7912]
**Describe the bug**
When connecting to a cluster using token-based authentication, I am unable to open a pod shell.  I get the following error message:
error: unable to upgrade connection: Misdirected Request

Everything else appears to function fine.

The exact same kubectl exec command works fine from command line using the same kubeconfig.

I do not have any issues when connecting using the host-generated kubeconfig file from my K3S master nodes

**To Reproduce**
1. Configure Lens to use a cluster with token-based auth
2. Go to Workloads - Pods
3. Click on a pod
4. Open a pod shell
5. See error

**Expected behavior**
I expect that the pod shell opens without error

**Environment (please complete the following information):**
- Lens Version: 2023.8.231521-latest
- OS: Windows 11
- Installation method (e.g. snap or AppImage in Linux): Windows installer

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info: [SHELL-SESSION]: PTY for f191957afe720b4fbb89316d349db7a1:d9e0387a-93b8-4634-92a2-31ec4aa96c7b is started with PID=30440
error: W0828 12:42:56.979390   14360 dial.go:72] using custom dialer with no TLSClientConfig. Defaulting to InsecureSkipVerify
 {"meta":{"accessible":true,"disconnected":false,"id":"f191957afe720b4fbb89316d349db7a1","name":"Home K3S","online":true,"ready":true}}
info: [CLUSTER]: refresh {"accessible":true,"disconnected":false,"id":"f191957afe720b4fbb89316d349db7a1","name":"Home K3S","online":true,"ready":true}
```

**Non-working Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    server: https://cloud.mydomain.com
  name: cloud
- cluster:
    server: https://home.mydomain.com
  name: home
contexts:
- context:
    cluster: cloud
    user: cloud-user
  name: cloud
- context:
    cluster: home
    user: home-user
  name: home
current-context: home
kind: Config
preferences:
  colors: true
users:
- name: cloud-user
  user:
    token: mysuperlongtoken
- name: home-user
  user:
    token: mysuperlongtoken
```

**Working Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: _CACertString_
    server: https://10.x.x.x:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    client-certificate-data: _ClientCertString_
    client-key-data: _ClientKeyString_
```

**ClusterRole:**
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-cluster-role
  namespace: default
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
```
