### ISSUE TITLE
OpenLens does not work from launcher, however it works from the installed path.

### ISSUE THREAD

**Issue by Abdullah-Elkasaby** [lensapp/lens#7921]
**Describe the bug**

I installed OpenLens using homebrew on a Mac M1 Pro,  but it does not connect when opened from /Applications/OpenLens.app, however when opened from the terminal through this path "/opt/homebrew/Caskroom/openlens/6.5.2-366/OpenLens.app/Contents/MacOS/OpenLens", it works fine 
**To Reproduce**
1. install OpenLens thorugh homebrew using ´brew install openelns´
2. after having aws and kubectl configured and working fine
3. open Applications and click on OpenLens app to open 

**Expected behavior**
The application should work fine from the launcher but it does not 

**Screenshots**
Opened from the launcher 
<img width="1552" alt="Screenshot 2023-09-04 at 11 31 52 AM" src="https://github.com/lensapp/lens/assets/97049761/8d7c9a0f-3c47-47b8-a8af-231aa5b2b0f4">

Opened from terminal through `/opt/homebrew/Caskroom/openlens/6.5.2-366/OpenLens.app/Contents/MacOS/OpenLens`

<img width="1442" alt="Screenshot 2023-09-04 at 11 34 18 AM" src="https://github.com/lensapp/lens/assets/97049761/27f0c039-4a69-4b68-adb3-024832a0ed9e">

**Environment (please complete the following information):**
- Lens Version: 6.5.2
- OS: [e.g. OSX] MacOS 13.5.1 (22G90)
- Installation method (e.g. snap or AppImage in Linux): homebrew

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
E0904 11:37:15.384216 4992 proxy_server.go:147] Error while proxying request: getting credentials: exec: executable aws not found

It looks like you are trying to use a client-go credential plugin that is not installed.

To learn more about this feature, consult the documentation available at:
https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins

Failed to get /version for clusterId=: Internal Server Error
```

**Kubeconfig:**

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: 
contexts:
- context:
    cluster: 
    user: 
  name: 
current-context: 
kind: Config
preferences: {}
users:
- name: 
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - 
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: saml

```
