### ISSUE TITLE
openlens 6.5.2-366 on macos can not view workload like pod,node and config

### ISSUE THREAD

**Issue by KaimingWan** [lensapp/lens#7932]
**Describe the bug**
When start openlens I can't see workload of eks. I test another k3s kube config file and it works well. I use Apple M1 Pro and os is Ventura 13.0
<img width="1401" alt="image" src="https://github.com/lensapp/lens/assets/4374015/17fa0230-65ce-4c11-90db-9a19b93ea7e3">

My kube file is 
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: mock...
    server: https://EB2048EB3A42A65220F85CC74FDAF8FC.gr7.cn-northwest-1.eks.amazonaws.com.cn
  name: arn:aws-cn:eks:cn-northwest-1:12345:cluster/amq-stack-k8s-cluster-cn-northwest-1-env-yglrthcymngsbsyjl2jt
contexts:
- context:
    cluster: arn:aws-cn:eks:cn-northwest-1:12345:cluster/amq-stack-k8s-cluster-cn-northwest-1-env-yglrthcymngsbsyjl2jt
    user: arn:aws-cn:eks:cn-northwest-1:12345:cluster/amq-stack-k8s-cluster-cn-northwest-1-env-yglrthcymngsbsyjl2jt
  name: arn:aws-cn:eks:cn-northwest-1:12345:cluster/amq-stack-k8s-cluster-cn-northwest-1-env-yglrthcymngsbsyjl2jt
current-context: arn:aws-cn:eks:cn-northwest-1:12345:cluster/amq-stack-k8s-cluster-cn-northwest-1-env-yglrthcymngsbsyjl2jt
kind: Config
preferences: {}
users:
- name: arn:aws-cn:eks:cn-northwest-1:12345:cluster/amq-stack-k8s-cluster-cn-northwest-1-env-yglrthcymngsbsyjl2jt
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - cn-northwest-1
      - eks
      - get-token
      - --cluster-name
      - amq-stack-k8s-cluster-cn-northwest-1-env-yglrthcymngsbsyjl2jt
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: cn-dev-install-console-create-resource

```
