### ISSUE TITLE
Traefik ingress Example on K0s website is outdated.

### ISSUE THREAD

**Issue by gavan-x** [lensapp/lens#7989]
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - role: controller+worker
    noTaints: true
    ssh:
      address: 192.168.1.110 
      user: root
      keyPath: ~/.ssh/id_rsa
  - role: controller+worker
    noTaints: true
    ssh:
      address: 192.168.1.114  
      user: root
      keyPath: ~/.ssh/id_rsa
  - role: controller+worker
    noTaints: true
    ssh:
      address: 192.168.1.112  
      user: root
      keyPath: ~/.ssh/id_rsa                  
  k0s:
    version: v1.28.4+k0s.0
    dynamicConfig: false
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
       name: k0s-cluster
      spec:        
        network:
          nodeLocalLoadBalancing:
            enabled: true
            type: EnvoyProxy    
        extensions:
          helm:
            repositories:
            - name: traefik
              url: https://traefik.github.io/charts
            - name: bitnami
              url: https://charts.bitnami.com/bitnami
            charts:
            - name: traefik
              chartname: traefik/traefik
              version: "20.5.3"
              namespace: default
            - name: metallb
              chartname: bitnami/metallb
              version: "2.5.4"
              namespace: default
              values: |
                configInline:
                  address-pools:
                  - name: generic-cluster-pool
                    protocol: layer2
                    addresses:
                    - 192.168.1.150-192.168.9.155
```

The above yaml uses k0sctl v1.28.4+k0s.0, and follows the Traefik Ingress example on  k0s official [docs] while selecting documentation for v1.28.4+k0s.0 (https://docs.k0sproject.io/v1.28.4+k0s.0/examples/traefik-ingress/).

k0sctl bootstraps the cluster with no error but when running `k0s kubectl get all` (as per example) traefik does not get an external IP assigned.

`service/traefik      LoadBalancer   10.96.226.129   <pending>     80:30193/TCP,443:31634/TCP   74s`

`daemonset.apps/metallb` is also not listed in pods

The example listed on k0s is using an outdated example from 2020 linked here https://traefik.io/blog/from-zero-to-hero-getting-started-with-k0s-and-traefik/
