### ISSUE TITLE
Lens doesn't list HPAs in GKE

### ISSUE THREAD

**Issue by matti** [lensapp/lens#80]
```
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: slave
  namespace: ruoska
spec:
  minReplicas: 1
  maxReplicas: 999
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: slave
  targetCPUUtilizationPercentage: 25
```

^-- this is not visible in HPA listing and `autoscaling/v2beta2` that would (?) be visible is not supported in GKE (atleast in 1.13 or 1.14) - only `autoscaling/v2beta1` is and that is not visible in lens either.
