### ISSUE TITLE
Lens Desktop: Error handling on "Create resource" is broken

### ISSUE THREAD

**Issue by rfx77** [lensapp/lens#8019]
When is create a resource in Lens Desktop Personal and there is some error in the yaml i dont get a info with the real reason. It always shows "Unknown error occured while creating resource"

with kubectl it shows the real reason

Sample yaml with error:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystemx
  resources:
    requests:
```

kubectl says correctly: `The PersistentVolumeClaim "myclaim3" is invalid: spec.resources[storage]: Required value`

this is what lens says 

![image](https://github.com/lensapp/lens/assets/61699304/a06c3fcc-6bc7-4398-accd-f43330bf30ee)

![image](https://github.com/lensapp/lens/assets/61699304/3d7c7373-6c3f-4783-b1cf-ee29a4fdf434)

--------------------------

My environment:
Lens Desktop Personal: 2024.1.300751-latest (on Windows 10)
Kubernetes: RKE2 1.27.10 on Linux
