### ISSUE TITLE
When trying to connect to the cluster via lens: Failed to get /version for clusterId=id Internal Server Errorr

### ISSUE THREAD

**Issue by AjayEdupuganti** [lensapp/lens#8057]
I am trying to connect to my kubernetes cluster which was spunup using kubeadm on aws instances.

I am using lens desktop app on windows.

My kubeconfig file

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://<private ip address of the master>:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
```

i think the issue is with private ip address as server. kindly help me with this error

> E0607 15:01:56.696813 3604 proxy_server.go:147] Error while proxying request: dial tcp :6443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. Failed to get /version for clusterId=: Internal Server Error

If i change the config file and add public ip address there i am getting another error

> E0607 16:25:02.787250 484 proxy_server.go:147] Error while proxying request: tls: failed to verify certificate: x509: certificate is valid certificate is valid for privateip1, privateip2, not publicip of the master

> Failed to get /version for clusterId=clusterid: Internal Server Error
