### ISSUE TITLE
Unable to read property 'kc' of undefined

### ISSUE THREAD

**Issue by mattholmes15** [lensapp/lens#806]
**Describe the bug**
Unable to add any kube config - using Lens 3.5.3 on Mac.

**To Reproduce**
1. Go to quick launch menu
2. Select any kubeconfig or custom config from the drop down
3. Error 'Cannot read property 'kc' of undefined 

**Expected behavior**
Add a kubernetes cluster to the config and see through the Lens dashboard.

**Screenshots**
![Screenshot 2020-09-04 at 16 33 17](https://user-images.githubusercontent.com/20838965/92257433-21bd9380-eecd-11ea-99ff-2d294b7c4eef.png)

See also the error below when exiting Lens:
![Screenshot 2020-09-04 at 16 33 29](https://user-images.githubusercontent.com/20838965/92257505-3dc13500-eecd-11ea-934c-f38d704aa12c.png)

**Environment (please complete the following information):**
- Lens Version: 3.5.3
- OS: OSX
- Installation method  `brew cask install lens`

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
- Happens with any kubeconfig (i have access to upwards of 20+ clusters), here is my minikube config as an example

```
apiVersion: v1
kind: Config
preferences: {}
current-context: minikube
clusters:
  - name: minikube
    cluster:
      certificate-authority: /Users/User/.minikube/ca.crt
      server: 'https://192.168.99.100:8443'
      insecure-skip-tls-verify: false
contexts:
  - name: minikube
    context:
      cluster: minikube
      user: minikube
users:
  - name: minikube
    user:
      client-certificate: /Users/User/.minikube/profiles/minikube/client.crt
      client-key: /Users/User/.minikube/profiles/minikube/client.key
```

**Additional context**
I also recieve the JavaScript error in the screenshot when exiting.
