### ISSUE TITLE
Reload command displays blank pages

### ISSUE THREAD

**Issue by romainourgorry** [lensapp/lens#8099]
**Describe the bug**
When I'm using Lens and I run a "relaod" (by command+R or by the menu) the screen becomes blank for all the pages of the current cluster (other clusters are not affected except if I reload one page on them)
I need to kill Lens app and start it again to fix it.

In the steps I mentioned the Overview page but I can any page.

**To Reproduce**
1. Open Lens
2. Select a cluster
3. Select Overview page
4. Reload the page (cmd+R or view->Reload)
5. The Overview page is now fully blank

**Expected behavior**
The overview page should be reloaded

**Screenshots**
Before reload:
![Screenshot 2024-10-04 at 11 49 13](https://github.com/user-attachments/assets/4e6116dd-6d72-4281-a1f9-9a14cb11802c)

After reload:
![Screenshot 2024-10-04 at 11 49 20](https://github.com/user-attachments/assets/e19fd62b-0bd6-4169-8df1-7500f35aee3b)

**Environment (please complete the following information):**
- Lens Version: 2024.9.300059-latest
- OS: Mac OS 15.0.1
- Installation method (e.g. snap or AppImage in Linux): Download from website (.dmg file)

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "first-application-window" loaded +6s
[ELECTRON-SYNC-STORE]: 2024-10-04T09:50:35.395Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-10-04T09:50:35.395Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
[ELECTRON-SYNC-STORE]: 2024-10-04T09:50:35.456Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-10-04T09:50:35.456Z - select-space-store ~ ipc electron-sync-store:renderer:initialize:select-space-store received
[ELECTRON-SYNC-STORE]: 2024-10-04T09:50:35.456Z - startup-store ~ ipc electron-sync-store:renderer:initialize:startup-store received
info:    ▪ [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "after-root-frame-is-ready" took 0.07 ms.

Individual runnables took:
- lens-core-main:start-catalog-sync     	1.27 ms
- lens-core-main:flag-renderer-as-loaded	0.08 ms +810ms
Error occurred in handler for 'get-demo-cluster-config-channel': Error: You are not allowed to access the demo-cluster config.
    at /Applications/Lens.app/Contents/Resources/app.asar/node_modules/@lensapp/lens-platform-client-main/dist/index.js:188:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:83654)
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXXX
    server: https://my-cluster-XXX.francecentral.azmk8s.io:443
  name: my-cluster-XXX
contexts:
- context:
    cluster: my-cluster-XXX
    user: clusterUser_my-cluster-XXX_my-cluster-XXX
  name: my-cluster-XXX
current-context: my-cluster-XXX
kind: Config
preferences: {}
users:
- name: clusterUser_my-cluster-XXX_my-cluster-XXX
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --environment
      - AzurePublicCloud
      - --server-id
      - XXXXXX-XXXX-XXXX
      - --client-id
      - XXXXXX-XXXX-XXXX
      - --tenant-id
      - XXXXXX-XXXX-XXXX
      - --login
      - devicecode
      command: kubelogin
      env: null
      installHint: '

        kubelogin is not installed which is required to connect to AAD enabled cluster.


        To learn more, please go to https://aka.ms/aks/kubelogin

        '
      provideClusterInfo: false
```

**Additional context**
I removed and recreate my Kubeconfig to be fully new.
