### ISSUE TITLE
Cannot connect cause of proxy authentication

### ISSUE THREAD

**Issue by K4leri** [lensapp/lens#8105]
**Describe the bug**
I just installed new version of lens and it tries to use proxy conection for no reason.
I have never use proxy and i dont have set up them. 

**To Reproduce**
1. I decide to install new version
2. after installed i cant connect cause of luck conection to proxy

**Expected behavior**
I dont wanna my lens use proxy conection if i dont have any proxy conections.

**Screenshots**
![изображение](https://github.com/user-attachments/assets/30bad410-a1e5-4d2e-bc19-6113e5366c55)

**Environment (please complete the following information):**
- Lens Setup: 2024.9.300059-latest.exe
- OS: Windows 10 22H2 19045.2965

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: ...
  name: ...
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: ...
  name: ...
contexts:
- context:
    cluster: ...
    user: ...
  name: yc-general
- context:
    cluster: ...
    user: ...
  name: yc-kube-massive
current-context: yc-general
kind: Config
preferences: {}
users:
- name: ...
  user:
    exec:
      apiVersion: ...
      args:
      - k8s
      - create-token
      - --profile=...
      command: C:\Users\...\yandex-cloud\bin\yc.exe
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: ...
  user:
    exec:
      apiVersion: ...
      args:
      - k8s
      - create-token
      - --profile=easycommerse
      command: ...
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Aditional content:**
- k9s works fine at the same setup.
- Close to https://github.com/lensapp/lens/issues/2189
