### ISSUE TITLE
Pod exec and port-forwarding to Kubernetes don’t work from Lens (After last update)

### ISSUE THREAD

**Issue by sm1lexops** [lensapp/lens#8113]
**Describe the bug**
I am unable to execute commands in pods or use port-forwarding via Lens GUI or Lens’ integrated terminal CLI (after last update).

**To Reproduce**
	1.	Open Lens.
	2.	Navigate to the desired pod in the Pods section.
	3.	Click on Pod Shell or Attach to Pod.
	4.	Attempt to exec into the pod.
	
error output:

`exec /usr/local/bin/kubectl exec -i -t -n gitlab-ci gitlab-runner-5d48dc4f94-2j8kr -c gitlab-runner -- sh -c "clear; (bash || ash || sh)"                                                                                      ✔ │ aleks.com ⎈ 
error: unable to upgrade connection: error dialing backend: read tcp 192.168.101.120:60692->xx.xx.xx.xx:443: read: network is down
Terminal will auto-close in 15 seconds ...`

same when try to port-forward:
All is working from local env terminal CLI

`Port Forwarding
Error occurred starting port-forward, the local port may not be available or the pod devops-atd-qa1-d56b6f558-jhhjk may not be reachable
`

**Expected behavior**
exec to pod or port-forward success

**Environment (please complete the following information):**
	•	macOS 14.x, 15.x (desktop)
	•	Linux Ubuntu 24.04 (desktop)

**Kubeconfig:**
Using OIDC Dex 

```
- name: aleks.org
  user:
    auth-provider:
      config:
        client-id: k8s-authenticator
        client-secret: 
        id-token: 
        idp-issuer-url: https://test-dex.com
        refresh-token: 
      name: oidc
```

**Additional context**
when I delete the  and unset KUBECONFIG it directly from the Lens integrated terminal, it works as expected.
`
unset KUBECONFIG
`

**Screenshots**

![Screenshot 2024-10-18 at 13 59 24](https://github.com/user-attachments/assets/f737dedd-f105-40e3-9302-ae7a310bb9d4)

![Screenshot 2024-10-18 at 14 03 38](https://github.com/user-attachments/assets/15597558-00c4-46c5-99ac-2d58afb9e409)

![Screenshot 2024-10-18 at 14 02 46](https://github.com/user-attachments/assets/9dcb5df5-cdd7-4a37-89ff-6263250fb183)
