### ISSUE TITLE
Applications view is broken when several application instances are deployed

### ISSUE THREAD

**Issue by random-ua** [lensapp/lens#8153]
We have several instances of application deployed into a single namespace, each with unique instance id, version and other labels set according to rules from https://docs.k8slens.dev/using-lens/applications/ and https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/.

Lens: 2024.8.291605-latest shows everything just fine (as seen on screenshot 1)

More recent versions (e.g. Lens: 2024.11.261604-latest)  show all instances as having the same version, age and instance id (screenshot 2).

This leads to other UI bugs:
 - ApplicationInstance panel shows Pods and Deployments of all instances. But is doesn't show URLs exposed via Ingresses for any of them (unlike an older version)
 - "More actions" menu is only available for the first item in list

**To Reproduce**
Create several deployments in a single namespace with the same `app.kubernetes.io/name` label but different version and `app.kubernetes.io/instance`, e.g.:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platform-fra
    app.kubernetes.io/instance: first
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: platform
    app.kubernetes.io/version: 223fcd99
    argocd.argoproj.io/instance: platform
....
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: platform-fra
    app.kubernetes.io/instance: second
    app.kubernetes.io/managed-by: ArgoCD
    app.kubernetes.io/name: platform
    app.kubernetes.io/version: 22222222
    argocd.argoproj.io/instance: platform
```

Note: ` argocd.argoproj.io/instance` is added automatically by ArgoCD.

**Environment:**
- Lens Version: 2024.11
- OS: OSX on ARM
- Installation method: brew

**Screenshots:**

From Lens: 2024.8:
<img width="1082" alt="screenshot1" src="https://github.com/user-attachments/assets/9245bc46-edce-4e56-bf2d-85b3a4321cfc" />

From Lens: 2024.11:
<img width="1083" alt="screenshot2" src="https://github.com/user-attachments/assets/8e5c788a-c47c-4a8a-9a05-6b77b00ab17c" />
