### ISSUE TITLE
Lens in Ubuntu 24.04 using too much bandwidth.

### ISSUE THREAD

**Issue by fmpastoriko** [lensapp/lens#8193]
**Describe the bug**
Lens in Ubuntu 24.04 seems to be using too much bandwidth, around 200-300mb per 5 minutes.

**To Reproduce**
1. Leave Lens open for hours, no need to connect to any cluster. But if you do connect to a cluster, the data usage seems to increase.
2. Check internet usage, it'll use up to 200-300mb per 5 mins.

**Expected behavior**
I expect the bandwidth to not exceed, idk, maybe ~50mb every 5 minutes.

**Screenshots**

![Image](https://github.com/user-attachments/assets/95e756b9-2fd4-4d9d-b6b9-7360c1790464)

This shows the data usage using vnstat. Around 13:00 I close the lens app.

**Environment (please complete the following information):**
- Lens Version: 

![Image](https://github.com/user-attachments/assets/baf12305-11de-49d3-8f75-bda7c97613c2)

- OS: Ubuntu 24.04
- Installation method (e.g. snap or AppImage in Linux): Install Lens Desktop from the APT repository

**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
info:    ▪ [RUN-MANY-PERFORMANCE-LOGGING]: Running runnables for "before-anything" took 2.07 ms.

Individual runnables took:
- app-paths-setup-main:setup-app-paths	0.69 ms +0ms

```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxx
    server: xxx
  name: xxx
- cluster:
    certificate-authority-data: xxx
    server: xxx
  name: xxx
contexts:
- context:
    cluster: xxx
    user: xxx
  name: xxx
- context:
    cluster: xxx
    user: xxx
  name: xxx
current-context: xxx
kind: Config
preferences: {}
users:
- name: xxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true
- name: xxx
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true
```

**Additional context**
