### ISSUE TITLE
Network policy is not visualized correctly

### ISSUE THREAD

**Issue by skysaeed** [lensapp/lens#8195]
**Describe the bug**
the visualization for a list of Egress rules to different endpoint is not correct

**To Reproduce**
1. create a Network policy using this Egress rules : 
```
egress:
    - to:
        - ipBlock:
            cidr: 10.168.106.0/24
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
      to:
        - ipBlock:
            cidr: 10.243.0.10/32
```
2. deploy it to k8s
3. browse network policies 
4. See the wrong visualization. the ports should be dedicated for the second rule but not the first

**Expected behavior**
 the ports should be visualized under the second rule.

**Screenshots**

<img width="448" alt="Image" src="https://github.com/user-attachments/assets/11b0120d-eb3e-4758-989e-1f012e655f16" />

**Environment**
- Lens Version: 2025.2.141554-latest
- OS: macOS 15.3.1
