### ISSUE TITLE
Some Ingress description crashes

### ISSUE THREAD

**Issue by fert-f** [lensapp/lens#881]
**Describe the bug**
Some Ingress description crashes

**To Reproduce**
Go to Ingresses
Click on ingress
See error

**Expected behavior**
Ingress description is showed

**Screenshots**
![image](https://user-images.githubusercontent.com/45031838/93176899-a06ec800-f73a-11ea-9a3a-b293a4b3d915.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.0
- OS: 10.15.6
- DMG
 
**Logs:**
```
Error stack:

 
TypeError: Cannot read property 'length' of undefined
    at r.value (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:8204711)
    at r.value (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:8206631)
    at ve (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:33319)
    at http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:13199
    at ce (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:31425)
    at e.track (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:42789)
    at r.l [as render] (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:13147)
    at xo (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:4287558)
    at Po (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:4287353)
    at fs (http://0d7e2ec1-cc03-4246-99e2-66af060660fa.localhost:54163/build/Lens.js:2:4323152)```
```

**Kubeconfig:**
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: https://*****.eks.amazonaws.com
  name: ARN
contexts:
- context:
    cluster: ARN
    user: ARN
  name: ARN
current-context: ARN
kind: Config
preferences: {}
users:
- name: ARN
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - REGION
      - eks
      - get-token
      - --cluster-name
      - NAME
      command: aws
      env:
      - name: AWS_PROFILE
        value: PROFILE
```

**Additional context**
Lens crashes when trying to describe ingress (as I've seen, one's which has several 2+ rules)
