### ISSUE TITLE
Pod details not updating

### ISSUE THREAD

**Issue by madianas** [lensapp/lens#902]
**Describe the bug**
Environment variables in Pod details page are not updating.

**To Reproduce**
1. Go to 'Pods'
2. Click on any Pod to open details
3. Scroll down to 'Environment'
4. See current variables with their values
5. Change any variable value
6. Repeat steps 1-4
7. See old variable value

**Expected behavior**
Step 7: See updated environment value

**Screenshots**
![image](https://user-images.githubusercontent.com/7828566/93428348-16149880-f8e1-11ea-9c69-fb365439d6eb.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.0
- OS: Ubuntu 20.04
- Installation method: Snap 
 
**Logs:**
Don't have logs

**Kubeconfig:**
```
apiVersion: v1
kind: Config
preferences: {}
current-context: kubernetes-admin@k2.name1
clusters:
  - name: k2.name1
    cluster:
      certificate-authority-data: >-
        LS0tLS1C<>BVEUtLS0tLQo=
      server: 'https://10.10.6.250:6443'
      insecure-skip-tls-verify: false
contexts:
  - name: kubernetes-admin@k2.name1
    context:
      cluster: k2.name1
      user: kubernetes-admin-name1
users:
  - name: kubernetes-admin-name1
    user:
      client-certificate-data: >-
        LS0tLS1CR<>tLQo=
      client-key-data: >-
        LS0tLS1CRUdJTiBS<>VRFIEtFWS0tLS0tCg==
```

**Additional context**
In previous versions, one way to update environment values, was to Disconnect from cluster and connect back again. Fresh values loaded correctly then. In this version values are still cached. Closing the app completely helps.
