### ISSUE TITLE
Show last pod state and termination reason

### ISSUE THREAD

**Issue by Delorien84** [lensapp/lens#926]
**What would you like to be added**:
Sometimes pod is killed by various reason, but the reason is not visible in Lens. I need to execute kubectl command to see last state and reason why the pod was killed

```yaml
State:          Waiting
  Reason:       CrashLoopBackOff
Last State:     Terminated
  Reason:       OOMKilled
  Exit Code:    137
  Started:      Tue, 15 Sep 2020 08:45:37 +0200
  Finished:     Tue, 15 Sep 2020 08:45:38 +0200
```
**Why is this needed**:
I would like to see in pod detail Last State and Reason similary to see when executing kubectl describe pod <pod_name>.

**Environment you are Lens application on:**

- Kubernetes distribution: EKS
