### ISSUE TITLE
Editing a resource show latest available apiVersion, not the currently used apiVersion (upgrading kubernetes)

### ISSUE THREAD

**Issue by Richard87** [lensapp/lens#932]
**Describe the bug**
I'm working on upgrading our k8s cluster from v1.15 to v1.16, and trying to locate all deprecated resources.

When I'm looking at f.eks kube-system/kube-dns, and click edit, I get this content in the editor:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-dns
  namespace: kube-system
  selfLink: /apis/apps/v1/namespaces/kube-system/deployments/kube-dns
  uid: 99034a6c-f166-11e8-8b25-42010aa6001a
  resourceVersion: '218389145'
  ...
```

Bu when I run `kubectl get -n kube-system deployment kube-dns -o yaml` I get a different output:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    kubectl.kubernetes.io/last-applied-configuration: ...
```

**To Reproduce**
Seems to happen on all resources, I'm running Lens v3.6.3

**Expected behavior**
I want the editor to display the current live yaml.

(It would also be awesome to see deprecated resources in the UI :D)

**Screenshots**
![image](https://user-images.githubusercontent.com/5749715/93666387-1f873780-fa7e-11ea-92e2-745bdc3abaf3.png)
![image](https://user-images.githubusercontent.com/5749715/93666392-244beb80-fa7e-11ea-8051-3d83b285aebc.png)

**Environment (please complete the following information):**
- Lens Version: 3.6.3
- OS: Fedora 32
- Installation method:  snap
