### ISSUE TITLE
Problems connecting to GKE cluster

### ISSUE THREAD

**Issue by ariesyous** [lensapp/lens#944]
I've noticed this pattern of connecting to a Google Kubernetes Engine cluster where it works for a short period of time, then errors out and I'm never able to reconnect again. 

**Environment (please complete the following information):**
- Lens Version: 3.6.0
- OS: Windows 10 
- Installation method (e.g. snap or AppImage in Linux): MSI from Lens website

020/09/21 19:40:29 http: proxy error: error executing access token command "/usr/lib/google-cloud-sdk/bin/gcloud config config-helper --format=json": err=exec: "/usr/lib/google-cloud-sdk/bin/gcloud": file does not exist output= stderr=

**Comment by ariesyous** [comment]
Fixed this by just updating the cmd-path to just gcloud

Here is the kubeconfig snippet for reference:

```
users:
  - name: omitted
    user:
      auth-provider:
        config:
          cmd-args: config config-helper --format=json
          cmd-path: gcloud
          expiry-key: '{.credential.token_expiry}'
          token-key: '{.credential.access_token}'
        name: gcp
```

**Comment by davidgourde** [comment]
@ariesyous Awesome, thanks! This fixed my problem with WSL2, as the paths are Linux and Lens is installed on Windows, using Windows paths 😅

**Comment by StanislavYermolenko** [comment]
> @ariesyous Awesome, thanks! This fixed my problem with WSL2, as the paths are Linux and Lens is installed on Windows, using Windows paths 😅

Hi, stack with the same problem, can you share yours solution please?

**Comment by wasuaje** [comment]
@davidgourde How do you exactly fixed it? IDK what to do with @ariesyous snippet!

**Comment by asrathour12** [comment]
Did you manually edit it through vi?

**Comment by MrCoffey** [comment]
I faced the issue one more time, I had to edit manually my kube_config as follows:


This configuration fails with the following error:

```
- name: name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true
```

```
proxy_server.go:147] Error while proxying request: getting credentials: exec: executable gke-gcloud-auth-plugin not found It looks like you are trying to use a client-go credential plugin that is not installed. To learn more about this feature, consult the documentation available at: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
```

I had to manually edit the `command` field in my `.kube/config` to point to the path where the plugin was installed, I have to do this with every cluster:

```
- name: name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: /Users/google-cloud-sdk-2/bin/gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true

```

Even with the configuration lens shows errors:

```
print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exec: "gcloud": executable file not found in $PATH (err: )
```

**Comment by lopezvit** [comment]
> I faced the issue one more time, I had to edit manually my kube_config as follows:
> 
> This configuration fails with the following error:
> 
> ```
> - name: name
>   user:
>     exec:
>       apiVersion: client.authentication.k8s.io/v1beta1
>       command: gke-gcloud-auth-plugin
>       installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
>         https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
>       provideClusterInfo: true
> ```
> 
> ```
> proxy_server.go:147] Error while proxying request: getting credentials: exec: executable gke-gcloud-auth-plugin not found It looks like you are trying to use a client-go credential plugin that is not installed. To learn more about this feature, consult the documentation available at: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
> ```
> 
> I had to manually edit the `command` field in my `.kube/config` to point to the path where the plugin was installed, I have to do this with every cluster:
> 
> ```
> - name: name
>   user:
>     exec:
>       apiVersion: client.authentication.k8s.io/v1beta1
>       command: /Users/google-cloud-sdk-2/bin/gke-gcloud-auth-plugin
>       installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
>         https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
>       provideClusterInfo: true
> ```
> 
> Even with the configuration lens shows errors:
> 
> ```
> print credential failed with error: Failed to retrieve access token:: failure while executing gcloud, with args [config config-helper --format=json]: exec: "gcloud": executable file not found in $PATH (err: )
> ```

you are in the right direction, but you have to add the environment variable with the path to make it work:

```
- name: name
   user:
     exec:
       apiVersion: client.authentication.k8s.io/v1beta1
       command: /Users/google-cloud-sdk-2/bin/gke-gcloud-auth-plugin
       env:
       - name: PATH
         value: /Users/google-cloud-sdk-2/bin:/usr/local/bin:/usr/bin:/bin
       installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
         https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
       provideClusterInfo: true
```
