### ISSUE TITLE
Can't exec on pods

### ISSUE THREAD

**Issue by xaocon** [lensapp/lens#975]
**Describe the bug**
Lens no longer connects to a shell on pods on my setup. Maybe related to the proxy.

We have to connect to our clusters via a jumpbox so I open a socks proxy with ssh then use tinyproxy to act as a http -> socks proxy middle man. This works fine for the normal kubectl on my system with the HTTP_PROXY var set for the tinypoxy port but doesn't seem to work in Lens. If unset `KUBECONFIG` in Lens it work again. I'm on 3.6.4. I see there was a note in prior releases about the proxy not working in some cases but it wasn't in this one so I'm guessing it was resolved.

**To Reproduce**
1. Use a ssh jumpbox to reach k8s via a socks proxy `ssh -D 12345 <jumpbox>`
2. Set up a proxy server to act as HTTP to socks proxy (relevant tinyproxy config below)
```
Port 8118
Listen 127.0.0.1
upstream socks5 127.0.0.1:12345
```
3. Set up shell rc file to use proxy `export HTTP_PROXY=http://localhost:8118`
4. Open Lens and navigate to cluster with HTTP Proxy set in config `http://localhost:8118`
5. Look at pods, see them as expected.
6. Navigate to pod and click icon for `Pod shell`
7. Wait for timeout `error: unable to upgrade connection: error dialing backend: dial tcp <ip>: i/o timeout`
8. Copy and paste command into personal shell and see it work.

**Expected behavior**
Connect to pod shell

**Screenshots**

**Environment (please complete the following information):**
- Lens Version: 3.6.4
- OS: OSX
- brew cask installed but updated from within app
- In case it helps, tinyproxy also comes from brew `tinyproxy: stable 1.10.0 (bottled)`
 
**Logs:**
When you run the application executable from command line you will see some logging output. Please paste them here:
```
❯ exec kubectl exec -i -t -n <namespace> <pod> -c <container name> "--" sh -c "clear; (bash || ash || sh)"
error: unable to upgrade connection: error dialing backend: dial tcp <IP>: i/o timeout
Terminal will auto-close in 15 seconds ...
```

**Kubeconfig:**
Quite often the problems are caused by malformed kubeconfig which the application tries to load. Please share your kubeconfig, remember to remove any secret and sensitive information.
```
apiVersion: v1
kind: Config
preferences: {}
current-context: <redacted>
clusters:
  - name: <redacted>
    cluster:
      server: 'http://127.0.0.1:52181/<UUID>'
contexts:
  - name: <redacted>
    context:
      cluster: <redacted>
      user: proxy
users:
  - name: proxy
    user: {}
```

**Additional context**
