### ISSUE TITLE
StatefulSet sidebar Pods list is incorrect when two StatefulSets have the same name

### ISSUE THREAD

**Issue by vreon** [lensapp/lens#99]
**Describe the bug**
The sidebar Pods list for a given StatefulSet seems to include Pods belonging to _any_ StatefulSet with that name, even if they're in different Namespaces.

**To Reproduce**
1. Consider a cluster that has two namespaces: `testns1` and `testns2`. Inside each one is a StatefulSet named `web`, each with 3 replicas.

    <details>
    <summary>Example YAML for this scenario</summary>

    ```yaml
    apiVersion: v1
    kind: Namespace
    metadata:
      name: testns1
    ---
    apiVersion: v1
    kind: Namespace
    metadata:
      name: testns2
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: web
      namespace: testns1
    spec:
      ports:
      - port: 80
        name: web
      clusterIP: None
      selector:
        app: web
    ---
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: web
      namespace: testns1
    spec:
      selector:
        matchLabels:
          app: web
      serviceName: web
      replicas: 3
      template:
        metadata:
          labels:
            app: web
        spec:
          containers:
          - name: nginx
            image: k8s.gcr.io/nginx-slim:0.8
            ports:
            - containerPort: 80
              name: web
    ---
    apiVersion: v1
    kind: Service
    metadata:
      name: web
      namespace: testns2
    spec:
      ports:
      - port: 80
        name: web
      clusterIP: None
      selector:
        app: web
    ---
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: web
      namespace: testns2
    spec:
      selector:
        matchLabels:
          app: web
      serviceName: web
      replicas: 3
      template:
        metadata:
          labels:
            app: web
        spec:
          containers:
          - name: nginx
            image: k8s.gcr.io/nginx-slim:0.8
            ports:
            - containerPort: 80
              name: web
    ```

    </details>

2. In Lens, click on **Workloads** > **StatefulSets**.
3. Click the `web` StatefulSet in `testns1`.
4. In the sidebar, the **Pods** list displays Pods belonging to the `testns1` `web` StatefulSet, but also Pods belonging to the `testns2` `web` StatefulSet. The **Pod Status** field also incorrectly includes all six Pods.

**Expected behavior**
Expected to see just a list of Pods belonging to the `testns1` `web` StatefulSet.

**Screenshots**
![Screenshot_2019-11-29_22-49-35](https://user-images.githubusercontent.com/52548/69897105-dbaf2000-12fb-11ea-9f39-ff190c01b2ad.png)

**Environment (please complete the following information):**
- Lens Version: 2.6.5
- OS: Arch Linux
- Installation method (e.g. snap or AppImage in Linux): AppImage
 
**Logs:**
n/a

**Kubeconfig:**
n/a

**Additional context**
n/a
